### ISSUE TITLE
RedisCache is not a constructor

### ISSUE THREAD

**Issue by iepsen** [apollographql/apollo-server#1299]
I'm trying to use `apollo-server-redis` as a cache but it isn't working:

```node
$ node index.js 
/Users/iepsen/apollo/index.js:20
    cache: new RedisCache({
           ^

TypeError: RedisCache is not a constructor
    at Object.<anonymous> (/Users/iepsen/apollo/index.js:20:12)
    at Module._compile (module.js:652:30)
    at Object.Module._extensions..js (module.js:663:10)
    at Module.load (module.js:565:32)
    at tryModuleLoad (module.js:505:12)
    at Function.Module._load (module.js:497:3)
    at Function.Module.runMain (module.js:693:10)
    at startup (bootstrap_node.js:188:16)
    at bootstrap_node.js:609:3
```

package.json:
```json
{
  "name": "guide-graphql",
  "version": "1.0.0",
  "description": "",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "apollo-datasource-rest": "^2.0.0-rc.6",
    "apollo-server": "^2.0.0-rc.6",
    "apollo-server-redis": "^2.0.0-rc.0",
    "graphql": "^0.13.2"
  }
}
```

index.js:
```js
const server = new ApolloServer({
    typeDefs,
    resolvers,
    cache: new RedisCache({
        host: '127.0.0.1',
    }),
    dataSources: () => {
        return {
            guide: new GuideAPI()
        }
    }
});
```

node and typescript version:
```sh
$ node --version
v8.11.1

$ tsc --version
Version 2.9.2
```

I forgot something?

Thanks!

**Comment by JacobT14** [comment]
Change apollo-server-redis to 2.0.0-rc.6 and that should resolve it!

**Comment by iepsen** [comment]
@JacobT14, it worked. Btw, I added `apollo-server-redis` without version and default is `apollo-server-redis@2.0.0-rc.0`. Adding with `@rc` installs `rc.6`.

Thank you!
