### ISSUE TITLE
Error messages related to server error 400 should display more information when available

### ISSUE THREAD

**Issue by joeflack4** [apollographql/apollo-server#1394]
## Expected Behavior
When receiving an error that would produce  a generic error 400, I feel as if this should be something more descriptive, telling me something about why there was an error and perhaps where the error is located.

## Actual Behavior
When starting a new project using Apollo and `neo4jgraphql` and a relatively non-complex schema, I encounter a generic, non-descriptive error 400 when trying to seed the database with very little seed data (actual error message shown in "code snippets").

### Short reproduction
**Update: ** I figured out what was causing the issue. So the short reproduction would be the following...

Perform a mutation with the following syntax error: multiple mutations at the same time, but with the same key. For example,

```graphql
mutation {
    thisKeyIsIdenticalToAnotherInTheSameMutation: CreateUser(id: "u1",  username: "user1") { id }
    thisKeyIsIdenticalToAnotherInTheSameMutation: CreateUser(id: "u2",  username: "user2") { id }
}  
```

### Long reproduction
1. `git clone https://github.com/the-health-hub/health-hub.api.git && cd health-hub.api/`
2. `npm install`
3. Follow [these steps](https://github.com/grand-stack/grand-stack-starter) to start a local or remote Neo4j db (sorry; I know this part isn't "simple").
4. `npm start`
5. After starting, and in a separate shell, navigate to root of repo and: `npm run seedDb`

## Background information
I am using the function `neo4jgraphql` from `neo4j-graphql-js` to auto-generate resolvers. Then, I'm using `makeExecutableSchema` from `apollo-server`. Then, I'm using `augmentSchema` from `neo4j-graphql-js` to auto-generate mutations.

Following that initial and running of apollo-server, I then run a file called `seed-db.js` to load some initial data into the graph db via a single mutation.

When running it, however, I get a console error with a generic error 400. I feel as if this should be more descriptive, telling me something about why there was an error and perhaps where the error is located.

I'll show code snippets for the two relevant files, then an output of the warnings.

As a final note, I'm using the [grand-stack-starter](https://github.com/grand-stack/grand-stack-starter/tree/master/api) as my base, and I haven't yet added much code since cloning it.

### File 1 - `graphql-schema.js`  
```javascript
import gql from "graphql-tag";
import { print } from 'graphql/language/printer'
import { neo4jgraphql } from "neo4j-graphql-js";

export const typeDefs = print(gql`

# Simple Types
scalar Date
scalar DateTime
scalar Email
scalar PhoneNumber
scalar ZeroToOne

enum state_code {
  AL
  AndSoOn # TODO
}

# People
interface Person {
  id: ID!
  person_name_first: String
  person_name_last: String
  person_name_middle: String
  person_name_suffix: String
  person_name_prefix: String
  person_dob: DateTime
}

interface ContactInfo {
  id: ID!
  contact_address_street: String
  contact_address_city: String
  contact_address_state: String
  contact_address_country: String
  contact_emails: [Email]
  contact_phones: [PhoneNumber]
}

type Contact implements Person & ContactInfo {
  id: ID!
  person_name_first: String
  person_name_last: String
  person_name_middle: String
  person_name_suffix: String
  person_name_prefix: String
  person_dob: DateTime
  contact_address_street: String
  contact_address_city: String
  contact_address_state: String
  contact_address_country: String
  contact_emails: [Email]
  contact_phones: [PhoneNumber]
  contacts(first: Int = 10, offset: Int = 0): [User] @relation(name: "PERSONAL_CONTACT", direction: "BOTH")
}

type User implements Person & ContactInfo {
  id: ID!
  username: String!
  password: String!  # Handle auth otherwise: https://blog.apollographql.com/a-guide-to-authentication-in-graphql-e002a4039d1
  person_name_first: String
  person_name_last: String
  person_name_middle: String
  person_name_suffix: String
  person_name_prefix: String
  person_dob: DateTime
  contact_address_street: String
  contact_address_city: String
  contact_address_state: String
  contact_address_country: String
  contact_emails: [Email!]
  contact_phones: [PhoneNumber]
  contacts(first: Int = 10, offset: Int = 0): [User] @relation(name: "PERSONAL_CONTACT", direction: "BOTH")
}

# Afflictions
interface Illness {
  id: ID!
  illness_name: String
  illness_description: String
  illness_date_onset: String
}

interface Diagnosis {
  id: ID!
  diagnosis_name: String
  diagnosis_description: String
  diagnosis_given_date: String
  diagnosis_given_by_id: ID # to doctor
}

type AfflictionGlaucoma implements Illness & Diagnosis {
  id: ID!
  illness_name: String
  illness_description: String
  illness_date_onset: String
  diagnosis_name: String
  diagnosis_description: String
  diagnosis_given_date: String
  diagnosis_given_by_id: ID # to doctor
}

# Symptoms
# - make a type for every symptom or just one type w/ props?
interface Symptom {
  id: ID!
  name: String
  description: String
}

interface SymptomExperienced {
  id: ID! # is this id of the instance, or symptom type class?
  by: ID! # can I pass this in? not auto-generated?
  name: String
  description: String
  when: DateTime! # dateTime
  adversity_self_ranked_ascending: ZeroToOne!  # default step size should be 0.1; so a range of 10.
  comorbidities: [ID!]
}

type SymptomDizziness {
  id: ID!
  by: ID!
  name: String
  description: String
  when: DateTime!
  adversity_self_ranked_ascending: ZeroToOne!
  comorbidities: [Symptom!]
}

type EyePain {
  id: ID!
  by: ID!
  name: String
  description: String
  when: DateTime!
  adversity_self_ranked_ascending: ZeroToOne!
  comorbidities: [Symptom!]
}

type NightHalos {
  id: ID!
  by: ID!
  name: String
  description: String
  when: DateTime!
  adversity_self_ranked_ascending: ZeroToOne!
  comorbidities: [Symptom!]
}

type TunnelVision {
  id: ID!
  by: ID!
  name: String
  description: String
  when: DateTime!
  adversity_self_ranked_ascending: ZeroToOne!
  comorbidities: [Symptom!]
}

type BlurredVision {
  id: ID!
  by: ID!
  name: String
  description: String
  when: DateTime!
  adversity_self_ranked_ascending: ZeroToOne!
  comorbidities: [Symptom!]
}

type SwellingAndRedness {
  id: ID!
  by: ID!
  name: String
  description: String
  when: DateTime!
  adversity_self_ranked_ascending: ZeroToOne!
  comorbidities: [Symptom!]
}

type AccompanyingNausea {
  id: ID!
  by: ID!
  name: String
  description: String
  when: DateTime!
  adversity_self_ranked_ascending: ZeroToOne!
  comorbidities: [Symptom!]
}

type SuddenVisualDisturbance {
  id: ID!
  by: ID!
  name: String
  description: String
  when: DateTime!
  adversity_self_ranked_ascending: ZeroToOne!
  comorbidities: [Symptom!]
}

# Measurements
interface Measurement {
  id: ID!
  measurement: Float!
  measurement_units: String!
  measured_by: Person
}

interface DiagnosticMeasurementReading {
  id: ID!
  measurement: Float!
  measurement_units: String!
  when: DateTime
  reported_by: Person!
  experienced_by: Person!
  measured_by: Person
}

type ReadingBloodPressure implements DiagnosticMeasurementReading {
  id: ID!
  measurement: Float!
  measurement_units: String!
  when: DateTime
  reported_by: Person!
  experienced_by: Person!
  measured_by: Person
}

type IopLeft implements DiagnosticMeasurementReading {
  id: ID!
  measurement: Float!
  measurement_units: String!
  when: DateTime
  reported_by: Person!
  experienced_by: Person!
  measured_by: Person
}

type IopRight implements DiagnosticMeasurementReading {
  id: ID!
  measurement: Float!
  measurement_units: String!
  when: DateTime
  reported_by: Person!
  experienced_by: Person!
  measured_by: Person
}

type CorneaThicknessLeft implements DiagnosticMeasurementReading {
  id: ID!
  measurement: Float!
  measurement_units: String!
  when: DateTime
  reported_by: Person!
  experienced_by: Person!
  measured_by: Person
}

type CorneaThicknessRight implements DiagnosticMeasurementReading {
  id: ID!
  measurement: Float!
  measurement_units: String!
  when: DateTime
  reported_by: Person!
  experienced_by: Person!
  measured_by: Person
}

type CorneaThicknessCorrectionLeft implements DiagnosticMeasurementReading {
  id: ID!
  measurement: Float!
  measurement_units: String!
  when: DateTime
  reported_by: Person!
  experienced_by: Person!
  measured_by: Person
}

type CorneaThicknessCorrectionRight implements DiagnosticMeasurementReading {
  id: ID!
  measurement: Float!
  measurement_units: String!
  when: DateTime
  reported_by: Person!
  experienced_by: Person!
  measured_by: Person
}

type Query {
    # person(id: ID, first: Int = 10, offset: Int = 0): [Person]
    # contactinfo(id: ID, first: Int = 10, offset: Int = 0): [ContactInfo]
    contact(id: ID, first: Int = 10, offset: Int = 0): [Contact]
    user(id: ID, first: Int = 10, offset: Int = 0): [User]
    # illness(id: ID, first: Int = 10, offset: Int = 0): [Illness]
    # diagnosis(id: ID, first: Int = 10, offset: Int = 0): [Diagnosis]
    afflictionglaucoma(id: ID, first: Int = 10, offset: Int = 0): [AfflictionGlaucoma]
    # symptom(id: ID, first: Int = 10, offset: Int = 0): [Symptom]
    # symptomexperienced(id: ID, first: Int = 10, offset: Int = 0): [SymptomExperienced]
    symptomdizziness(id: ID, first: Int = 10, offset: Int = 0): [SymptomDizziness]
    eyepain(id: ID, first: Int = 10, offset: Int = 0): [EyePain]
    nighthalos(id: ID, first: Int = 10, offset: Int = 0): [NightHalos]
    tunnelvision(id: ID, first: Int = 10, offset: Int = 0): [TunnelVision]
    blurredvision(id: ID, first: Int = 10, offset: Int = 0): [BlurredVision]
    swellingandredness(id: ID, first: Int = 10, offset: Int = 0): [SwellingAndRedness]
    accompanyingnausea(id: ID, first: Int = 10, offset: Int = 0): [AccompanyingNausea]
    suddenvisualdisturbance(id: ID, first: Int = 10, offset: Int = 0): [SuddenVisualDisturbance]
    # measurement(id: ID, first: Int = 10, offset: Int = 0): [Measurement]
    # diagnosticmeasurementreading(id: ID, first: Int = 10, offset: Int = 0): [DiagnosticMeasurementReading]
    readingbloodpressure(id: ID, first: Int = 10, offset: Int = 0): [ReadingBloodPressure]
    iopleft(id: ID, first: Int = 10, offset: Int = 0): [IopLeft]
    iopright(id: ID, first: Int = 10, offset: Int = 0): [IopRight]
    corneathicknessleft(id: ID, first: Int = 10, offset: Int = 0): [CorneaThicknessLeft]
    corneathicknessright(id: ID, first: Int = 10, offset: Int = 0): [CorneaThicknessRight]
    corneathicknesscorrectionleft(id: ID, first: Int = 10, offset: Int = 0): [CorneaThicknessCorrectionLeft]
    corneathicknesscorrectionright(id: ID, first: Int = 10, offset: Int = 0): [CorneaThicknessCorrectionRight]

    userBySubstringOfName(substring: String, first: Int = 10, offset: Int = 0): [User] @cypher(statement: "MATCH (u:User) WHERE u.name CONTAINS $substring RETURN u")
}
`);

export const resolvers = {
  Query: {
    // person: neo4jgraphql,
    // contactinfo: neo4jgraphql,
    contact: neo4jgraphql,
    user: neo4jgraphql,
    // illness: neo4jgraphql,
    // diagnosis: neo4jgraphql,
    afflictionglaucoma: neo4jgraphql,
    // symptom: neo4jgraphql,
    // symptomexperienced: neo4jgraphql,
    symptomdizziness: neo4jgraphql,
    eyepain: neo4jgraphql,
    nighthalos: neo4jgraphql,
    tunnelvision: neo4jgraphql,
    blurredvision: neo4jgraphql,
    swellingandredness: neo4jgraphql,
    accompanyingnausea: neo4jgraphql,
    suddenvisualdisturbance: neo4jgraphql,
    // measurement: neo4jgraphql,
    // diagnosticmeasurementreading: neo4jgraphql,
    readingbloodpressure: neo4jgraphql,
    iopleft: neo4jgraphql,
    iopright: neo4jgraphql,
    corneathicknessleft: neo4jgraphql,
    corneathicknessright: neo4jgraphql,
    corneathicknesscorrectionleft: neo4jgraphql,
    corneathicknesscorrectionright: neo4jgraphql,
    userBySubstringOfName: neo4jgraphql,
  }
};
```

### File 2 - `index.js`  
```javascript
import { typeDefs, resolvers } from "./graphql-schema";
import { ApolloServer, makeExecutableSchema } from "apollo-server";
import { v1 as neo4j } from "neo4j-driver";
import { augmentSchema } from "neo4j-graphql-js";
import dotenv from "dotenv";

dotenv.config();

const schema = makeExecutableSchema({
  typeDefs,
  resolvers,
  resolverValidationOptions: {
    requireResolversForResolveType: false
  }
});

const augmentedSchema = augmentSchema(schema);

const driver = neo4j.driver(
  process.env.NEO4J_URI || "bolt://localhost:7687",
  neo4j.auth.basic(
    process.env.NEO4J_USER || "neo4j",
    process.env.NEO4J_PASSWORD || "neo4j"
  )
);

const server = new ApolloServer({
  context: { driver },
  schema: augmentedSchema
});

server.listen(process.env.GRAPHQL_LISTEN_PORT, '0.0.0.0').then(({ url }) => {
  console.log(`GraphQL API ready at ${url}`);
});
```

### File 3 - `seed-db.js`  
```javascript
import ApolloClient from "apollo-client";
import gql from "graphql-tag";
import dotenv from "dotenv";
import seedmutations from "./seed-mutations";
import fetch from "node-fetch";
import { HttpLink } from "apollo-link-http";
import { InMemoryCache } from "apollo-cache-inmemory";

dotenv.config();

const client = new ApolloClient({
  link: new HttpLink({ uri: process.env.GRAPHQL_URI, fetch }),
  cache: new InMemoryCache()
});

client
  .mutate({
    mutation: gql(`mutation {
    u1: CreateUser(
      id: "u1", 
      username: "username"
      password: "password"
      nickname: "nickname"
      person_name_first: "firstname"
      person_name_last: "lastname"
      person_name_middle: "middlename"
      person_name_suffix: ""
      person_name_prefix: "Mrs."
      person_dob: "2000-01-01"
      contact_address_street: "101 Main St"
      contact_address_city: "Baltimore"
      contact_address_state: "MD"
      contact_address_zip: "21205"
      contact_address_country: "USA"
      contact_emails: ["username@gmail.com"]
      contact_phones: ["800-555-5555"]
    ) {
      id
      username
      nickname
    }

    u1: CreateUser(
      id: "u1", 
      username: "username2"
      password: "password"
      nickname: "nickname"
      person_name_first: "firstname"
      person_name_last: "lastname"
      person_name_middle: "middlename"
      person_name_suffix: ""
      person_name_prefix: "Mrs."
      person_dob: "2000-01-01"
      contact_address_street: "101 Main St"
      contact_address_city: "Baltimore"
      contact_address_state: "MD"
      contact_address_zip: "21205"
      contact_address_country: "USA"
      contact_emails: ["username2@gmail.com"]
      contact_phones: ["800-555-5555"]
    ) {
      id
      username
      nickname
    }
})
  })
  .then(data => console.log(data))
  .catch(error => console.error(error));
```

### Terminal warnings - on server start
```nodejs
> nodemon --exec babel-node src/index.js

[nodemon] 1.18.3
[nodemon] to restart at any time, enter `rs`
[nodemon] watching: *.*
[nodemon] starting `babel-node src/index.js`
Type "Person" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Type "ContactInfo" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Type "Illness" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Type "Diagnosis" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Type "Symptom" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Type "DiagnosticMeasurementReading" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Type "Measurement" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
Type "SymptomExperienced" is missing a "resolveType" resolver. Pass false into "resolverValidationOptions.requireResolversForResolveType" to disable this warning.
`onTypeConflict` is deprecated. Use schema transforms to customize merging logic.
GraphQL API ready at http://0.0.0.0:4000/
[nodemon] restarting due to changes...
[nodemon] starting `babel-node src/index.js`
```

### Terminal error trace - on mutation
```
health-hub-api@1.0.0 seedDb /Users/joeflack4/projects/hh-api
> babel-node src/seed/seed-db.js

{ Error: Network error: Response not successful: Received status code 400
    at new ApolloError (/Users/joeflack4/projects/hh-api/node_modules/src/errors/ApolloError.ts:56:5)
    at Object.error (/Users/joeflack4/projects/hh-api/node_modules/src/core/QueryManager.ts:228:13)
    at notifySubscription (/Users/joeflack4/projects/hh-api/node_modules/zen-observable/lib/Observable.js:130:18)
    at onNotify (/Users/joeflack4/projects/hh-api/node_modules/zen-observable/lib/Observable.js:161:3)
    at SubscriptionObserver.error (/Users/joeflack4/projects/hh-api/node_modules/zen-observable/lib/Observable.js:220:7)
    at /Users/joeflack4/projects/hh-api/node_modules/apollo-link-http/src/httpLink.ts:163:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  graphQLErrors: [],
  networkError:
   { Error: Response not successful: Received status code 400
    at throwServerError (/Users/joeflack4/projects/hh-api/node_modules/apollo-link-http-common/src/index.ts:113:17)
    at /Users/joeflack4/projects/hh-api/node_modules/apollo-link-http-common/src/index.ts:142:11
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
     response:
      Response {
        size: 0,
        timeout: 0,
        [Symbol(Body internals)]: [Object],
        [Symbol(Response internals)]: [Object] },
     statusCode: 400,
     result: { errors: [Array] } },
  message: 'Network error: Response not successful: Received status code 400',
  extraInfo: undefined }
(hh-api) Joe:hh-api joeflack4$ npm run seedDb

> health-hub-api@1.0.0 seedDb /Users/joeflack4/projects/hh-api
> babel-node src/seed/seed-db.js

{ Error: Network error: Response not successful: Received status code 400
    at new ApolloError (/Users/joeflack4/projects/hh-api/node_modules/src/errors/ApolloError.ts:56:5)
    at Object.error (/Users/joeflack4/projects/hh-api/node_modules/src/core/QueryManager.ts:228:13)
    at notifySubscription (/Users/joeflack4/projects/hh-api/node_modules/zen-observable/lib/Observable.js:130:18)
    at onNotify (/Users/joeflack4/projects/hh-api/node_modules/zen-observable/lib/Observable.js:161:3)
    at SubscriptionObserver.error (/Users/joeflack4/projects/hh-api/node_modules/zen-observable/lib/Observable.js:220:7)
    at /Users/joeflack4/projects/hh-api/node_modules/apollo-link-http/src/httpLink.ts:163:20
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
  graphQLErrors: [],
  networkError:
   { Error: Response not successful: Received status code 400
    at throwServerError (/Users/joeflack4/projects/hh-api/node_modules/apollo-link-http-common/src/index.ts:113:17)
    at /Users/joeflack4/projects/hh-api/node_modules/apollo-link-http-common/src/index.ts:142:11
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:160:7)
     response:
      Response {
        size: 0,
        timeout: 0,
        [Symbol(Body internals)]: [Object],
        [Symbol(Response internals)]: [Object] },
     statusCode: 400,
     result: { errors: [Array] } },
  message: 'Network error: Response not successful: Received status code 400',
  extraInfo: undefined
```

## Final Notes  

Would this issue be more appropriate in `apollo-server` or `apollo-link`? I've created issues in both.
- https://github.com/apollographql/apollo-server/issues/1394
- https://github.com/apollographql/apollo-link/issues/728

**Comment by JohnathanMaravilla** [comment]
> **Update: ** I figured out what was causing the issue.

@joeflack4,

I'm having a similar (if not the same) issue. It's not clear to me how you figured out what was causing the "Network error: Response not successful: Received status code 400". Can you please elaborate on how you resolved this and could you also share your method in debugging the error?

**Comment by jhampton** [comment]
Thanks very much for reporting this! We think this is a great idea, and would definitely review a PR. In this particular case, some ahead-of-time validation of operations might aide in catching errors as well. If you (or anyone else) is interested in working on this, that would be great - thanks!

**Comment by joeflack4** [comment]
@jhampton No problem! Much appreciation. Honestly, cryptic errors have unfortunately been my bane in Apollo. It caused me to move back to Redux for now. Love the project though and hoping to use it again in the future.
