### ISSUE TITLE
Hapi 17.5.3 bug or apollo-server-hapi bug?

### ISSUE THREAD

**Issue by nicolas-goudry** [apollographql/apollo-server#1501]
Hi,

I’m using Apollo server with Hapi 17.5.2, so I am using apollo-server-hapi 2.0.0.

Everything was working fine, but I recently updated to Hapi 17.5.3 and GraphQL Playground isn’t working anymore. When I try to hit `http://locahost:3000/graphql`, request timeouts in browser and the following errors are logged:

```
(node:24804) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'isOriginMatch' of null
    at exports.headers (/home/nicolas/dev/yellow/mistertracer/mistertracer-server/node_modules/hapi/lib/cors.js:171:28)
    at Object.internals.marshal (/home/nicolas/dev/yellow/mistertracer/mistertracer-server/node_modules/hapi/lib/transmit.js:46:24)
    at Object.exports.send (/home/nicolas/dev/yellow/mistertracer/mistertracer-server/node_modules/hapi/lib/transmit.js:31:25)
    at Request._reply (/home/nicolas/dev/yellow/mistertracer/mistertracer-server/node_modules/hapi/lib/request.js:349:24)
    at <anonymous>
(node:24804) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:24804) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

I’ve open a [discussion on hapijs/discuss repo](https://github.com/hapijs/discuss/issues/704), as of my understanding, the error seems to come from hapi cors module.

I created a repo to reproduce the error: https://github.com/nicolas-goudry/hapi-17.5.3-apollo-hapi-server-bug

Any idea about which one is faulty? Apollo ? Hapi ?

Thanks in advance.

**Comment by bichikim** [comment]
Hapi ~17.4.0 is working well with apollo-server-hapi
However 17.5* is throw the error

**Comment by bichikim** [comment]
it's fixed by hapi 17.5.4 path
