### ISSUE TITLE
Apollo 2 serverless tutorial dont work

### ISSUE THREAD

**Issue by webchi** [apollographql/apollo-server#1535]
Tried [this](https://www.apollographql.com/docs/apollo-server/v2/deployment/lambda.html#Running-the-Serverless-Framework) tutorial  but after deploing to aws lamabda get an error:
```
Unable to import module 'handler': Error
at Function.Module._resolveFilename (module.js:547:15)
at Function.Module._load (module.js:474:25)
at Module.require (module.js:596:17)
at require (internal/module.js:11:18)
at Object.<anonymous> (/var/task/node_modules/apollo-upload-server/lib/middleware.js:14:1)
at Module._compile (module.js:652:30)
at Object.Module._extensions..js (module.js:663:10)
at Module.load (module.js:565:32)
at tryModuleLoad (module.js:505:12)
at Function.Module._load (module.js:497:3)
```
[Source code](https://github.com/webchi/apollo2-lambda-test)
@MeixnerTobias in slack found workaround solution to add "core-js": "^2.5.7" to package.json. That helped but maybe need fix tutorial or find better fix.

**Comment by sbrichardson** [comment]
related #1536 possibly

**Comment by yofriadi** [comment]
#1542

**Comment by abernix** [comment]
Closing as this is quite old, but happy to re-open if it continues to be a problem.  (Though I suspect the underlying issue has ben resolved.)

Thanks for opening this originally!
