### ISSUE TITLE
Error: Couldn't find package "@apollographql/graphql-playground-html@^1.6.0"

### ISSUE THREAD

**Issue by apollomusa** [apollographql/apollo-server#1544]
When I try to add the `apollo-server` pkg it returns with the error: 

```
yarn add apollo-server
`Error: Couldn't find package "@apollographql/graphql-playground-html@^1.6.0" required by "apollo-server-express@2.0.2" on the "npm" registry.
```

Here's a `verbose` log of the install: 

```
mbarighzaai@M ~/proj/bff/interactions-bff $ yarn add apollo-server --verbose
yarn add v1.7.0
verbose 0.337 Checking for configuration file "/Users/mbarighzaai/proj/bff/interactions-bff/.npmrc".
verbose 0.337 Checking for configuration file "/Users/mbarighzaai/.npmrc".
verbose 0.337 Found configuration file "/Users/mbarighzaai/.npmrc".
verbose 0.338 Checking for configuration file "/Users/mbarighzaai/.nvm/versions/node/v9.2.1/etc/npmrc".
verbose 0.338 Checking for configuration file "/Users/mbarighzaai/proj/bff/interactions-bff/.npmrc".
verbose 0.338 Checking for configuration file "/Users/mbarighzaai/proj/bff/.npmrc".
verbose 0.338 Checking for configuration file "/Users/mbarighzaai/proj/.npmrc".
verbose 0.338 Checking for configuration file "/Users/mbarighzaai/.npmrc".
verbose 0.338 Found configuration file "/Users/mbarighzaai/.npmrc".
verbose 0.339 Checking for configuration file "/Users/.npmrc".
verbose 0.34 Checking for configuration file "/Users/mbarighzaai/proj/bff/interactions-bff/.yarnrc".
verbose 0.377 Checking for configuration file "/Users/mbarighzaai/.yarnrc".
verbose 0.377 Found configuration file "/Users/mbarighzaai/.yarnrc".
verbose 0.378 Checking for configuration file "/Users/mbarighzaai/.nvm/versions/node/v9.2.1/etc/yarnrc".
verbose 0.378 Checking for configuration file "/Users/mbarighzaai/proj/bff/interactions-bff/.yarnrc".
verbose 0.378 Checking for configuration file "/Users/mbarighzaai/proj/bff/.yarnrc".
verbose 0.378 Checking for configuration file "/Users/mbarighzaai/proj/.yarnrc".
verbose 0.378 Checking for configuration file "/Users/mbarighzaai/.yarnrc".
verbose 0.378 Found configuration file "/Users/mbarighzaai/.yarnrc".
verbose 0.378 Checking for configuration file "/Users/.yarnrc".
verbose 0.381 current time: 2018-08-16T14:15:08.788Z
[1/4] 🔍  Resolving packages...
verbose 0.661 Performing "GET" request to "https://registry.yarnpkg.com/apollo-server".
verbose 0.737 Request "https://registry.yarnpkg.com/apollo-server" finished with status code 200.
verbose 0.739 Performing "GET" request to "https://registry.yarnpkg.com/apollo-server-core".
verbose 0.742 Performing "GET" request to "https://registry.yarnpkg.com/apollo-server-express".
verbose 0.742 Performing "GET" request to "https://registry.yarnpkg.com/express".
verbose 0.743 Performing "GET" request to "https://registry.yarnpkg.com/graphql-subscriptions".
verbose 0.743 Performing "GET" request to "https://registry.yarnpkg.com/graphql-tools".
verbose 0.763 Request "https://registry.yarnpkg.com/apollo-server-core" finished with status code 200.
verbose 0.767 Performing "GET" request to "https://registry.yarnpkg.com/@types%2fws".
verbose 0.768 Performing "GET" request to "https://registry.yarnpkg.com/apollo-cache-control".
verbose 0.769 Performing "GET" request to "https://registry.yarnpkg.com/apollo-datasource".
verbose 0.769 Performing "GET" request to "https://registry.yarnpkg.com/apollo-engine-reporting".
verbose 0.78 Request "https://registry.yarnpkg.com/graphql-subscriptions" finished with status code 200.
verbose 0.781 Performing "GET" request to "https://registry.yarnpkg.com/apollo-server-caching".
verbose 0.784 Request "https://registry.yarnpkg.com/apollo-server-express" finished with status code 200.
verbose 0.784 Performing "GET" request to "https://registry.yarnpkg.com/apollo-server-env".
verbose 0.816 Request "https://registry.yarnpkg.com/@types%2fws" finished with status code 200.
verbose 0.817 Performing "GET" request to "https://registry.yarnpkg.com/apollo-server-errors".
verbose 0.824 Request "https://registry.yarnpkg.com/express" finished with status code 200.
verbose 0.825 Performing "GET" request to "https://registry.yarnpkg.com/apollo-tracing".
verbose 0.839 Request "https://registry.yarnpkg.com/graphql-tools" finished with status code 200.
verbose 0.839 Performing "GET" request to "https://registry.yarnpkg.com/apollo-upload-server".
verbose 0.841 Request "https://registry.yarnpkg.com/apollo-server-caching" finished with status code 200.
verbose 0.842 Performing "GET" request to "https://registry.yarnpkg.com/graphql-extensions".
verbose 0.844 Request "https://registry.yarnpkg.com/apollo-engine-reporting" finished with status code 200.
verbose 0.845 Performing "GET" request to "https://registry.yarnpkg.com/graphql-tag".
verbose 0.846 Request "https://registry.yarnpkg.com/apollo-datasource" finished with status code 200.
verbose 0.847 Performing "GET" request to "https://registry.yarnpkg.com/hash.js".
verbose 0.848 Request "https://registry.yarnpkg.com/apollo-cache-control" finished with status code 200.
verbose 0.876 Performing "GET" request to "https://registry.yarnpkg.com/lodash".
verbose 0.878 Request "https://registry.yarnpkg.com/apollo-server-env" finished with status code 200.
verbose 0.878 Performing "GET" request to "https://registry.yarnpkg.com/subscriptions-transport-ws".
verbose 0.882 Request "https://registry.yarnpkg.com/apollo-server-errors" finished with status code 200.
verbose 0.882 Performing "GET" request to "https://registry.yarnpkg.com/ws".
verbose 0.883 Request "https://registry.yarnpkg.com/apollo-tracing" finished with status code 200.
verbose 0.883 Performing "GET" request to "https://registry.yarnpkg.com/@apollographql%2fgraphql-playground-html".
verbose 0.885 Request "https://registry.yarnpkg.com/apollo-upload-server" finished with status code 200.
verbose 0.885 Performing "GET" request to "https://registry.yarnpkg.com/@types%2faccepts".
verbose 0.888 Request "https://registry.yarnpkg.com/graphql-extensions" finished with status code 200.
verbose 0.924 Performing "GET" request to "https://registry.yarnpkg.com/@types%2fbody-parser".
verbose 0.928 Request "https://registry.yarnpkg.com/lodash" finished with status code 200.
verbose 0.928 Performing "GET" request to "https://registry.yarnpkg.com/@types%2fcors".
verbose 0.93 Request "https://registry.yarnpkg.com/subscriptions-transport-ws" finished with status code 200.
verbose 0.93 Performing "GET" request to "https://registry.yarnpkg.com/@types%2fexpress".
verbose 0.932 Request "https://registry.yarnpkg.com/hash.js" finished with status code 200.
verbose 0.932 Performing "GET" request to "https://registry.yarnpkg.com/accepts".
verbose 0.934 Request "https://registry.yarnpkg.com/graphql-tag" finished with status code 200.
verbose 0.934 Performing "GET" request to "https://registry.yarnpkg.com/body-parser".
verbose 0.935 Request "https://registry.yarnpkg.com/@types%2fbody-parser" finished with status code 200.
verbose 0.935 Performing "GET" request to "https://registry.yarnpkg.com/cors".
verbose 0.975 Request "https://registry.yarnpkg.com/ws" finished with status code 200.
verbose 0.976 Performing "GET" request to "https://registry.yarnpkg.com/type-is".
verbose 0.984 Request "https://registry.yarnpkg.com/@types%2faccepts" finished with status code 200.
verbose 0.985 Performing "GET" request to "https://registry.yarnpkg.com/@types%2fevents".
verbose 0.986 Request "https://registry.yarnpkg.com/body-parser" finished with status code 200.
verbose 0.986 Performing "GET" request to "https://registry.yarnpkg.com/@types%2fnode".
verbose 0.993 Request "https://registry.yarnpkg.com/@types%2fcors" finished with status code 200.
verbose 0.993 Performing "GET" request to "https://registry.yarnpkg.com/array-flatten".
verbose 0.994 Request "https://registry.yarnpkg.com/@types%2fexpress" finished with status code 200.
verbose 0.995 Performing "GET" request to "https://registry.yarnpkg.com/content-disposition".
verbose 0.998 Request "https://registry.yarnpkg.com/accepts" finished with status code 200.
verbose 0.998 Performing "GET" request to "https://registry.yarnpkg.com/content-type".
verbose 1.024 Request "https://registry.yarnpkg.com/cors" finished with status code 200.
verbose 1.025 Performing "GET" request to "https://registry.yarnpkg.com/cookie".
verbose 1.033 Request "https://registry.yarnpkg.com/array-flatten" finished with status code 200.
verbose 1.034 Performing "GET" request to "https://registry.yarnpkg.com/cookie-signature".
verbose 1.035 Request "https://registry.yarnpkg.com/content-disposition" finished with status code 200.
verbose 1.035 Performing "GET" request to "https://registry.yarnpkg.com/debug".
verbose 1.035 Request "https://registry.yarnpkg.com/type-is" finished with status code 200.
verbose 1.036 Performing "GET" request to "https://registry.yarnpkg.com/depd".
verbose 1.037 Request "https://registry.yarnpkg.com/cookie" finished with status code 200.
verbose 1.037 Performing "GET" request to "https://registry.yarnpkg.com/encodeurl".
verbose 1.038 Request "https://registry.yarnpkg.com/content-type" finished with status code 200.
verbose 1.038 Performing "GET" request to "https://registry.yarnpkg.com/escape-html".
verbose 1.075 Request "https://registry.yarnpkg.com/@types%2fnode" finished with status code 200.
verbose 1.076 Performing "GET" request to "https://registry.yarnpkg.com/etag".
verbose 1.076 Request "https://registry.yarnpkg.com/@types%2fevents" finished with status code 200.
verbose 1.077 Performing "GET" request to "https://registry.yarnpkg.com/finalhandler".
verbose 1.077 Request "https://registry.yarnpkg.com/cookie-signature" finished with status code 200.
verbose 1.077 Performing "GET" request to "https://registry.yarnpkg.com/fresh".
verbose 1.08 Request "https://registry.yarnpkg.com/depd" finished with status code 200.
verbose 1.08 Performing "GET" request to "https://registry.yarnpkg.com/merge-descriptors".
verbose 1.082 Request "https://registry.yarnpkg.com/escape-html" finished with status code 200.
verbose 1.082 Performing "GET" request to "https://registry.yarnpkg.com/methods".
verbose 1.084 Request "https://registry.yarnpkg.com/debug" finished with status code 200.
verbose 1.084 Performing "GET" request to "https://registry.yarnpkg.com/on-finished".
verbose 1.087 Request "https://registry.yarnpkg.com/etag" finished with status code 200.
verbose 1.087 Performing "GET" request to "https://registry.yarnpkg.com/parseurl".
verbose 1.088 Request "https://registry.yarnpkg.com/encodeurl" finished with status code 200.
verbose 1.088 Performing "GET" request to "https://registry.yarnpkg.com/path-to-regexp".
verbose 1.124 Request "https://registry.yarnpkg.com/finalhandler" finished with status code 200.
verbose 1.124 Performing "GET" request to "https://registry.yarnpkg.com/proxy-addr".
verbose 1.13 Request "https://registry.yarnpkg.com/fresh" finished with status code 200.
verbose 1.13 Performing "GET" request to "https://registry.yarnpkg.com/qs".
verbose 1.131 Request "https://registry.yarnpkg.com/merge-descriptors" finished with status code 200.
verbose 1.131 Performing "GET" request to "https://registry.yarnpkg.com/range-parser".
verbose 1.132 Request "https://registry.yarnpkg.com/methods" finished with status code 200.
verbose 1.132 Performing "GET" request to "https://registry.yarnpkg.com/safe-buffer".
verbose 1.133 Request "https://registry.yarnpkg.com/on-finished" finished with status code 200.
verbose 1.133 Performing "GET" request to "https://registry.yarnpkg.com/send".
verbose 1.142 Request "https://registry.yarnpkg.com/path-to-regexp" finished with status code 200.
verbose 1.142 Performing "GET" request to "https://registry.yarnpkg.com/serve-static".
verbose 1.179 Request "https://registry.yarnpkg.com/parseurl" finished with status code 200.
verbose 1.179 Performing "GET" request to "https://registry.yarnpkg.com/setprototypeof".
verbose 1.182 Request "https://registry.yarnpkg.com/qs" finished with status code 200.
verbose 1.182 Performing "GET" request to "https://registry.yarnpkg.com/statuses".
verbose 1.187 Request "https://registry.yarnpkg.com/range-parser" finished with status code 200.
verbose 1.187 Performing "GET" request to "https://registry.yarnpkg.com/utils-merge".
verbose 1.188 Request "https://registry.yarnpkg.com/proxy-addr" finished with status code 200.
verbose 1.188 Performing "GET" request to "https://registry.yarnpkg.com/vary".
verbose 1.189 Request "https://registry.yarnpkg.com/safe-buffer" finished with status code 200.
verbose 1.189 Performing "GET" request to "https://registry.yarnpkg.com/apollo-link".
verbose 1.192 Request "https://registry.yarnpkg.com/send" finished with status code 200.
verbose 1.192 Performing "GET" request to "https://registry.yarnpkg.com/apollo-utilities".
verbose 1.235 Request "https://registry.yarnpkg.com/serve-static" finished with status code 200.
verbose 1.235 Performing "GET" request to "https://registry.yarnpkg.com/deprecated-decorator".
verbose 1.237 Request "https://registry.yarnpkg.com/utils-merge" finished with status code 200.
verbose 1.237 Performing "GET" request to "https://registry.yarnpkg.com/iterall".
verbose 1.238 Request "https://registry.yarnpkg.com/apollo-link" finished with status code 200.
verbose 1.238 Performing "GET" request to "https://registry.yarnpkg.com/uuid".
verbose 1.24 Request "https://registry.yarnpkg.com/setprototypeof" finished with status code 200.
verbose 1.24 Performing "GET" request to "https://registry.yarnpkg.com/lru-cache".
verbose 1.241 Request "https://registry.yarnpkg.com/vary" finished with status code 200.
verbose 1.241 Performing "GET" request to "https://registry.yarnpkg.com/apollo-engine-reporting-protobuf".
verbose 1.275 Request "https://registry.yarnpkg.com/statuses" finished with status code 200.
verbose 1.275 Performing "GET" request to "https://registry.yarnpkg.com/async-retry".
verbose 1.281 Request "https://registry.yarnpkg.com/apollo-utilities" finished with status code 200.
verbose 1.281 Performing "GET" request to "https://registry.yarnpkg.com/node-fetch".
verbose 1.288 Request "https://registry.yarnpkg.com/iterall" finished with status code 200.
verbose 1.288 Performing "GET" request to "https://registry.yarnpkg.com/util.promisify".
verbose 1.292 Request "https://registry.yarnpkg.com/lru-cache" finished with status code 200.
verbose 1.292 Performing "GET" request to "https://registry.yarnpkg.com/@babel%2fruntime".
verbose 1.293 Request "https://registry.yarnpkg.com/deprecated-decorator" finished with status code 200.
verbose 1.293 Performing "GET" request to "https://registry.yarnpkg.com/busboy".
verbose 1.294 Request "https://registry.yarnpkg.com/async-retry" finished with status code 200.
verbose 1.325 Performing "GET" request to "https://registry.yarnpkg.com/object-path".
verbose 1.327 Request "https://registry.yarnpkg.com/util.promisify" finished with status code 200.
verbose 1.327 Performing "GET" request to "https://registry.yarnpkg.com/backo2".
verbose 1.329 Request "https://registry.yarnpkg.com/apollo-engine-reporting-protobuf" finished with status code 200.
verbose 1.329 Performing "GET" request to "https://registry.yarnpkg.com/eventemitter3".
verbose 1.331 Request "https://registry.yarnpkg.com/uuid" finished with status code 200.
verbose 1.331 Performing "GET" request to "https://registry.yarnpkg.com/symbol-observable".
verbose 1.333 Request "https://registry.yarnpkg.com/node-fetch" finished with status code 200.
verbose 1.333 Performing "GET" request to "https://registry.yarnpkg.com/minimalistic-assert".
verbose 1.337 Request "https://registry.yarnpkg.com/object-path" finished with status code 200.
verbose 1.337 Performing "GET" request to "https://registry.yarnpkg.com/@types%2fconnect".
verbose 1.338 Request "https://registry.yarnpkg.com/@babel%2fruntime" finished with status code 200.
verbose 1.373 Performing "GET" request to "https://registry.yarnpkg.com/async-limiter".
verbose 1.376 Request "https://registry.yarnpkg.com/busboy" finished with status code 200.
verbose 1.376 Performing "GET" request to "https://registry.yarnpkg.com/bytes".
verbose 1.378 Request "https://registry.yarnpkg.com/backo2" finished with status code 200.
verbose 1.378 Performing "GET" request to "https://registry.yarnpkg.com/http-errors".
verbose 1.38 Request "https://registry.yarnpkg.com/eventemitter3" finished with status code 200.
verbose 1.381 Performing "GET" request to "https://registry.yarnpkg.com/iconv-lite".
verbose 1.384 Request "https://registry.yarnpkg.com/symbol-observable" finished with status code 200.
verbose 1.384 Performing "GET" request to "https://registry.yarnpkg.com/raw-body".
verbose 1.384 Request "https://registry.yarnpkg.com/minimalistic-assert" finished with status code 200.
verbose 1.384 Performing "GET" request to "https://registry.yarnpkg.com/@types%2fserve-static".
verbose 1.386 Request "https://registry.yarnpkg.com/async-limiter" finished with status code 200.
verbose 1.386 Performing "GET" request to "https://registry.yarnpkg.com/@types%2fexpress-serve-static-core".
verbose 1.424 Request "https://registry.yarnpkg.com/http-errors" finished with status code 200.
verbose 1.425 Performing "GET" request to "https://registry.yarnpkg.com/mime-types".
verbose 1.429 Request "https://registry.yarnpkg.com/bytes" finished with status code 200.
verbose 1.429 Performing "GET" request to "https://registry.yarnpkg.com/negotiator".
verbose 1.43 Request "https://registry.yarnpkg.com/@types%2fconnect" finished with status code 200.
verbose 1.43 Performing "GET" request to "https://registry.yarnpkg.com/object-assign".
verbose 1.431 Request "https://registry.yarnpkg.com/iconv-lite" finished with status code 200.
verbose 1.432 Performing "GET" request to "https://registry.yarnpkg.com/media-typer".
verbose 1.434 Request "https://registry.yarnpkg.com/raw-body" finished with status code 200.
verbose 1.435 Performing "GET" request to "https://registry.yarnpkg.com/unpipe".
verbose 1.442 Request "https://registry.yarnpkg.com/@types%2fserve-static" finished with status code 200.
verbose 1.474 Performing "GET" request to "https://registry.yarnpkg.com/ee-first".
verbose 1.477 Request "https://registry.yarnpkg.com/@types%2fexpress-serve-static-core" finished with status code 200.
verbose 1.477 Performing "GET" request to "https://registry.yarnpkg.com/forwarded".
verbose 1.479 Request "https://registry.yarnpkg.com/mime-types" finished with status code 200.
verbose 1.479 Performing "GET" request to "https://registry.yarnpkg.com/ipaddr.js".
verbose 1.48 Request "https://registry.yarnpkg.com/unpipe" finished with status code 200.
verbose 1.48 Performing "GET" request to "https://registry.yarnpkg.com/destroy".
verbose 1.481 Request "https://registry.yarnpkg.com/object-assign" finished with status code 200.
verbose 1.481 Performing "GET" request to "https://registry.yarnpkg.com/mime".
verbose 1.482 Request "https://registry.yarnpkg.com/negotiator" finished with status code 200.
verbose 1.482 Performing "GET" request to "https://registry.yarnpkg.com/@types%2fgraphql".
verbose 1.491 Request "https://registry.yarnpkg.com/ee-first" finished with status code 200.
verbose 1.491 Performing "GET" request to "https://registry.yarnpkg.com/zen-observable-ts".
verbose 1.525 Request "https://registry.yarnpkg.com/forwarded" finished with status code 200.
verbose 1.526 Performing "GET" request to "https://registry.yarnpkg.com/fast-json-stable-stringify".
verbose 1.526 Request "https://registry.yarnpkg.com/ipaddr.js" finished with status code 200.
verbose 1.527 Performing "GET" request to "https://registry.yarnpkg.com/retry".
verbose 1.528 Request "https://registry.yarnpkg.com/mime" finished with status code 200.
verbose 1.529 Performing "GET" request to "https://registry.yarnpkg.com/object.getownpropertydescriptors".
verbose 1.53 Request "https://registry.yarnpkg.com/@types%2fgraphql" finished with status code 200.
verbose 1.53 Performing "GET" request to "https://registry.yarnpkg.com/protobufjs".
verbose 1.532 Request "https://registry.yarnpkg.com/destroy" finished with status code 200.
verbose 1.532 Performing "GET" request to "https://registry.yarnpkg.com/regenerator-runtime".
verbose 1.536 Request "https://registry.yarnpkg.com/media-typer" finished with status code 200.
verbose 1.536 Performing "GET" request to "https://registry.yarnpkg.com/dicer".
verbose 1.541 Request "https://registry.yarnpkg.com/retry" finished with status code 200.
verbose 1.541 Performing "GET" request to "https://registry.yarnpkg.com/readable-stream".
verbose 1.575 Request "https://registry.yarnpkg.com/fast-json-stable-stringify" finished with status code 200.
verbose 1.575 Performing "GET" request to "https://registry.yarnpkg.com/inherits".
verbose 1.576 Request "https://registry.yarnpkg.com/regenerator-runtime" finished with status code 200.
verbose 1.577 Performing "GET" request to "https://registry.yarnpkg.com/safer-buffer".
verbose 1.578 Request "https://registry.yarnpkg.com/object.getownpropertydescriptors" finished with status code 200.
verbose 1.578 Performing "GET" request to "https://registry.yarnpkg.com/@types%2fmime".
verbose 1.582 Request "https://registry.yarnpkg.com/protobufjs" finished with status code 200.
verbose 1.582 Performing "GET" request to "https://registry.yarnpkg.com/@types%2frange-parser".
verbose 1.588 Request "https://registry.yarnpkg.com/dicer" finished with status code 200.
verbose 1.588 Performing "GET" request to "https://registry.yarnpkg.com/mime-db".
verbose 1.59 Request "https://registry.yarnpkg.com/zen-observable-ts" finished with status code 200.
verbose 1.59 Performing "GET" request to "https://registry.yarnpkg.com/es-abstract".
verbose 1.592 Request "https://registry.yarnpkg.com/readable-stream" finished with status code 200.
verbose 1.593 Performing "GET" request to "https://registry.yarnpkg.com/@protobufjs%2faspromise".
verbose 1.598 Request "https://registry.yarnpkg.com/inherits" finished with status code 200.
verbose 1.625 Performing "GET" request to "https://registry.yarnpkg.com/@protobufjs%2fbase64".
verbose 1.627 Request "https://registry.yarnpkg.com/safer-buffer" finished with status code 200.
verbose 1.627 Performing "GET" request to "https://registry.yarnpkg.com/@protobufjs%2fcodegen".
verbose 1.629 Request "https://registry.yarnpkg.com/mime-db" finished with status code 200.
verbose 1.629 Performing "GET" request to "https://registry.yarnpkg.com/@protobufjs%2feventemitter".
verbose 1.63 Request "https://registry.yarnpkg.com/es-abstract" finished with status code 200.
verbose 1.631 Performing "GET" request to "https://registry.yarnpkg.com/@protobufjs%2ffetch".
verbose 1.632 Request "https://registry.yarnpkg.com/@types%2frange-parser" finished with status code 200.
verbose 1.633 Performing "GET" request to "https://registry.yarnpkg.com/@protobufjs%2ffloat".
verbose 1.633 Request "https://registry.yarnpkg.com/@types%2fmime" finished with status code 200.
verbose 1.634 Performing "GET" request to "https://registry.yarnpkg.com/@protobufjs%2finquire".
verbose 1.668 Request "https://registry.yarnpkg.com/@apollographql%2fgraphql-playground-html" finished with status code 404.
verbose 1.676 Performing "GET" request to "https://registry.yarnpkg.com/@protobufjs%2fpath".
verbose 1.7 Request "https://registry.yarnpkg.com/@protobufjs%2fbase64" finished with status code 200.
verbose 1.7 Performing "GET" request to "https://registry.yarnpkg.com/@protobufjs%2fpool".
verbose 1.701 Request "https://registry.yarnpkg.com/@protobufjs%2faspromise" finished with status code 200.
verbose 1.702 Performing "GET" request to "https://registry.yarnpkg.com/@protobufjs%2futf8".
verbose 1.711 Request "https://registry.yarnpkg.com/@protobufjs%2ffloat" finished with status code 200.
verbose 1.712 Performing "GET" request to "https://registry.yarnpkg.com/@types%2flong".
verbose 1.713 Request "https://registry.yarnpkg.com/@protobufjs%2fcodegen" finished with status code 200.
verbose 1.713 Performing "GET" request to "https://registry.yarnpkg.com/long".
verbose 1.726 Request "https://registry.yarnpkg.com/long" finished with status code 200.
verbose 1.726 Performing "GET" request to "https://registry.yarnpkg.com/streamsearch".
verbose 1.727 Request "https://registry.yarnpkg.com/@types%2flong" finished with status code 200.
verbose 1.727 Performing "GET" request to "https://registry.yarnpkg.com/zen-observable".
verbose 1.731 Request "https://registry.yarnpkg.com/@protobufjs%2ffetch" finished with status code 200.
verbose 1.736 Request "https://registry.yarnpkg.com/streamsearch" finished with status code 200.
verbose 1.737 Request "https://registry.yarnpkg.com/@protobufjs%2finquire" finished with status code 200.
verbose 1.76 Request "https://registry.yarnpkg.com/@protobufjs%2fpath" finished with status code 200.
verbose 1.775 Request "https://registry.yarnpkg.com/@protobufjs%2feventemitter" finished with status code 200.
verbose 1.778 Request "https://registry.yarnpkg.com/@protobufjs%2fpool" finished with status code 200.
verbose 1.779 Request "https://registry.yarnpkg.com/@protobufjs%2futf8" finished with status code 200.
verbose 1.78 Error: Couldn't find package "@apollographql/graphql-playground-html@^1.6.0" required by "apollo-server-express@2.0.2" on the "npm" registry.
    at MessageError.ExtendableBuiltin (/Users/mbarighzaai/.nvm/versions/node/v9.2.1/lib/node_modules/yarn/lib/cli.js:243:66)
    at new MessageError (/Users/mbarighzaai/.nvm/versions/node/v9.2.1/lib/node_modules/yarn/lib/cli.js:272:123)
    at PackageRequest.<anonymous> (/Users/mbarighzaai/.nvm/versions/node/v9.2.1/lib/node_modules/yarn/lib/cli.js:36403:17)
    at Generator.throw (<anonymous>)
    at step (/Users/mbarighzaai/.nvm/versions/node/v9.2.1/lib/node_modules/yarn/lib/cli.js:98:30)
    at /Users/mbarighzaai/.nvm/versions/node/v9.2.1/lib/node_modules/yarn/lib/cli.js:111:13
    at <anonymous>
    at process._tickCallback (internal/process/next_tick.js:188:7)
error Couldn't find package "@apollographql/graphql-playground-html@^1.6.0" required by "apollo-server-express@2.0.2" on the "npm" registry.
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
verbose 1.857 Request "https://registry.yarnpkg.com/zen-observable" finished with status code 200.
```

I've tried clearing cache and all, same error. I have no .npmrc/.yarnrc file in the directory either

**Comment by apollomusa** [comment]
Sorry, `.npmrc` was blocking. Closing Issue.
