### ISSUE TITLE
Get INTERNAL_SERVER_ERROR when throwing AuthenticationError

### ISSUE THREAD

**Issue by liemdo** [apollographql/apollo-server#1583]
Hi guys, I'm using `apollo-server-express@2.0.4` and throwing an AuthenticationError but I always get INTERNAL_SERVER_ERROR instead of UNAUTHENTICATED as mentioned in the docs. I throw the error in a mutation. I've tried ForbiddenError and I also get the same error.

```javascript
import { AuthenticationError } from 'apollo-server-express';
...
throw new AuthenticationError('Invalid username or password');
```

```json
{
  "data": {
    "login": null
  },
  "errors": [
    {
      "message": "Invalid username or password",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "login"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "AuthenticationError: Incorrect username or password.",
            "    at User.login (/Users/ldo/apollo/login/index.js:87:26)",
            "    at login (/Users/ldo/apollo/graphqlSchema/mutation.js:6:43)",
            "    at field.resolve (/Users/ldo/apollo/node_modules/graphql-extensions/dist/index.js:92:48)",
            "    at resolveFieldValueOrError (/Users/ldo/apollo/node_modules/graphql/execution/execute.js:498:12)",
            "    at resolveField (/Users/ldo/apollo/node_modules/graphql/execution/execute.js:462:16)",
            "    at /Users/liemdo/ringblaze/api/node_modules/graphql/execution/execute.js:284:20",
            "    at <anonymous>",
            "    at process._tickCallback (internal/process/next_tick.js:182:7)"
          ]
        }
      }
    }
  ]
}
```

**Comment by liemdo** [comment]
It worked after I upgraded `graphql` to the latest version.

**Comment by kfrajtak** [comment]
Does not work for me even after upgrading `graphql` to 14.4.0 and Apollo packages (server, server-core and server-express) to 2.6.7.

**Comment by carlitux** [comment]
I had this same error and figured out that I wrapped an ApolloError **subclass** with another ApolloError.
