### ISSUE TITLE
TypeError: [domain] is not a legal HTTP header value when using apollo-server-lambda with react-apollo 

### ISSUE THREAD

**Issue by jchungkr** [apollographql/apollo-server#1702]
node version 8.10.0
apollo-server-lambda version ^2.0.0-xrc.11
react-apollo: ^2.1.11

* using serverless to deploy Apollo GraphQL backend to lambda functions - graphql server works fine with Chrome, Safari and Firefox browsers

* Query Component in Both IE and Edge browsers returns error - the error in CloudWatch lambda function logs is:
```
[date] ...TypeError: https://[KOREAN DOMAIN NAME].com is not a legal HTTP header value
at validateValue (/var/task/node_modules/node-fetch/lib/index.js:677:9)
at Headers.append (/var/task/node_modules/node-fetch/lib/index.js:829:3)
at new Headers (/var/task/node_modules/node-fetch/lib/index.js:754:11)
at graphqlHandler (/var/task/node_modules/apollo-server-lambda/dist/lambdaApollo.js:29:26)
at /var/task/node_modules/apollo-server-lambda/dist/ApolloServer.js:87:85
```

where [KOREAN DOMAIN NAME] is an [Internationalized domain name](https://en.wikipedia.org/wiki/Internationalized_domain_name) in Korean.

Is there a way to avoid this error in IE and Edge?

**Comment by jchungkr** [comment]
apparently this is a bug with IE/Edge [but unfixed?](https://developer.microsoft.com/en-us/microsoft-edge/platform/issues/8075637/)
