### ISSUE TITLE
Contributing

### ISSUE THREAD

**Issue by anarasimhan** [apollographql/apollo-server#1712]
Is there some documentation on how to contribute.
  - Build apollo-server for local development
  - Coding standards/styles
 
I forked apollo-server, cloned the repository and ran npm install. I get these errors. 
```
events.js:183░░░░░░⸩ ⠏ extract:graphql-tools: sill extract @lerna/collect-updates@3.3.2
      throw er; // Unhandled 'error' event
      ^

Error: write after end
    at writeAfterEnd (_stream_writable.js:236:12)
    at PassThrough.Writable.write (_stream_writable.js:287:5)
    at PassThrough.Writable.end (_stream_writable.js:563:10)
    at ReadEntry.entry.on (/Users/anarasimhan/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/pacote/lib/extract-stream.js:19:41)
    at emitOne (events.js:121:20)
    at ReadEntry.emit (events.js:211:7)
    at ReadEntry.emit (/Users/anarasimhan/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:287:25)
    at ReadEntry.[maybeEmitEnd] (/Users/anarasimhan/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:240:12)
    at ReadEntry.end (/Users/anarasimhan/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/tar/node_modules/minipass/index.js:153:27)
    at Unpack.[consumeBody] (/Users/anarasimhan/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:210:13)
    at Unpack.[consumeChunkSub] (/Users/anarasimhan/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:391:40)
    at Unpack.[consumeChunk] (/Users/anarasimhan/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:360:30)
    at Unzip.(anonymous function).on.chunk (/Users/anarasimhan/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/tar/lib/parse.js:291:59)
    at emitOne (events.js:116:13)
    at Unzip.emit (events.js:211:7)
    at Unzip.emit (/Users/anarasimhan/.nvm/versions/node/v8.10.0/lib/node_modules/npm/node_modules/tar/node_modules/m
```

**Comment by sbrichardson** [comment]
Not sure if this will help but try:

1. remove node_modules
2. run `npm install`
3. run `npm run lerna bootstrap`

There is a postinstall hook, but sometimes I've seen running bootstrap separately helps. I would also try with a different/newer node version with nvm, just to see if it helps.

**Comment by JacksonKearl** [comment]
Hello! We have some docs for contributing on the [README](https://github.com/apollographql/apollo-server#development). Beyond that, we use [prettier](https://prettier.io/) for formatting, and we have some PR hooks to make sure the linting passes.
