### ISSUE TITLE
2.x - Fragment aliases seem to be incorrectly handled

### ISSUE THREAD

**Issue by kamranayub** [apollographql/apollo-server#1724]
I opened an issue on graphql-js: https://github.com/graphql/graphql-js/issues/1530#event-1862105684

But it appears that my issue may not be related to the parser itself. This is a bug that was introduced when I upgraded to Apollo Server 2.x. I even rolled back every package _except_ `apollo-server` to what I had before and the issue persists.

Playground: https://pinto-hip.glitch.me

Issue the query:

```
{
  books {
    name
    categoryHierarchy {
      ...category
      categories {
        ...category
      }
    }
  }
}

fragment category on Category {
  abc: name
}
```

Error:

```
{
  "data": {
    "books": null
  },
  "errors": [
    {
      "message": "Cannot return null for non-nullable field Books.name.",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "books",
        "name"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "Error: Cannot return null for non-nullable field Books.name.",
            "    at completeValue (/rbd/pnpm-volume/0897a123-e913-41b8-a689-0921f96aa33a/node_modules/.registry.npmjs.org/graphql/0.13.2/node_modules/graphql/execution/execute.js:631:13)",
            "    at completeValueWithLocatedError (/rbd/pnpm-volume/0897a123-e913-41b8-a689-0921f96aa33a/node_modules/.registry.npmjs.org/graphql/0.13.2/node_modules/graphql/execution/execute.js:580:21)",
            "    at completeValueCatchingError (/rbd/pnpm-volume/0897a123-e913-41b8-a689-0921f96aa33a/node_modules/.registry.npmjs.org/graphql/0.13.2/node_modules/graphql/execution/execute.js:550:12)",
            "    at resolveField (/rbd/pnpm-volume/0897a123-e913-41b8-a689-0921f96aa33a/node_modules/.registry.npmjs.org/graphql/0.13.2/node_modules/graphql/execution/execute.js:497:10)",
            "    at /rbd/pnpm-volume/0897a123-e913-41b8-a689-0921f96aa33a/node_modules/.registry.npmjs.org/graphql/0.13.2/node_modules/graphql/execution/execute.js:364:18",
            "    at Array.reduce (<anonymous>)",
            "    at executeFields (/rbd/pnpm-volume/0897a123-e913-41b8-a689-0921f96aa33a/node_modules/.registry.npmjs.org/graphql/0.13.2/node_modules/graphql/execution/execute.js:361:42)",
            "    at collectAndExecuteSubfields (/rbd/pnpm-volume/0897a123-e913-41b8-a689-0921f96aa33a/node_modules/.registry.npmjs.org/graphql/0.13.2/node_modules/graphql/execution/execute.js:772:10)",
            "    at completeObjectValue (/rbd/pnpm-volume/0897a123-e913-41b8-a689-0921f96aa33a/node_modules/.registry.npmjs.org/graphql/0.13.2/node_modules/graphql/execution/execute.js:762:10)",
            "    at completeValue (/rbd/pnpm-volume/0897a123-e913-41b8-a689-0921f96aa33a/node_modules/.registry.npmjs.org/graphql/0.13.2/node_modules/graphql/execution/execute.js:660:12)"
          ]
        }
      }
    }
  ]
}
```

**Comment by dncrews** [comment]
Do you have an example of some server code that reproduces this?

**Comment by kamranayub** [comment]
In the glitch code linked?

**Comment by dncrews** [comment]
sorry; didn't see a link to the source, and I didn't know glitch's url mechanism. Got it

**Comment by dncrews** [comment]
Your bug is here:

```js
  const books = [
    {
      name: 'Harry Potter and the Chamber of Secrets',
      author: 'J.K. Rowling',
      categoryHierarchy: [
        { name: 'Fiction', categories: { name: 'Fantasy', categories: [] } }
      ]
    },
    {
      name: 'Jurassic Park',
      author: 'Michael Crichton',
      categoryHierarchy: [
        { name: 'Fiction', categories: { name: 'Sci-Fi', categories: [] } }
      ]
    },
  ];
```
You aren't return an array for categories. should be:

```js
  const books = [
    {
      name: 'Harry Potter and the Chamber of Secrets',
      author: 'J.K. Rowling',
      categoryHierarchy: [
        { name: 'Fiction', categories: [ { name: 'Fantasy', categories: [] } ] }
      ]
    },
    {
      name: 'Jurassic Park',
      author: 'Michael Crichton',
      categoryHierarchy: [
        { name: 'Fiction', categories: [ { name: 'Sci-Fi', categories: [] } ] }
      ]
    },
  ];
```

**Comment by kamranayub** [comment]
Dang it, I need to try to reproduce it since I'm definitely returning the same structure as I was in apollo-server 1.x in the resolvers, so give me some time to get a proper repro.

**Comment by kamranayub** [comment]
@dncrews OK, I've managed to reproduce it (check the Glitch again)--it definitely seems to be due to my usage of `makeExecutableSchema` and `mergeSchemas`. Is there something I'm doing wrong? I thought I was following the docs correctly.

**Comment by dncrews** [comment]
This issues doesn't seem to be related to fragments. Aliases do not appear to be working with default resolvers in merged schemas:

This doesn't work:
```js
  const typeDefs = gql`
    type Query {
      book: Book
    }

    type Book {
      category: String!
    }
  `;

  const schema = makeExecutableSchema({ typeDefs });

  const resolvers = {
    Query: {
      book: () => ({ category: 'Test' })
    }
  };

  const server = new ApolloServer({
    schema: mergeSchemas({
      schemas: [ schema ],
      resolvers
    }),
  });
```

This does:
```js
  const typeDefs = gql`
    type Query {
      book: Book
    }

    type Book {
      category: String!
    }
  `;

  const schema = makeExecutableSchema({ typeDefs });

  const resolvers = {
    Query: {
      book: () => ({ category: 'Test' })
    },
    Book: {
      category: (parent) => parent.category // Adding default resolver to fix bug
    }
  };

  const server = new ApolloServer({
    schema: mergeSchemas({
      schemas: [ schema ],
      resolvers
    }),
  });
```

**Comment by souserge** [comment]
@kamranayub Are you sure you're using the latest version of `apollo-server`? I tried to reproduce the issue and it seems to work just fine. Running with node v8.11.3 and this code: [gist](https://gist.github.com/souserge/427d8ef5f9d7f48f120bc52d56917c29)

**Comment by kamranayub** [comment]
I can double check, have you run the glitch code? That is reproducing the
issue live as Dan found.

**Comment by kamranayub** [comment]
@souserge With your code and deps it still fails. See:

```
# Write your query or mutation here
{
  book {
    cat: category
  }
}
```

And the code: https://glitch.com/edit/#!/pinto-hip
