### ISSUE TITLE
_apolloServerKoa.Koa is not a constructor

### ISSUE THREAD

**Issue by rajinder-yadav** [apollographql/apollo-server#1776]
Unable to use koa with Apollo server, getting the following error:

```sh
/home/XXX/dev/angular/graphql-nodejs-angular-demo/backend/dist/server.js:43
var app = new _apolloServerKoa.Koa();
          ^

TypeError: _apolloServerKoa.Koa is not a constructor
    at Object.<anonymous> (/home/yadav/dev/angular/graphql-nodejs-angular-demo/backend/dist/server.js:43:11)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:742:12)
    at startup (internal/bootstrap/node.js:266:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:596:3)
```

**Comment by abernix** [comment]
I realize it's been quite some time since you opened this, but if you haven't already figured this out, I'd recommend taking this question to the [Apollo community on Spectrum.chat](https://spectrum.chat/apollo) to discuss it further.  Thanks!
