### ISSUE TITLE
TypeError: Cannot create property 'Upload' on string `type Query { hello : String } `

### ISSUE THREAD

**Issue by pacifio** [apollographql/apollo-server#1905]
This is really bothering as I just can't fix it ... please help me out
I am trying to create a simple server with apollo server express and express js but this is the error 
"TypeError: Cannot create property 'Upload' on string"

I am trying to create a package for my work which allows to create an express server with apollo under 3 - 4 lines . I know that there is yoga server but I don't like it and I am just writing too much boilerplate code so I am making this package but this just comes again and again .

My console output
```bash
TypeError: Cannot create property 'Upload' on string 'type Query{hello : String}'
    at new ApolloServerBase (/home/adib/Desktop/Coding/apollo/zathura.js/node_modules/apollo-server-core/dist/ApolloServer.js:100:38)
    at new ApolloServer (/home/adib/Desktop/Coding/apollo/zathura.js/node_modules/apollo-server-express/dist/ApolloServer.js:41:1)
    at Object.exports.server (/home/adib/Desktop/Coding/apollo/zathura.js/dist/main.js:40:28)
    at Object.<anonymous> (/home/adib/Desktop/Coding/apollo/zathura.js/example/server.js:12:9)
    at Module._compile (module.js:653:30)
    at Object.Module._extensions..js (module.js:664:10)
    at Module.load (module.js:566:32)
    at tryModuleLoad (module.js:506:12)
    at Function.Module._load (module.js:498:3)
    at Function.Module.runMain (module.js:694:10)
```

The part where it is executing ...
```javascript
const apolloServer: any = new ApolloServer({
      typeDefs: apolloSetting.typeDefs,
      resolvers: apolloSetting.typeDefs,
      playground: apolloSetting.playgroundPath,
      context: apolloSetting.context
 });    
let graphqlPathFixed: String;
if(apolloSetting.graphqlPath) { graphqlPathFixed = apolloSetting.graphqlPath } else {
      graphqlPathFixed = '/graphql';
}
apolloServer.applyMiddleware({ app, path: graphqlPathFixed });
```

**Comment by pacifio** [comment]
Sorry forgot to gql in front of the schema / typeDefs
