### ISSUE TITLE
gql tag breaks ESM

### ISSUE THREAD

**Issue by andrewnaeve** [apollographql/apollo-server#2160]
I'm running my server through ESM, https://github.com/standard-things/esm#readme, and using gql tags on my typeDefs breaks makeExecutableSchema. With the tag on, I get this:  

```
const __global__ = this;(function (require, module, __jest__, __shared__) { "use strict";var __shared__;const e=module,t={Array:global.Array,Buffer:global.Buffer,Error:global.Error,EvalError:global.EvalError,Function:global.Function,JSON:global.JSON,Object:global.Object,Promise:global.Promise,RangeError:global.RangeError,ReferenceError:global.ReferenceError,Reflect:global.Reflect,SyntaxError:global.SyntaxError,TypeError:global.TypeError,URIError:global.URIError,eval:global.eval},r=global.console;module.exports=(function(e){var t={};function r(i){if(t[i])return t[i].exports;var n=t[i]={i:i,l:!1,exports:{}};return e[i].call(n.exports,n,n.exports,r),n.l=!0,n.exports}return r.d=function(e,t,r){Reflect.defineProperty(e,t,{configurable:!0,enumerable:!0,get:r})},r.n=function(e){return e.a=e,()=>e.a},r.r=function(){},r(r.s=2)})([(function(e,t){var r;t=e.exports=H,"object"==typeof process&&process,r=function(){},t.SEMVER_SPEC_VERSION="2.0.0";var i=256,n=Num
GraphQLError: Syntax Error: Unexpected [
    at syntaxError (/Users/arn/Code/seeds/api/node_modules/graphql/error/syntaxError.js:24:10)
    at unexpected (/Users/arn/Code/seeds/api/node_modules/graphql/language/parser.js:1490:33)
    at parseDefinition (/Users/arn/Code/seeds/api/node_modules/graphql/language/parser.js:153:9)
    at many (/Users/arn/Code/seeds/api/node_modules/graphql/language/parser.js:1523:16)
    at parseDocument (/Users/arn/Code/seeds/api/node_modules/graphql/language/parser.js:113:18)
    at Object.parse (/Users/arn/Code/seeds/api/node_modules/graphql/language/parser.js:48:10)
    at Object.buildSchemaFromTypeDefinitions (/Users/arn/Code/seeds/api/node_modules/graphql-tools/dist/generate/buildSchemaFromTypeDefinitions.js:19:33)
    at makeExecutableSchema (/Users/arn/Code/seeds/api/node_modules/graphql-tools/dist/makeExecutableSchema.js:26:29)
    at Object.<anonymous> (/Users/arn/Code/seeds/api/src/graphql/schema.js:20:16)
```
This is because consoling out the gql tagged definitions prints out:
```
{ kind: 'Document',
  definitions:
   [ { kind: 'ObjectTypeDefinition',
       description: undefined,
       name: [Object],
       interfaces: [],
       directives: [],
       fields: [Array] },
     { kind: 'ObjectTypeExtension',
       name: [Object],
       interfaces: [],
       directives: [],
       fields: [Array] } ],
  loc: { start: 0, end: 145 } }
```

If I take the gql tag off, the server boots up just fine, and the typedefs console out as the string that they are. I'm not sure if this is a 'you', 'them' or 'me' problem, but just thought I would bring it up just in case.

Let me know if any other info would help.

**Comment by Toreilly317** [comment]
Hey Andrew, were you ever able to solve this using gql? I am running into this problem as well.

**Comment by Schachte** [comment]
@Toreilly317 Did you solve this? Also running into similar issue.
