### ISSUE TITLE
TypeError: _apolloServerKoa.ApolloSever is not a constructor

### ISSUE THREAD

**Issue by stefan-jevtic** [apollographql/apollo-server#2508]
Hello all,
I'm facing this problem when i try to make an instance of Apollo Server with Koa.js framework on backend. 
Here is the code:
```
import Koa from "koa";
import { ApolloSever, gql } from "apollo-server-koa";
import typeDefs from "./schema";
import resolvers from "./resolvers";
import db from './models/index';
import serve from 'koa-static';

const server = new ApolloSever({
    typeDefs,
    resolvers,
    context: { db }
});

const app = new Koa();
server.applyMiddleware({ app });

app.use(serve(__dirname + '/public'))

app.listen(4000);
```

And the error is:
```
var server = new _apolloServerKoa.ApolloSever({
             ^

TypeError: _apolloServerKoa.ApolloSever is not a constructor
    at Object.<anonymous> (/home/server.js:8:16)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Module._compile (/home/node_modules/pirates/lib/index.js:99:24)
    at Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Object.newLoader [as .js] (/home/node_modules/pirates/lib/index.js:104:7)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at Object.<anonymous> (/home/node_modules/@babel/node/lib/_babel-node.js:234:23)
    at Module._compile (internal/modules/cjs/loader.js:799:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:810:10)
    at Module.load (internal/modules/cjs/loader.js:666:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:606:12)
    at Function.Module._load (internal/modules/cjs/loader.js:598:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:862:12)
    at internal/main/run_main_module.js:21:11
```

I've tried to fix it with installing `apollo-server-koa@rc` as it mentioned here #1296 but didn't help.
Any tips?

**Comment by stefan-jevtic** [comment]
Solved!
I had a damn typo, i've imported ApolloSever instead ApolloServer
