### ISSUE TITLE
apollo-server-lambda with @apollo/federation does not work. Error while loading graphql.

### ISSUE THREAD

**Issue by ampProjects** [apollographql/apollo-server#2819]
* ❗️ Bug?
          I am trying to use @apollo/federation in lambda function. I have followed the same example in codebox, but I always have the same issue.
         I use serverless package to run and deploy my app.
        This is my example code:

`import { ApolloServer, gql } from 'apollo-server-lambda';
import { buildFederatedSchema } from '@apollo/federation';

const users = [
  {
    id: '1',
    name: 'Ada Lovelace',
    username: '@ada',
  },
  {
    id: '2',
    name: 'Alan Turin',
    username: '@alan',
  },
];

const typeDefs = gql`
  extend type Query {
    me: [User]
  }

  type User @key(fields: 'id') {
    id: ID!
    name: String
    username: String
  }
`;

const resolvers = {
  Query: {
    me() {
      return users;
    },
  },
  User: {
    __resolveReference(object) {
      return users.find(user => user.id === object.id);
    },
  },
};

const server = new ApolloServer({
  schema: buildFederatedSchema([
    {
      typeDefs,
      resolvers,
    },
  ]),
});

export default server.createHandler();`

This is my error when I try to run localy my graphql server as a Lambda function:

Serverless: ANY /graphql (λ: graphql)
Serverless: Error while loading graphql
[ 'TypeError: Cannot read property \'kind\' of undefined',
  'at KnownDirectives (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\node_modules\\graphql\\validation\\rules\\KnownDirectives.js:78:15)',
  'at C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\node_modules\\graphql\\validation\\validate.js:72:12',
  'at Array.map (<anonymous>)',
  'at Object.validateSDL (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\node_modules\\graphql\\validation\\validate.js:71:24)',
  'at Object.buildSchemaFromSDL (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\node_modules\\apollo-graphql\\src\\schema\\buildSchemaFromSDL.ts:64:18)',
  'at buildFederatedSchema (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\node_modules\\@apollo\\federation\\src\\service\\buildFederatedSchema.ts:30:16)',
  'at Module../src/graphql/index.js (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\.webpack\\service\\src\\webpack:\\src\\graphql\\index.js:7:36)',
  'at __webpack_require__ (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\.webpack\\service\\src\\webpack:\\webpack\\bootstrap:19:1)',
  'at Module../src/apolloserver.config.js (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\.webpack\\service\\src\\index.js:106:66)',
  'at __webpack_require__ (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\.webpack\\service\\src\\webpack:\\webpack\\bootstrap:19:1)',
  'at Module../src/server.js (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\.webpack\\service\\src\\index.js:332:78)',
  'at __webpack_require__ (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\.webpack\\service\\src\\webpack:\\webpack\\bootstrap:19:1)',
  'at Module../src/index.js (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\.webpack\\service\\src\\webpack:\\src\\index.js:1:1)',
  'at __webpack_require__ (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\.webpack\\service\\src\\webpack:\\webpack\\bootstrap:19:1)',
  'at C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\.webpack\\service\\src\\webpack:\\webpack\\bootstrap:83:1',
  'at Object.<anonymous> (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\.webpack\\service\\src\\index.js:87:10)',
  'at Module._compile (internal/modules/cjs/loader.js:701:30)',
  'at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)',
  'at Module.load (internal/modules/cjs/loader.js:600:32)',
  'at tryModuleLoad (internal/modules/cjs/loader.js:539:12)',
  'at Function.Module._load (internal/modules/cjs/loader.js:531:3)',
  'at Module.require (internal/modules/cjs/loader.js:637:17)',
  'at require (internal/modules/cjs/helpers.js:22:18)',
  'at Object.createHandler (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\node_modules\\serverless-offline\\src\\functionHelper.js:194:17)',
  'at handler (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\node_modules\\serverless-offline\\src\\index.js:660:44)',
  'at module.exports.internals.Manager.execute (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\node_modules\\@hapi\\hapi\\lib\\toolkit.js:41:33)',
  'at Object.internals.handler (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\node_modules\\@hapi\\hapi\\lib\\handler.js:46:48)',
  'at exports.execute (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\node_modules\\@hapi\\hapi\\lib\\handler.js:31:36)',
  'at Request._lifecycle (C:\\Users\\amarquez\\Documents\\Proyectos\\User Access Management\\gateway\\accounts\\node_modules\\@hapi\\hapi\\lib\\request.js:312:68)' ]

Thanks.

**Comment by ampProjects** [comment]
Sorry for this issue, I found the problem.
When I type de typeDefs, I use in @key(fields: "id") a simple cuotation and this failed when the schema as uploaded.
