### ISSUE TITLE
build failed when import apollo-server-express with webpack

### ISSUE THREAD

**Issue by ozee31** [apollographql/apollo-server#2846]
I have a small express application but when add `const { ApolloServer } = require("apollo-server-express");` build failed with this error

```
webpack:///./node_modules/graphql-tools/dist/stitching/introspectSchema.js?:39
var parsedIntrospectionQuery = graphql_1.parse(graphql_1.introspectionQuery);
                                         ^

TypeError: graphql_1.parse is not a function
    at eval (webpack:///./node_modules/graphql-tools/dist/stitching/introspectSchema.js?:39:42)
    at Object../node_modules/graphql-tools/dist/stitching/introspectSchema.js (/project/build/server.js:1554:1)
    at __webpack_require__ (/project/build/server.js:20:30)
    at eval (webpack:///./node_modules/graphql-tools/dist/stitching/index.js?:5:26)
    at Object../node_modules/graphql-tools/dist/stitching/index.js (/project/build/server.js:1543:1)
    at __webpack_require__ (/project/build/server.js:20:30)
    at eval (webpack:///./node_modules/graphql-tools/dist/index.js?:7:10)
    at Object../node_modules/graphql-tools/dist/index.js (/project/build/server.js:1422:1)
    at __webpack_require__ (/project/build/server.js:20:30)
    at eval (webpack:///./node_modules/apollo-server-core/dist/ApolloServer.js?:23:25)
[nodemon] app crashed - waiting for file changes before starting...
```

Env : Node 10.16

Dependencies :

```json
"dependencies": {
    "apollo-server": "^2.6.3",
    "apollo-server-express": "^2.6.3",
    "config": "^3.1.0",
    "cors": "^2.8.5",
    "express": "^4.17.1",
    "graphql": "^14.3.1"
  },
  "devDependencies": {
    "@babel/core": "^7.4.5",
    "@babel/plugin-proposal-object-rest-spread": "^7.4.4",
    "@babel/preset-env": "^7.4.5",
    "@babel/register": "^7.4.4",
    "babel-core": "^6.26.3",
    "babel-loader": "^8.0.6",
    "babel-plugin-root-import": "^6.2.0",
    "babel-plugin-syntax-async-functions": "^6.13.0",
    "eslint": "^5.16.0",
    "eslint-config-prettier": "^4.3.0",
    "eslint-plugin-import": "^2.17.3",
    "eslint-plugin-prettier": "^3.1.0",
    "fs-extra": "^8.0.1",
    "jest": "^24.8.0",
    "jest-express": "^1.10.1",
    "nodemon": "^1.19.1",
    "nodemon-webpack-plugin": "^4.0.8",
    "post-compile-webpack-plugin": "^0.1.2",
    "prettier": "^1.18.2",
    "supertest": "^4.0.2",
    "webpack": "^4.34.0",
    "webpack-cli": "^3.3.4",
    "webpack-node-externals": "^1.7.2"
  }
```

webpack.config.js

```js
const path = require("path");
const webpack = require("webpack");
const nodeExternals = require("webpack-node-externals");
const PostCompile = require("post-compile-webpack-plugin");
const fs = require("fs-extra");

const buildDir = path.join(__dirname, "build");
const buildFilename = "server.js";

const PRODUCTION = process.env.NODE_ENV === "production";

module.exports = {
  target: "node",

  externals: [nodeExternals()],

  entry: "./src/index.js",

  output: {
    path: buildDir,
    filename: buildFilename
  },

  context: __dirname,
  node: {
    __filename: false,
    __dirname: false
  },

  resolve: {
    extensions: [".js"]
  },

  mode: PRODUCTION ? "production" : "development",

  plugins: [
    new webpack.DefinePlugin({
      __DIST: JSON.stringify(PRODUCTION)
    }),
    new PostCompile(() => {
      ["config"].forEach(dir => {
        fs.copySync(
          path.resolve(__dirname, `./${dir}`),
          path.resolve(buildDir, `./${dir}`)
        );
      });

      const dist_package = {
        name: "itm-v2",
        main: buildFilename,
        license: "private",
        private: true,
        scripts: {
          start: `node ${buildFilename}`
        }
      };

      const self_package = require(path.resolve(__dirname, "./package.json"));

      const release_package = Object.assign({}, self_package, dist_package);
      if (release_package.devDependencies) {
        delete release_package.devDependencies;
      }

      fs.writeFileSync(
        path.resolve(buildDir, "./package.json"),
        JSON.stringify(release_package, null, 2)
      );
    })
  ],

  module: {
    rules: [
      {
        test: /\.js$/,
        exclude: /(node_modules|bower_components)/,
        use: {
          loader: "babel-loader"
        }
      }
    ]
  }
};

```

**Comment by ozee31** [comment]
OH! It's work after a restart... sory
