### ISSUE TITLE
Server not catching rejection/exception in merged schema resolvers

### ISSUE THREAD

**Issue by timcosta** [apollographql/apollo-server#2869]
Apollo Versions:
```bash
npm ls apollo-server apollo-server-hapi
my-pkg@0.1.0 /Users/tcosta/path/to/my-pkg
├── apollo-server@2.4.8
└── apollo-server-hapi@2.4.8
```

Stack trace logged:
```
/usr/src/app/src/index.js:87
        throw err;
        ^
TypeError: Cannot read property 'length' of undefined
    at resolve (/usr/src/app/src/remote_schemas/api_one/index.js:228:46)
    at field.resolve (/usr/src/app/node_modules/graphql-tools/dist/stitching/mergeSchemas.js:188:24)
    at field.resolve (/usr/src/app/node_modules/graphql-extensions/dist/index.js:128:26)
    at resolveFieldValueOrError (/usr/src/app/node_modules/graphql/execution/execute.js:480:18)
    at resolveField (/usr/src/app/node_modules/graphql/execution/execute.js:447:16)
    at executeFields (/usr/src/app/node_modules/graphql/execution/execute.js:294:18)
    at collectAndExecuteSubfields (/usr/src/app/node_modules/graphql/execution/execute.js:724:10)
    at completeObjectValue (/usr/src/app/node_modules/graphql/execution/execute.js:714:10)
    at completeValue (/usr/src/app/node_modules/graphql/execution/execute.js:603:12)
    at completeValue (/usr/src/app/node_modules/graphql/execution/execute.js:570:21)
    at completeValueCatchingError (/usr/src/app/node_modules/graphql/execution/execute.js:508:19)
    at resolveField (/usr/src/app/node_modules/graphql/execution/execute.js:448:10)
    at executeFields (/usr/src/app/node_modules/graphql/execution/execute.js:294:18)
    at collectAndExecuteSubfields (/usr/src/app/node_modules/graphql/execution/execute.js:724:10)
    at completeObjectValue (/usr/src/app/node_modules/graphql/execution/execute.js:714:10)
    at completeValue (/usr/src/app/node_modules/graphql/execution/execute.js:603:12)
    at completeValueCatchingError (/usr/src/app/node_modules/graphql/execution/execute.js:508:19)
    at /usr/src/app/node_modules/graphql/execution/execute.js:628:25
    at Array.forEach (<anonymous>)
    at forEach (/usr/src/app/node_modules/iterall/index.js:83:25)
    at completeListValue (/usr/src/app/node_modules/graphql/execution/execute.js:624:24)
    at completeValue (/usr/src/app/node_modules/graphql/execution/execute.js:586:12)
```

Code being executed:
```javascript
Course: {
    name: {
        fragment: '...on Course { sections { uuid } }',
        resolve: async (parent, args, context) => {
            this.log(context, {
                method: 'Course.name.resolve',
                parent,
                args,
            });
            // parent.sections is undefined, causing error to be thrown
            if (!parent.sections.length) return 'ERR_NO_VALID_SECTIONS';
            return parent.sections[0].name;
        }
    }
}
```

I would except this to bubble up as a graphql error of code `INTERNAL_SERVER_ERROR` but instead i'm getting a full process crash due to an unhandled rejection. My `process.on('unhandledRejection'` catcher is being hit, which feels like it should be possible.

This schema is being built from remotely introspected schemas, and then merged with local schemas and added resolvers in a graphql gateway style pattern.

The code we are using for the stitching is: 
```javascript
    const opts = Object.assign({}, defaultGQLServerOpts);
    const schemas = [gatewaySchema];
    const resolvers = [];
    await Promise.map(Object.values(RemoteSchemas), async (directory) => {
        const RemoteSchema = directory['index.js'];
        const rsInstance = new RemoteSchema(dataCache);
        if (rsInstance.shouldStitchSchema) {
            try {
                const remoteSchema = await rsInstance.getSchema();
                schemas.push(remoteSchema);
                schemas.push(rsInstance.getExtendedTypeDefs());
                resolvers.push(rsInstance.getResolvers());
            } catch (e) {
                console.error(e); // eslint-disable-line no-console
            }
        }
    });
    opts.schema = mergeSchemas({
        schemas,
        resolvers,
    });
```

The error is being throw in a function that is in the object returned by `rsInstance.getResolvers()`. This return value is just a javascript object with resolver functions for the remote schema that is being stitched into our local schema.

I can't reproduce this on glitch, though i tried, so i'm hoping that the stack trace above as well as all of the code examples provided are enough to track down the issue.

**Comment by martijnwalraven** [comment]
This behavior is part of `graphql-tools`, so you may want to open an issue there. Note that schema stitching is being deprecated and the recommendation is to migrate to federation however.
