### ISSUE TITLE
apollo-server-fastify - file upload error

### ISSUE THREAD

**Issue by blacksmoke26** [apollographql/apollo-server#3139]
The following code:
```js
const Fastify = require('fastify');
const { ApolloServer } = require('apollo-server-fastify');

///............ typeDefs, resolvers stuff ..............

const server = new ApolloServer({
  typeDefs,
  resolvers,
  uploads: {
    maxFileSize: 10000000, // 10 MB
    maxFiles: 20
  },
});

console.log(server);

(async function () {
  app.register(server.createHandler());
  await app.listen(process.env.PORT);
})();
```

Throws error:
```
...\fastify-graphql-upload\server\node_modules\apollo-server-core\dist\ApolloServer.js:146
                throw new Error('This implementation of ApolloServer does not support file uploads because the environment cannot accept multi-part forms');
                ^

Error: This implementation of ApolloServer does not support file uploads because the environment cannot accept multi-part forms
    at new ApolloServerBase (...\fastify-graphql-upload\server\node_modules\←[4mapollo-server-core←[24m\dist\ApolloServer.js:146:23)
    at new ApolloServer (...\fastify-graphql-upload\server\node_modules\←[4mapollo-server-fastify←[24m\dist\ApolloServer.js:45:1)
    at new CostAnalysisApolloServer (...\fastify-graphql-upload\server\src\index.js:55:1)
    at Object.<anonymous> (...\fastify-graphql-upload\server\src\index.js:70:16)
←[90m    at Module._compile (internal/modules/cjs/loader.js:777:30)←[39m
←[90m    at Object.Module._extensions..js (internal/modules/cjs/loader.js:788:10)←[39m
←[90m    at Module.load (internal/modules/cjs/loader.js:643:32)←[39m
←[90m    at Function.Module._load (internal/modules/cjs/loader.js:556:12)←[39m
←[90m    at Function.Module.runMain (internal/modules/cjs/loader.js:840:10)←[39m
←[90m    at internal/main/run_main_module.js:17:11←[39m
[nodemon] app crashed - waiting for file changes before starting...
```

Any proper example of how to upload file?

**Comment by trevor-scheer** [comment]
Hey @blacksmoke26, can you please provide us with a runnable reproduction?

That error is unexpected from the fastify integration since it explicitly supports file uploads:
https://github.com/apollographql/apollo-server/blob/master/packages/apollo-server-fastify/src/ApolloServer.ts#L69

**Comment by blacksmoke26** [comment]
I think it's fixed in the latest version. I just leave `uploads` property as it is. Things are working fine now.
