### ISSUE TITLE
Fragment cannot be spread here as objects of type "_Entity" can never be of type "X"

### ISSUE THREAD

**Issue by dredl** [apollographql/apollo-server#3141]
Hi everyone!
From apollo-server v 2.8.0 we are able to use same Value Types in multiple services:
https://www.apollographql.com/docs/apollo-server/federation/core-concepts/#value-types

As an example I experimented with federation-demo:
https://github.com/apollographql/federation-demo

I've added object type (Logs) in **account service**:
```
extend type Query {
  me: User
}

type User @key(fields: "id") {
  id: ID!
  name: String
  username: String
  logs: [Logs]
}
type Logs {
  id: ID
  message: String
}
```
and the same type in **products service**:
```
extend type Query {
  topProducts(first: Int = 5): [Product]
}

type Product @key(fields: "upc") {
  upc: String!
  name: String
  price: Int
  weight: Int
  logs: [Logs]
}
type Logs {
  id: ID
  message: String
}
```
all project is compiled successfully and now we may use one object type (Logs) in multiple services (according the rule of value types in federated service is that the types **must be identical** in name and contents):
![image](https://user-images.githubusercontent.com/9267716/62760022-c8561b80-baa4-11e9-9428-b8c105e3e52f.png)

But when i try to prepare data for logs property: 
```
const users = [
  {
    id: "1",
    name: "Ada Lovelace",
    birthDate: "1815-12-10",
    username: "@ada",
    logs: [
      {
        id: 1,
        message: "Some Message"
      }
    ]
  }
];
```
I got the following error:
```
"errors": [
    {
      "message": "400: Bad Request",
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "response": {
          "url": "http://localhost:4003/graphql",
          "status": 400,
          "statusText": "Bad Request",
          "body": {
            "errors": [
              {
                "message": "Fragment cannot be spread here as objects of type \"_Entity\" can never be of type \"Logs\".",
                "locations": [
                  {
                    "line": 3,
                    "column": 5
                  }
                ],
                "extensions": {
                  "code": "GRAPHQL_VALIDATION_FAILED",
                  "exception": {
                    "stacktrace": [
                      "GraphQLError: Fragment cannot be spread here as objects of type \"_Entity\" can never be of type \"Logs\".",
                      "    at Object.InlineFragment (C:\\_Redl\\temp\\federation-demo\\services\\products\\node_modules\\graphql\\validation\\rules\\PossibleFragmentSpreads.js:45:29)",
                      "    at Object.enter (C:\\_Redl\\temp\\federation-demo\\services\\products\\node_modules\\graphql\\language\\visitor.js:324:29)",
                      "    at Object.enter (C:\\_Redl\\temp\\federation-demo\\services\\products\\node_modules\\graphql\\language\\visitor.js:375:25)",
                      "    at visit (C:\\_Redl\\temp\\federation-demo\\services\\products\\node_modules\\graphql\\language\\visitor.js:242:26)",
                      "    at Object.validate (C:\\_Redl\\temp\\federation-demo\\services\\products\\node_modules\\graphql\\validation\\validate.js:54:22)",
                      "    at validate (C:\\_Redl\\temp\\federation-demo\\services\\products\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:211:32)",
                      "    at Object.<anonymous> (C:\\_Redl\\temp\\federation-demo\\services\\products\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:124:42)",
                      "    at Generator.next (<anonymous>)",
                      "    at fulfilled (C:\\_Redl\\temp\\federation-demo\\services\\products\\node_modules\\apollo-server-core\\dist\\requestPipeline.js:4:58)",
                      "    at processTicksAndRejections (internal/process/task_queues.js:85:5)"
                    ]
                  }
                }
              }
            ]
          }
        }
      }
    }
  ],
``` 
Is it a bug or I'm doing something wrong?

**Comment by trevor-scheer** [comment]
Hey @dredl, thanks for the detailed reproduction steps - I was able to reproduce this and it's definitely a bug. We'll look into this!

**Comment by victorandree** [comment]
I ran into the same issue, wrote [a reproducible example](https://github.com/victorandree/apollo-federation-value-types) and did some digging before I found this issue. Maybe this is helpful :) 

- When services are composed, a type to service map is built (`typeToServiceMap`). In building this map, the [documented behavior is that the last definition wins](https://github.com/apollographql/apollo-server/blob/675e97bc92436979e0fa50d38f21694c594b8b12/packages/apollo-federation/src/composition/compose.ts#L159).
- The `typeToServiceMap` is used to attach `federation` metadata to the gateway's types. It will therefore say that queries for a given type should go to the last service to define it.
- When the query planner starts splitting fields, it think it must go to the last service in order to find it.

I tried mutating my schema to simply remove `.federation` from the value type. This allows the value type field to be resolved, but its fields cannot in turn be resolved (because now the query planner can't figure out who owns _that_ field).

This is just from some digging in the code, but I don't really have a solution. I'd probably not add types without `@key` to the type-to-service map such that they don't have `.federation` properties. Such types then have to be entirely resolved by (`@provide`d by) the service owning the field. Tried hacking `@provides` too, but you can't `@provide` a field which doesn't have a `@key` so.

**Comment by trevor-scheer** [comment]
@victorandree thanks for the digging! I started looking into this yesterday and found the same as you, but you got a bit further than I. Service->type ownership is an oversight on my part when I first implemented these changes. I'll be starting on this today 😄
