### ISSUE TITLE
New Relic transaction throwing error when apollo tries to send multiple queries

### ISSUE THREAD

**Issue by doudou1212** [apollographql/apollo-server#3209]
I try to send a query
```
{
  posts(
    app_name:"xxx",
    section_name: "xxx",
    user_type: "xx"
  )
  {
    posts {
      title
      fields{
        video{
            mediaInfo
        }
      }
    }
  }
}
```
In above query, when getting `mediaInfo` in Video, it will send another request to get media info. 
So actually the above query will send two requests:
1. get post
2. get mediaInfo

While I got a error:

```
 this._segment && this._segment.probe('Segment removed from tracer')
                                   ^

TypeError: this._segment.probe is not a function
    at Tracer.segmentSetter (/path/node_modules/newrelic/lib/transaction/tracer/index.js:46:36)
    at Shim.setActiveSegment (/path/node_modules/newrelic/lib/shim/shim.js:1311:30)
    at process.wrappedFatalException [as _fatalException] (/path/node_modules/newrelic/lib/instrumentation/core/globals.js:21:14)
```

newrelic version: 5.7.0
apollo-server-express version: 2.8.1
graphql version: 14.2.1
node version: 10.15.3

### This bug report should include:

- [ ] A short, but descriptive title. The title doesn't need "Apollo" in it.
- [ ] The package name and version of Apollo showing the problem.
- [ ] If applicable, the last version of Apollo where the problem did _not_ occur.
- [ ] The expected behavior.
- [ ] The actual behavior.
- [ ] A **simple**, runnable reproduction!
      Please make a GitHub repository that anyone can clone and run and see the
      problem.  Other great ways to demonstrate a reproduciton are using our
      CodeSandbox template (https://codesandbox.io/s/apollo-server), or re-mixing
      our Glitch template (https://glitch.com/~apollo-launchpad).
-->

**Comment by doudou1212** [comment]
we resolve this problem so closed issue
