### ISSUE TITLE
Apollo Gateway minimum example doesn't work

### ISSUE THREAD

**Issue by cramshaw** [apollographql/apollo-server#3275]
I've just updated Apollo and Apollo gateway - currently running:
```
"dependencies": {
    "@apollo/gateway": "^0.6.14",
    "apollo-server": "^2.9.3",
    "cookie-parser": "^1.4.4",
    "graphql": "^14.5.4"
  },
```

When attempting to run the minimum example from this page of the docs: 
https://www.apollographql.com/docs/apollo-server/federation/implementing/

```
const { ApolloServer } = require('apollo-server');
const { ApolloGateway } = require("@apollo/gateway");

const gateway = new ApolloGateway({
  serviceList: [
    { name: 'accounts', url: 'http://localhost:4001' },
    // more services
  ],
});

const server = new ApolloServer({
  gateway,
  
  // Currently, subscriptions are enabled by default with Apollo Server, however,
  // subscriptions are not compatible with the gateway.  We hope to resolve this
  // limitation in future versions of Apollo Server.  Please reach out to us on
  // https://spectrum.chat/apollo/apollo-server if this is critical to your adoption!
  subscriptions: false,
});

server.listen().then(({ url }) => {
  console.log(`🚀 Server ready at ${url}`);
});
```

I have changed the url to my own GraphQL service which I knew was running.
I get:
```
 /app/node_modules/apollo-server-core/dist/ApolloServer.js:218
             this.toDispose.add(gateway.onSchemaChange(schema => (this.schemaDerivedData = Promise.resolve(this.generateSchemaDerivedData(schema)))));
                                        ^
 
 TypeError: gateway.onSchemaChange is not a function
     at ApolloServer.initSchema (/app/node_modules/apollo-server-core/dist/ApolloServer.js:218:40)
     at new ApolloServerBase (/app/node_modules/apollo-server-core/dist/ApolloServer.js:202:30)
     at new ApolloServer (/app/node_modules/apollo-server-express/dist/ApolloServer.js:59:9)
     at new ApolloServer (/app/node_modules/apollo-server/dist/index.js:24:9)
     at Object.<anonymous> (/app/index.js:11:16)
     at Module._compile (internal/modules/cjs/loader.js:774:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:785:10)
     at Module.load (internal/modules/cjs/loader.js:641:32)
     at Function.Module._load (internal/modules/cjs/loader.js:556:12)
     at Function.Module.runMain (internal/modules/cjs/loader.js:837:10)
```
I have managed to make this work by implementing the gateway manually:
```
let newSchema;
const { schema, executor } = await gateway.load();
...
gateway: {
      load: () => {
        return Promise.resolve({
          schema,
          executor
        });
      },
      /**
          * The callback received here is an Apollo internal function which actually update
          * the schema stored by Apollo Server. We init an event listener to execute this function
          * on schema update
          */
      onSchemaChange: callback => {
        schemaChange = newSchema => callback(newSchema)
      }
    },
```
But is this the anticipated result of running the minimum example from the docs? 

Thanks!

**Comment by trevor-scheer** [comment]
Hey @cramshaw, thanks for submitting this and I appreciate the level of detail! I was able to reproduce the problem using the versions you provided, and I resolved by updating the gateway version `npm i @apollo/gateway@latest`.

[Version 0.6.x](https://www.npmjs.com/package/@apollo/gateway) is relatively dated at this point and doesn't support the newer `gateway` option that `ApolloServer` supports.
