### ISSUE TITLE
TypeError caused by tsconfig-paths

### ISSUE THREAD

**Issue by EmiyaYang** [apollographql/apollo-server#3436]
# Error Report

Just follow the tutorial demo but meet this error.

```
TypeError: graphql_1.parse is not a function
    at Object.<anonymous> (D:\Project\web\blog-service\node_modules\graphql-tools\src\stitching\introspectSchema.ts:7:48)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Object.require.extensions.(anonymous function) [as .js] (D:\Code\nodejs\node_global\node_modules\ts-node\src\index.ts:485:14)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Module.require (internal/modules/cjs/loader.js:692:17)
    at require (internal/modules/cjs/helpers.js:25:18)
    at Object.<anonymous> (D:\Project\web\blog-service\node_modules\graphql-tools\src\stitching\index.ts:2:1)
```

# Source Code

```bash
ts-node -r tsconfig-paths/register src/service.ts
```

```js
// src/server.ts
import Koa from "koa";

import server from "./graphql";

const app = new Koa();

server.applyMiddleware({ app });
```

<details>
<summary>src/graphql/index.ts</summary>

```js
import { ApolloServer, gql } from "apollo-server-koa";

const typeDefs = gql`
  # Comments in GraphQL strings (such as this one) start with the hash (#) symbol.

  # This "Book" type defines the queryable fields for every book in our data source.
  type Book {
    title: String
    author: String
  }

  # The "Query" type is special: it lists all of the available queries that
  # clients can execute, along with the return type for each. In this
  # case, the "books" query returns an array of zero or more Books (defined above).
  type Query {
    books: [Book]
  }
`;

const books = [
  {
    title: "Harry Potter and the Chamber of Secrets",
    author: "J.K. Rowling"
  },
  {
    title: "Jurassic Park",
    author: "Michael Crichton"
  }
];

// Resolvers define the technique for fetching the types defined in the
// schema. This resolver retrieves books from the "books" array above.
const resolvers = {
  Query: {
    books: () => books
  }
};

// The ApolloServer constructor requires two parameters: your schema
// definition and your set of resolvers.
export default new ApolloServer({ typeDefs, resolvers });
```

</details>

**Comment by EmiyaYang** [comment]
It seems to be the probelm with tsconfig-paths/register. 
Run `ts-node -r ./src/service.ts` is OK.

**Comment by glasser** [comment]
This is not a self-contained reproduction so I can't tell if this applies anymore.
