### ISSUE TITLE
buildFederatedSchema throws when a directive uses an input type

### ISSUE THREAD

**Issue by AvivRubys** [apollographql/apollo-server#3655]
I've tried replacing the input type with a scalar and an enum, they both work fine, it's only inputs that are crashing.

Reproducible example:
```js
const {gql} = require('apollo-server');
const {buildFederatedSchema} = require('@apollo/federation');

const typeDefs = gql`
    directive @someDirective(input: SomeInput) on FIELD_DEFINITION

    input SomeInput {
        key: String
    }
`;

buildFederatedSchema(typeDefs);
```

Package versions:
0.11.2 - @apollo/federation
2.9.15 - apollo-server
14.5.8 - graphql

**Comment by AvivRubys** [comment]
Forgot to add, the error:
```    Schema must contain uniquely named types but contains multiple types named "SomeInput".
      at typeMapReducer (node_modules/graphql/type/schema.js:262:13)
      at node_modules/graphql/type/schema.js:307:12
          at Array.reduce (<anonymous>)
      at typeMapDirectiveReducer (node_modules/graphql/type/schema.js:306:25)
          at Array.reduce (<anonymous>)
      at new GraphQLSchema (node_modules/graphql/type/schema.js:147:32)
      at Object.transformSchema (node_modules/apollo-graphql/src/schema/transformSchema.ts:51:10)
      at buildFederatedSchema (node_modules/@apollo/federation/src/service/buildFederatedSchema.ts:98:12)
```

**Comment by AvivRubys** [comment]
`buildFederatedSchema` calls `transformSchema`, which in turn uses `recreateNamedType`, which recreates objects, interfaces, unions, and input types, skipping scalars and enums which are also named types. This is probably why scalars and enums work but inputs don't.
Later on, `new GraphQLSchema` gets called, which verifies that within all types and all inner types (like the ones used in directives) there aren't duplicates. That's where this fails.
Sounds like `transformSchema` needs to update the reference in the directives too, or use some kind of different approach.

**Comment by mogui** [comment]
I'm having the exact problem too, but I cannot replace the input with something else because it comes from a package i'm using `@graphql-codegen/typescript-mongodb`.
My idea too is that something strange happens in `transformSchema`

**Comment by shawub** [comment]
+1
We are using ApolloGateway to federate and external api over which I have little control. 
```
"@apollo/federation": "^0.12.1",
"apollo-server": "^2.10.1",
"graphql": "^14.6.0",
```
Anybody got any ideas how to avoid this issue?

**Comment by AvivRubys** [comment]
@shawub we ended up stripping all nob-federation directives, and re-applying them after federation.
See - https://github.com/Soluto/stitch/blob/master/services/src/modules/buildFederatedSchema.ts#L41

**Comment by eritscher** [comment]
Is anyone able to look into this? We're running into this issue when using Apollo Federation to proxy a GQL API that uses inputs in directives which we can't control.
