### ISSUE TITLE
GraphQLError: Syntax Error: Unexpected Name "extend"

### ISSUE THREAD

**Issue by luandro** [apollographql/apollo-server#3697]
I've been trying to setup Federation but `extend` doesn't seem to be parsed by the GraphQL parser.

This is the definition that's throwing the error:
```
  extend type CurrentIdentity @key(fields: "id") {
    id: ID! @external

    profile: Person
  }
```

For the full definition check [here](https://gitlab.com/ahau/ssb-profile-graphql/blob/master/src/typeDefs.js#L45).

This is the exact error I'm getting:
```
GraphQLError: Syntax Error: Unexpected Name "extend"
    at syntaxError (/ahau/@ssb-graphql/profile/node_modules/graphql/error/syntaxError.js:15:10)
    at Parser.unexpected (/ahau/@ssb-graphql/profile/node_modules/graphql/language/parser.js:1463:41)
    at Parser.parseTypeSystemDefinition (/ahau/@ssb-graphql/profile/node_modules/graphql/language/parser.js:715:16)
    at Parser.parseDefinition (/ahau/@ssb-graphql/profile/node_modules/graphql/language/parser.js:154:19)
    at Parser.many (/ahau/@ssb-graphql/profile/node_modules/graphql/language/parser.js:1518:26)
    at Parser.parseDocument (/ahau/@ssb-graphql/profile/node_modules/graphql/language/parser.js:111:25)
    at parse (/ahau/@ssb-graphql/profile/node_modules/graphql/language/parser.js:36:17)
    at parseDocument (/ahau/@ssb-graphql/profile/node_modules/graphql-tag/lib/graphql-tag.umd.js:135:16)
    at gql (/ahau/@ssb-graphql/profile/node_modules/graphql-tag/lib/graphql-tag.umd.js:176:10)
    at Object.<anonymous> (/ahau/@ssb-graphql/profile/src/typeDefs.js:3:21)
```
And these are the package versions I'm using:
```
    "@apollo/federation": "^0.11.3",
    "apollo-server": "^2.9.3",
    "apollo-server-express": "^2.9.6",
```

**Comment by luandro** [comment]
@IvanGoncharov is this expected?

**Comment by luandro** [comment]
Might as well close this since no one seems to have an answer...

Opened a [new issue](https://github.com/graphql/graphql-js/issues/2385) in the graphql-js repo.

**Comment by shahzebmhd** [comment]
I feel like the answer to the question may lie in this issue, I had the same error but for adding a description to these extend type definitions, after removing it, the tests passed for me.  
https://github.com/apollographql/apollo-server/issues/2826
