### ISSUE TITLE
buildFederatedSchema: TypeError: Cannot read property 'kind' of undefined     at KnownDirectives (.../graphql/validation/rules/KnownDirectives.js:51:13)

### ISSUE THREAD

**Issue by terion-name** [apollographql/apollo-server#3740]
Don't know if it is a bug, but seems to be.

`buildFederatedSchema([{typeDefs, resolvers}])` fails on parsing valid document.
`resolvers` irrelevant, could be `{}`.
typeDefs:  https://gist.github.com/terion-name/514900b4f0fad1fc32f1f4ffe92cf93b

tracking the error what I've found that at `graphql/validation/rules/KnownDirectives.js:51:13` at some point `context.getDocument().definitions` (that is called multiple times) returns `[null]`. I've tried to debug  this for several days but no luck,  document is valid, I don't see any errors

**Comment by terion-name** [comment]
Oh. sorry, forgot that `typeDefs`  should not be a string, but a parsed document, wrapped with `gql()` and worked
