### ISSUE TITLE
Apollo-Server-Lambda and serverless-offline integration not working.

### ISSUE THREAD

**Issue by haayhappen** [apollographql/apollo-server#3826]
The serverless-offline integration seems to have a problem with the internal server of apollo-server-lambda. Please see the attached error response. Weird behavour is that I can access the graphiql schema explorer on the same endpoint.

**Package**: "apollo-server-lambda": "^2.10.1"

 **The expected behavior:** 
return data Json

**The actual behavior:** 
```
{
  "errors": [
    {
      "message": "Inaccessible host: `dynamodb.localhost.amazonaws.com'. This service may not be available in the `localhost' region.",
      "locations": [
        {
          "line": 30,
          "column": 2
        }
      ],
      "path": [
        "Koachs"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "message": "Inaccessible host: `dynamodb.localhost.amazonaws.com'. This service may not be available in the `localhost' region.",
          "code": "UnknownEndpoint",
          "region": "localhost",
          "hostname": "dynamodb.localhost.amazonaws.com",
          "retryable": true,
          "originalError": {
            "message": "getaddrinfo ENOTFOUND dynamodb.localhost.amazonaws.com",
            "errno": "ENOTFOUND",
            "code": "NetworkingError",
            "syscall": "getaddrinfo",
            "hostname": "dynamodb.localhost.amazonaws.com",
            "region": "localhost",
            "retryable": true,
            "time": "2020-02-24T17:24:00.423Z"
          },
          "time": "2020-02-24T17:24:00.423Z",
          "stacktrace": [
            "UnknownEndpoint: Inaccessible host: `dynamodb.localhost.amazonaws.com'. This service may not be available in the `localhost' region.",
            "    at Request.ENOTFOUND_ERROR (C:\\Users\\REMOVED\\Desktop\\Code Playground\\vuejs-lambda\\backend\\node_modules\\aws-sdk\\lib\\event_listeners.js:495:46)",
            "    at Request.callListeners (C:\\Users\\REMOVED\\Desktop\\Code Playground\\vuejs-lambda\\backend\\node_modules\\aws-sdk\\lib\\sequential_executor.js:106:20)",
            "    at Request.emit (C:\\Users\\REMOVED\\Desktop\\Code Playground\\vuejs-lambda\\backend\\node_modules\\aws-sdk\\lib\\sequential_executor.js:78:10)",
            "    at Request.emit (C:\\Users\\REMOVED\\Desktop\\Code Playground\\vuejs-lambda\\backend\\node_modules\\aws-sdk\\lib\\request.js:683:14)",
            "    at ClientRequest.error (C:\\Users\\REMOVED\\Desktop\\Code Playground\\vuejs-lambda\\backend\\node_modules\\aws-sdk\\lib\\event_listeners.js:333:22)",
            "    at ClientRequest.<anonymous> (C:\\Users\\REMOVED\\Desktop\\Code Playground\\vuejs-lambda\\backend\\node_modules\\aws-sdk\\lib\\http\\node.js:96:19)",
            "    at ClientRequest.emit (events.js:210:5)",
            "    at ClientRequest.EventEmitter.emit (domain.js:475:20)",
            "    at TLSSocket.socketErrorListener (_http_client.js:406:9)",
            "    at TLSSocket.emit (events.js:210:5)",
            "    at TLSSocket.EventEmitter.emit (domain.js:475:20)",
            "    at emitErrorNT (internal/streams/destroy.js:92:8)",
            "    at emitErrorAndCloseNT (internal/streams/destroy.js:60:3)",
            "    at processTicksAndRejections (internal/process/task_queues.js:80:21)"
          ]
        }
      }
    }
  ],
  "data": {
    "Koachs": null
  }
}
```

**handler.js:**

```
const { ApolloServer, gql } = require('apollo-server-lambda');
import * as dbKoaches from './dynamo/koach';

const typeDefs = gql`
REMOVED
`;
const resolvers = {
  REMOVED
};

const server = new ApolloServer({
  typeDefs,
  resolvers,
  context: ({ event, context }) => ({
    headers: event.headers,
    functionName: context.functionName,
    event,
    context,
  }),
  playground: true,
  introspection: true,
});

console.log("ServerObject: ", JSON.stringify(server));

exports.graphqlHandler = server.createHandler({
  cors: {
    origin: '*',
    credentials: true,
  },
});

```

Where is that "hostname": "dynamodb.localhost.amazonaws.com" coming from?

Running `sls offline --region eu-central-1` doesn't change a thing.

**Comment by yemi** [comment]
Im getting:
```
"TypeError: utilities_1.getIntrospectionQuery is not a function",
```

Not sure if they're at all related but I'm trying to acheive the same thing.

**Comment by glasser** [comment]
Apollo Server 4 replaces a hard-coded set of web framework integrations with a simple stable API for building integrations. As part of this, the core project no longer directly supports a Lambda integration. Check out the [`@as-integrations/aws-lambda`](https://www.npmjs.com/package/@as-integrations/aws-lambda) package; this new package is maintained by Lambda users and implements support for the API Gateway v1 and v2 protocols. If you need to work with different AWS projects, you may be able to add that support to that package, or take another approach such as combining the [`@vendia/serverless-express`](https://www.npmjs.com/package/@vendia/serverless-express) package with Apollo Server 4's built-in `expressMiddleware` (this is the same approach that `apollo-server-lambda` takes in AS3). Sorry for the delay!
