### ISSUE TITLE
BUG -- Error: Invalid plugin options for hapijs v18.4.1

### ISSUE THREAD

**Issue by jonnydungeons** [apollographql/apollo-server#3928]
When I register graphqlHapi the way your docs suggest here: https://www.apollographql.com/docs/apollo-server/v1/servers/hapi/#usage

WHEN I HAVE THIS: 

```
await Server.register([
        { 
            plugin: Inert,
            options: {}
        },
        {
            plugin: graphqlHapi,
            options: {
                path: '/graphql',
                graphqlOptions: { Schema }
            }
        }
    ]);

```

I GET ERROR: 

```
Error: Invalid plugin options  {
  "plugin": {
    "options": {
      "path": "/graphql",
      "graphqlOptions": {
        "Schema": {
          "__allowedLegacyNames": [],
          "_directives": [
            "@skip",
            "@include",
            "@deprecated"
          ],
          "_typeMap": {
            "__Schema": "__Schema",
            "__Type": "__Type",
            "__TypeKind": "__TypeKind",
            "String": "String",
            "Boolean": "Boolean",
            "__Field": "__Field",
            "__InputValue": "__InputValue",
            "__EnumValue": "__EnumValue",
            "__Directive": "__Directive",
            "__DirectiveLocation": "__DirectiveLocation",
            "Inventory": "Inventory"
          },
          "_possibleTypeMap": {},
          "_implementations": {}
        }
      }
    },
    "register": () => \"\",
    "name" [1]: -- missing --
  }
}

[1] "name" is required
    at Object.exports.apply (/Users/jonortiz/github/toocute/node_modules/@hapi/hapi/lib/config.js:19:15)
    at internals.Server.register (/Users/jonortiz/github/toocute/node_modules/@hapi/hapi/lib/server.js:412:31)
    at async StartServer (/Users/jonortiz/github/toocute/server/server.js:18:5)

```

WHEN I DO THIS ALL IS GOOD:

```
await Server.register([
        { 
            plugin: Inert,
            options: {}
        },
        {
            plugin: graphqlHapi,
            options: {
                path: '/graphql',
                graphqlOptions: { Schema }
            },
            register: () => "what does this do???",
            name: "what is this???"
        }
    ]);

```

**WHERE IN YOUR DOCUMENTATION DO YOU TALK ABOUT register and name keys as being part of the plugin options?**

**Comment by mranosa** [comment]
I get the same error too. Any update on this?

**Comment by glasser** [comment]
Apollo Server 4 now includes a stable API for building web framework integrations instead of directly maintaining a Hapi integration. See https://github.com/apollographql/apollo-server/issues/6028 for discussion on creating a Hapi integration (looks like it's almost done!).
