### ISSUE TITLE
Broken tutorial: getting-started.md

### ISSUE THREAD

**Issue by AasmundEndresen** [apollographql/apollo-server#4268]
Hi - I'm following this tutorial right now on Ubuntu Linux 19.04.

When running `node index.js` after copy+pasting the code from the tutorial (https://www.apollographql.com/docs/apollo-server/getting-started/), I get the following error in console:

```
internal/modules/cjs/loader.js:628
  throw e;
  ^

Error: No valid exports main found for '{project-path}/node_modules/uuid'
    at resolveExportsTarget (internal/modules/cjs/loader.js:625:9)
    at applyExports (internal/modules/cjs/loader.js:502:14)
    at resolveExports (internal/modules/cjs/loader.js:551:12)
    at Function.Module._findPath (internal/modules/cjs/loader.js:657:22)
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:960:27)
    at Function.Module._load (internal/modules/cjs/loader.js:855:27)
    at Module.require (internal/modules/cjs/loader.js:1033:19)
    at require (internal/modules/cjs/helpers.js:72:18)
    at Object.<anonymous> ({project-path}/node_modules/apollo-engine-reporting/dist/agent.js:26:16)
    at Module._compile (internal/modules/cjs/loader.js:1144:30) {
  code: 'MODULE_NOT_FOUND'
}
```
Expected behavior: No errors - server running and available at localhost port 3000,

Reproduction: Not necessary - just copy + paste the code from the tutorial and try to run it, same as I did...

**Comment by calumpeak** [comment]
I'm also getting the same error - is there any update on this?

**Comment by KaesarZ** [comment]
I'm also getting the same error.
node version: v13.6.0
npm version: 6.13.4
yarn version: 1.21.1

**Comment by calumpeak** [comment]
@AasmundEndresen @KaesarZ I found the issue I was having. I was also on Node version v13. Try changing your node version to v12 or v14.
Fixed the issue for me.

**Comment by AasmundEndresen** [comment]
Also on v13.6.0 so that might solve it for me when I get a change to upgrade to 14.

Not sure if I'd call it a solution, because as you said it seemingly broke overnight - but I will do this to be able to keep moving forwards with my projects atleast.

**Comment by KaesarZ** [comment]
Thank you @calumpeak, resolved here by downgrading the node to version v12.18.0

**Comment by glasser** [comment]
Sounds like this was an issue with a particular old version of Node. AS4 requires Node 14, so this shouldn't be a problem.
