### ISSUE TITLE
[apollo-server-fastify]: GraphQL in Vercel does not work

### ISSUE THREAD

**Issue by dalisoft** [apollographql/apollo-server#4338]
### Package version

```bash
@dalisoft/fastify-dev-env@0.1.0 /Users/dalisoft/Desktop/Open_Source/Dev_Env/backend/fastify
├── @rollup/plugin-run@2.0.2
├── apollo-server-fastify@2.15.0
├── ava@3.9.0
├── aws-lambda-fastify@1.4.4
├── bufferutil@4.0.1
├── dotenv-safe@8.2.0
├── eslint@7.3.1
├─┬ UNMET DEPENDENCY fastify@2.15.1
│ ├── abstract-logging@2.0.0
│ ├── ajv@6.12.2 deduped
│ ├── avvio@6.4.1
│ ├── fast-json-stringify@1.20.2
│ ├── find-my-way@2.2.3
│ ├── flatstr@1.0.12
│ ├── light-my-request@3.8.0
│ ├── middie@4.1.0
│ ├── pino@5.17.0
│ ├── proxy-addr@2.0.6
│ ├── readable-stream@3.6.0
│ ├── rfdc@1.1.4
│ ├── secure-json-parse@2.1.0
│ └── tiny-lru@7.0.6
├── fastify-compress@2.0.1
├── fastify-cookie@3.6.1
├── fastify-cors@3.0.3
├── fastify-helmet@3.0.2
├── fastify-jwt@1.4.0
├── fastify-normalize-request-reply@2.2.0
├── fastify-oas@2.7.0
├── fastify-plugin@1.6.1
├── fastify-rate-limit@3.0.1
├── graphql@14.6.0
├── husky@4.2.5
├── lint-staged@10.2.11
├── lodash.pick@4.4.0
├── long@4.0.0
├── netlify-lambda@1.6.3
├── pino-pretty@3.6.1
├── prettier@2.0.5
├── rollup@2.18.1
├── serverless@1.74.0
├── serverless-dotenv-plugin@2.4.2
├── serverless-offline@6.4.0
├── serverless-webpack@5.3.2
├── serverless-websockets-plugin@1.0.0
├── uglify-es@3.3.9
├── utf-8-validate@5.0.2
├── vercel@19.1.1
├── webpack-node-externals@1.7.2
└── ws@7.3.0
```

### Actual behavior

```bash
Unhandled rejection: Error: The type of Mutation.default must be Output Type but got: undefined.
    at assertValidSchema (/Users/dalisoft/Desktop/Open_Source/Dev_Env/backend/fastify/node_modules/graphql/type/validate.js:71:11)
    at assertValidExecutionArguments (/Users/dalisoft/Desktop/Open_Source/Dev_Env/backend/fastify/node_modules/graphql/execution/execute.js:136:35)
    at executeImpl (/Users/dalisoft/Desktop/Open_Source/Dev_Env/backend/fastify/node_modules/graphql/execution/execute.js:86:3)
    at Object.execute (/Users/dalisoft/Desktop/Open_Source/Dev_Env/backend/fastify/node_modules/graphql/execution/execute.js:64:63)
    at Object.generateSchemaHash (/Users/dalisoft/Desktop/Open_Source/Dev_Env/backend/fastify/node_modules/apollo-server-core/src/utils/schemaHash.ts:12:18)
    at ApolloServer.generateSchemaDerivedData (/Users/dalisoft/Desktop/Open_Source/Dev_Env/backend/fastify/node_modules/apollo-server-core/src/ApolloServer.ts:515:24)
    at new ApolloServerBase (/Users/dalisoft/Desktop/Open_Source/Dev_Env/backend/fastify/node_modules/apollo-server-core/src/ApolloServer.ts:369:32)
    at new ApolloServer (/Users/dalisoft/Desktop/Open_Source/Dev_Env/backend/fastify/node_modules/apollo-server-fastify/src/ApolloServer.ts:64:1)
    at /Users/dalisoft/Desktop/Open_Source/Dev_Env/backend/fastify/src/fastify-plugins/fastify-apollo-server.js:7:18
    at step (/Users/dalisoft/Desktop/Open_Source/Dev_Env/backend/fastify/src/fastify-plugins/fastify-apollo-server.js:33:23)
Error! Failed to complete request to /: Error: socket hang up
```

### Excepted behavior

Rendering GraphiQL

### Runnable reproduction

1. Clone [this](https://github.com/dalisoft/dev-env/tree/master/backend/fastify)
2. Run `npm run dev:vercel`
3. Go-to localhost:3000/graphql

**Comment by glasser** [comment]
It looks like you set up your schema in a really complicated way instead of just parsing SDL. I'd recommend setting up your schema without manually building a `GraphQLSchema` object. Did any Apollo Server docs recommend this structure? Sorry for the delay!
