### ISSUE TITLE
Bare minimum Hapi + Apollo server does not work

### ISSUE THREAD

**Issue by jrsmith17** [apollographql/apollo-server#4458]
i am trying to use Hapi and Apollo to create a server that supports both REST and GraphQL. The REST portion is fine, but I ran into issues trying to use Apollo's Hapi hooks. I pared down my schema to a very basic plain old data schema with no resolvers and it still throws and error stating it is `Unable to resolve a valid GraphQLSchema`. This seems unlikely to me. I've posted the code (minus the REST portions) and the error message (minus ID-ing info) below. I've also included the versions I'm using as per my package.json.

```
"apollo-server-hapi": "^2.16.1",
"graphql": "^15.3.0",
"hapi": "^18.1.0",
```

```
'use strict'

const { ApolloServer, gql } = require('apollo-server-hapi');
const Hapi = require('hapi');

const schema = gql`
  type Person {
      firstname: String
      lastname: String
  }
`;

const resolvers = {
};

let init = async () => {
    const apollo = new ApolloServer({ 
        schema:schema, 
        resolvers:resolvers 
    });
    const server = Hapi.server({
        port: Number(process.env.PORT || 8000),
        host: String(process.env.HOST || 'localhost')
    });
    await apollo.applyMiddleware({
        server,
    });

    server.route([
        // .. REST endpoints setup here
    ]);

    await apollo.installSubscriptionHandlers(server.listener);

    try {
        await server.start();
    } 
    catch (err) {
        console.log(`Error while starting server: ${err.message}`);
    }

    console.log('Server running on %s', server.info.uri);
};

process.on('unhandledRejection', (err) => {
    console.log(err);
    process.exit(1);
});

init();
```

```
$ yarn start
yarn run v1.22.4
$ tsc && node ./dist/index.js
Error: Unexpected error: Unable to resolve a valid GraphQLSchema.  Please file an issue with a reproduction of this error, if possible.
    at new ApolloServerBase (/Users/<me>/<project>/node_modules/apollo-server-core/dist/ApolloServer.js:204:19)
    at new ApolloServer (/Users/<me>/<project>/node_modules/apollo-server-hapi/dist/ApolloServer.js:30:1)
    at /Users/<me>/<project>/dist/index.js:23:20
    at Generator.next (<anonymous>)
    at /Users/<me>/<project>/dist/index.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/<me>/<project>/dist/index.js:4:12)
    at init (/Users/<me>/<project>/dist/index.js:22:18)
    at Object.<anonymous> (/Users/<me>/<project>/dist/index.js:71:1)
    at Module._compile (internal/modules/cjs/loader.js:1123:30)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by unzico** [comment]
Have you tried downgrading to graphql v14.x (e.g. v14.7.0)?

**Comment by elskwid** [comment]
@jrsmith17 I just happened to be looking over `hapi`-related issues and saw this. I think you need to modify the arguments to `ApolloServer` to pass `typeDefs` instead of `schema`.


```
const apollo = new ApolloServer({ 
    typeDefs: schema, // this was `schema:schema` in your example code
    resolvers: resolvers 
});
```

**Comment by jrsmith17** [comment]
I happened to have left the position this ticket was for, so I'll close but thanks all for the feedback.
