### ISSUE TITLE
apollo-server-fastify FastifyDeprecation: legacy Content Type Parser function signature

### ISSUE THREAD

**Issue by ZenSoftware** [apollographql/apollo-server#4520]
### System specs
+ Node v14
+ apollo-server-fastify@2.17.0
+ fastify@3.3.0

Relevant info: [Fastify - Changed Content Type Parser syntax](https://github.com/fastify/fastify/blob/master/docs/Migration-Guide-V3.md#changed-content-type-parser-syntax-2286)

**Error log:**
```
(node:3288) [FSTDEP003] FastifyDeprecation: You are using the legacy Content Type Parser function signature. Use the one suggested in the documentation instead.
    at Object.emit (C:\a\Work\zen\node_modules\fastify-warning\index.js:52:13)
    at new Parser (C:\a\Work\zen\node_modules\fastify\lib\contentTypeParser.js:237:13)
    at ContentTypeParser.add (C:\a\Work\zen\node_modules\fastify\lib\contentTypeParser.js:51:18)
    at Object.addContentTypeParser (C:\a\Work\zen\node_modules\fastify\lib\contentTypeParser.js:266:30)
    at ApolloServer.<anonymous> (C:\a\Work\zen\node_modules\apollo-server-fastify\dist\ApolloServer.js:112:30)      
    at Generator.next (<anonymous>)
    at C:\a\Work\zen\node_modules\apollo-server-fastify\dist\ApolloServer.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\a\Work\zen\node_modules\apollo-server-fastify\dist\ApolloServer.js:4:12)
    at app.register.prefix (C:\a\Work\zen\node_modules\apollo-server-fastify\dist\ApolloServer.js:81:40)

(node:3288) [FSTDEP001] FastifyDeprecation: You are accessing the Node.js core request object via "request.req", Use "request.raw" instead.
    at Object.emit (C:\a\Work\zen\node_modules\fastify-warning\index.js:52:13)
    at _Request.get (C:\a\Work\zen\node_modules\fastify\lib\request.js:90:15)
    at Object.<anonymous> (C:\a\Work\zen\node_modules\apollo-server-fastify\dist\fastifyApollo.js:22:37)
    at Generator.next (<anonymous>)
    at C:\a\Work\zen\node_modules\apollo-server-fastify\dist\fastifyApollo.js:8:71
    at new Promise (<anonymous>)
    at __awaiter (C:\a\Work\zen\node_modules\apollo-server-fastify\dist\fastifyApollo.js:4:12)
    at Object.<anonymous> (C:\a\Work\zen\node_modules\apollo-server-fastify\dist\fastifyApollo.js:19:36)
    at preHandlerCallback (C:\a\Work\zen\node_modules\fastify\lib\handleRequest.js:120:28)
    at next (C:\a\Work\zen\node_modules\fastify\lib\hooks.js:158:7)
```

**Comment by hboylan** [comment]
Appears to be fixed in `apollo-server-fastify@next-v3`.
https://github.com/apollographql/apollo-server/pull/4356#issuecomment-677515901

**Comment by SalahAdDin** [comment]
Is there any **ETA** about the new version?

**Comment by DarkPark** [comment]
soon it will be a year

**Comment by glasser** [comment]
Apollo Server 2 does not support Fastify v3. Apollo Server 3 is in active development and does support Fastify v3.

**Comment by DarkPark** [comment]
@glasser the last 3.0.0-alpha.3 was released 9 months ago and last time I'v checked there were some problems

**Comment by glasser** [comment]
You're correct that work on Apollo Server 3 was stalled, but the `release-3.0` branch is under active development now (with new alphas since your comment last week).
