### ISSUE TITLE
Testing with Jest leads to error Unable to resolve a valid GraphQLSchema

### ISSUE THREAD

**Issue by henhen724** [apollographql/apollo-server#4572]
I have been trying to a unit test to a project I'm working on.  It uses typescript and apollo server and client etc.  I use graphql-tools makeExecutableSchema to build my schema.  For the full code you can see my repository https://github.com/henhen724/Wi-DAQ.  This is obviously not a simple error reproduction, but I don't really have time to make one.  Not to mention I have no idea what combination of causes this.

The following is a test file I added
```
import { ApolloServer } from 'apollo-server';
import { createTestClient } from 'apollo-server-testing';
import dotenv from "dotenv";
import mongoose from "mongoose";

let server: any, query: any, mutate: any;
export { server, query, mutate };

const makeTestClient = () => {
    dotenv.config({ path: './.env.local' });
    mongoose.connect(`${process.env.MONGODB_PROTO}${process.env.MONGODB_USERNAME}:${process.env.MONGODB_PASSWORD}@${process.env.MONGODB_DOMAIN}`, { useNewUrlParser: true, useUnifiedTopology: true });
    const schema = require("../server/apollo/schema");
    server = new ApolloServer({
        schema,
        context: (ctx) => {
            return {
                session: { id: '1', email: 'test@beep.com' },
                req: ctx.req,
                res: ctx.res,
            }
        },
    })
    const rslt = createTestClient(server);
    query = rslt.query;
    mutate = rslt.mutate;
}

beforeAll(makeTestClient);

it('test client starts up', () => {
    expect(server).toBeDefined();
    expect(query).toBeDefined();
    expect(mutate).toBeDefined();
})
```

When I run this I get the following error:

```
test client starts up

    Unexpected error: Unable to resolve a valid GraphQLSchema.  Please file an issue with a reproduction of this error, if possible.

      14 |     mongoose.connect(`${process.env.MONGODB_PROTO}${process.env.MONGODB_USERNAME}:${process.env.MONGODB_PASSWORD}@${process.env.MONGODB_DOMAIN}`, { useNewUrlParser: true, useUnifiedTopology: true });
      15 |     const schema = require("../server/apollo/schema");
    > 16 |     server = new ApolloServer({
         |              ^
      17 |         schema,
      18 |         context: (ctx) => {
      19 |             return {

      at new ApolloServerBase (node_modules/apollo-server-core/src/ApolloServer.ts:381:13)
      at new ApolloServer (node_modules/apollo-server-express/src/ApolloServer.ts:88:5)
      at new ApolloServer (node_modules/apollo-server/src/index.ts:36:5)
      at Object.makeTestClient (__tests__/makeTestClient.ts:16:14)

```

**Comment by henhen724** [comment]
I ended up switching from graphql-tool to type-graphql and that fix fixed this for what ever reason.  If the apollo-server team is still interested in this error, this link https://github.com/henhen724/Wi-DAQ/tree/181470661b9b8c3b507907966f1c18d1f066ee99 can reproduce it.

**Comment by glasser** [comment]
We removed that particular error in Apollo Server v2.22 which was the first of several steps towards having a simpler and more consistent server lifecycle.
