### ISSUE TITLE
Graphql Subscriptions: resolveFn is not a function

### ISSUE THREAD

**Issue by nunovieira220** [apollographql/apollo-server#4606]
I am trying to implement a simple Graphql subscription example and, after connecting to the server, all I am getting as a result is the following error:

```json
{
  "errors": [
    {
      "message": "resolveFn is not a function",
      "locations": [
        {
          "line": 2,
          "column": 3
        }
      ],
      "path": [
        "newPost"
      ],
      "extensions": {
        "code": "INTERNAL_SERVER_ERROR",
        "exception": {
          "stacktrace": [
            "TypeError: resolveFn is not a function",
            "    at resolveFieldValueOrError (/Users/nunovieira/git/projects/koa-with-graphql-subscriptions/node_modules/graphql/execution/execute.js:467:18)",
            "    at createSourceEventStream (/Users/nunovieira/git/projects/koa-with-graphql-subscriptions/node_modules/graphql/subscription/subscribe.js:153:56)",
            "    at subscribeImpl (/Users/nunovieira/git/projects/koa-with-graphql-subscriptions/node_modules/graphql/subscription/subscribe.js:67:23)",
            "    at subscribe (/Users/nunovieira/git/projects/koa-with-graphql-subscriptions/node_modules/graphql/subscription/subscribe.js:30:65)",
            "    at /Users/nunovieira/git/projects/koa-with-graphql-subscriptions/node_modules/subscriptions-transport-ws/src/server.ts:359:52",
            "    at process._tickCallback (internal/process/next_tick.js:68:7)"
          ]
        }
      }
    }
  ]
}
```

I am using `apollo-server-koa` node package on the `2.18.0` version but I've tried with the same version of the base `apollo-server` package too.

Next there is some code snippets of the server initialization, integration with Koa server and a client example:

```js
// Server initialization
const graphqlApolloServer = new ApolloServer({
  context: async ({ ctx, connection }) => {
      return connection ? connection.context : ctx;
  },
  debug: true,
  schema: makeExecutableSchema({
    resolverValidationOptions: { requireResolversForResolveType: false },
    resolvers: [postResolver],
    typeDefs: [postSchema]
  }),
  subscriptions: { path: "/subscriptions" }
});
```

```js
// Integration with Koa server
const httpServer = app.listen('3000', () => console.log(`Server is listening on port 3000`));
graphqlApolloServer.applyMiddleware({ app, path: '/graphql' });
graphqlApolloServer.installSubscriptionHandlers(httpServer);
```

```js
// Client example using Apollo Client
const link = new WebSocketLink({
    uri: `ws://localhost:3000/subscriptions`,
    options: { reconnect: true },
    webSocketImpl: ws
  });

const client = new ApolloClient({ cache: new InMemoryCache(), link });

client.subscribe({
  query: gql`
    subscription {
      newPost {
        id
      }
    }
  `
}).subscribe({
  next: data => console.log(require('util').inspect(data, { depth: null })),
  error: err => console.log(require('util').inspect(err, { depth: null })),
  complete: () => console.log('Done')
});
```

I created a Github repository with 2 different clients that allow you to easily reproduce the error above: [here](https://github.com/nunovieira220/koa-with-graphql-subscriptions). You can also reproduce it via Graphql Apollo Server provided UI client.

**Comment by chen572** [comment]
all you need to do is to turn the subscribe in Subscription in your post-resolver into a function 
like so:
`  
Subscription: {
    newPost: {
      resolve: ({ newPost }) => newPost,
      subscribe: () => pubsub.asyncIterator(topic)
    }
  }
`

**Comment by nunovieira220** [comment]
@chen572 thank you, you're right, it solved the problem. I guess I tried so many different things, I probably solved one problem and created that one.

I am closing the issue, thanks again!
