### ISSUE TITLE
Remove excessive warning re graph variant still spamming test?

### ISSUE THREAD

**Issue by xenoterracide** [apollographql/apollo-server#4652]
I found this PR, which suggests this should be fixed but I'm still getting a warning  every time my test context spins up, doing a source dive, it appears that it's because this warning is set when `APOLLO_KEY` is set in the environment, even when engine is set to false.

https://github.com/apollographql/apollo-server/pull/3043

```
➤ YN0000: [@bb/graph]:       No graph variant provided. Defaulting to `current`.
➤ YN0000: [@bb/graph]: 
➤ YN0000: [@bb/graph]:       10 | export const TestClientConfig = [
➤ YN0000: [@bb/graph]:       11 |   Registration.cachedCallback(ApolloServer, (c) => ***
➤ YN0000: [@bb/graph]:     > 12 |     return new ApolloServer(*** ...c.get(ApolloServerConfig), engine: false ***);
➤ YN0000: [@bb/graph]:          |            ^
➤ YN0000: [@bb/graph]:       13 |   ***),
➤ YN0000: [@bb/graph]:       14 |   Registration.cachedCallback(TestClient, (c) => createTestClient(c.get(ApolloServer))),
➤ YN0000: [@bb/graph]:       15 | ];
➤ YN0000: [@bb/graph]: 
➤ YN0000: [@bb/graph]:       at Object.determineApolloConfig (../.yarn/$$virtual/apollo-server-core-virtual-d0f952ada2/0/cache/apollo-server-core-npm-2.18.2-6498354fe6-c4374b24ca.zip/node_modules/apollo-server-core/src/determineApolloConfig.ts:107:12)
➤ YN0000: [@bb/graph]:       at new ApolloServerBase (../.yarn/$$virtual/apollo-server-core-virtual-d0f952ada2/0/cache/apollo-server-core-npm-2.18.2-6498354fe6-c4374b24ca.zip/node_modules/apollo-server-core/src/ApolloServer.ts:213:25)
➤ YN0000: [@bb/graph]:       at new ApolloServer (../.yarn/$$virtual/apollo-server-express-virtual-29824d2776/0/cache/apollo-server-express-npm-2.18.2-772b669727-ebcb732409.zip/node_modules/apollo-server-express/src/ApolloServer.ts:88:5)
➤ YN0000: [@bb/graph]:       at graph/package
```
here's all of my deps that matter
```
yarn info -A 'apollo-*'
├─ apollo-cache-control@npm:0.11.3
│  ├─ Instances: 1
│  ├─ Version: 0.11.3
│  │
│  └─ Dependencies
│     ├─ apollo-server-env@npm:^2.4.5 → npm:2.4.5
│     └─ apollo-server-plugin-base@npm:^0.10.1 → npm:0.10.1
│
├─ apollo-datasource@npm:0.7.2
│  ├─ Version: 0.7.2
│  │
│  └─ Dependencies
│     ├─ apollo-server-caching@npm:^0.5.2 → npm:0.5.2
│     └─ apollo-server-env@npm:^2.4.5 → npm:2.4.5
│
├─ apollo-env@npm:0.6.5
│  ├─ Version: 0.6.5
│  │
│  └─ Dependencies
│     ├─ @types/node-fetch@npm:2.5.7 → npm:2.5.7
│     ├─ core-js@npm:^3.0.1 → npm:3.6.5
│     ├─ node-fetch@npm:^2.2.0 → npm:2.6.0
│     └─ sha.js@npm:^2.4.11 → npm:2.4.11
│
├─ apollo-graphql@npm:0.6.0
│  ├─ Instances: 1
│  ├─ Version: 0.6.0
│  │
│  └─ Dependencies
│     ├─ apollo-env@npm:^0.6.5 → npm:0.6.5
│     └─ lodash.sortby@npm:^4.7.0 → npm:4.7.0
│
├─ apollo-link@npm:1.2.14
│  ├─ Instances: 1
│  ├─ Version: 1.2.14
│  │
│  └─ Dependencies
│     ├─ apollo-utilities@npm:^1.3.0 → npm:1.3.4
│     ├─ ts-invariant@npm:^0.4.0 → npm:0.4.4
│     ├─ tslib@npm:^1.9.3 → npm:1.13.0
│     └─ zen-observable-ts@npm:^0.8.21 → npm:0.8.21
│
├─ apollo-reporting-protobuf@npm:0.6.0
│  ├─ Version: 0.6.0
│  │
│  └─ Dependencies
│     ├─ @apollo/protobufjs@npm:^1.0.3 → npm:1.0.5
│     ├─ @types/long@npm:^4 → npm:4.0.1
│     └─ long@npm:^4 → npm:4.0.0
│
├─ apollo-server-caching@npm:0.5.2
│  ├─ Version: 0.5.2
│  │
│  └─ Dependencies
│     └─ lru-cache@npm:^5.0.0 → npm:5.1.1
│
├─ apollo-server-core@npm:2.18.2
│  ├─ Instances: 1
│  ├─ Version: 2.18.2
│  │
│  └─ Dependencies
│     ├─ @apollographql/apollo-tools@npm:^0.4.3 → npm:0.4.8
│     ├─ @apollographql/graphql-playground-html@npm:1.6.26 → npm:1.6.26
│     ├─ @types/graphql-upload@npm:^8.0.0 → npm:8.0.3
│     ├─ @types/ws@npm:^7.0.0 → npm:7.2.6
│     ├─ apollo-cache-control@npm:^0.11.3 → npm:0.11.3
│     ├─ apollo-datasource@npm:^0.7.2 → npm:0.7.2
│     ├─ apollo-graphql@npm:^0.6.0 → npm:0.6.0
│     ├─ apollo-reporting-protobuf@npm:^0.6.0 → npm:0.6.0
│     ├─ apollo-server-caching@npm:^0.5.2 → npm:0.5.2
│     ├─ apollo-server-env@npm:^2.4.5 → npm:2.4.5
│     ├─ apollo-server-errors@npm:^2.4.2 → npm:2.4.2
│     ├─ apollo-server-plugin-base@npm:^0.10.1 → npm:0.10.1
│     ├─ apollo-server-types@npm:^0.6.0 → npm:0.6.0
│     ├─ apollo-tracing@npm:^0.11.4 → npm:0.11.4
│     ├─ async-retry@npm:^1.2.1 → npm:1.3.1
│     ├─ fast-json-stable-stringify@npm:^2.0.0 → npm:2.1.0
│     ├─ graphql-extensions@npm:^0.12.5 → npm:0.12.5
│     ├─ graphql-tag@npm:^2.9.2 → npm:2.11.0
│     ├─ graphql-tools@npm:^4.0.0 → npm:4.0.8
│     ├─ graphql-upload@npm:^8.0.2 → npm:8.1.0
│     ├─ loglevel@npm:^1.6.7 → npm:1.7.0
│     ├─ lru-cache@npm:^5.0.0 → npm:5.1.1
│     ├─ sha.js@npm:^2.4.11 → npm:2.4.11
│     ├─ subscriptions-transport-ws@npm:^0.9.11 → npm:0.9.18
│     ├─ uuid@npm:^8.0.0 → npm:8.3.0
│     └─ ws@npm:^6.0.0 → npm:6.2.1
│
├─ apollo-server-env@npm:2.4.5
│  ├─ Version: 2.4.5
│  │
│  └─ Dependencies
│     ├─ node-fetch@npm:^2.1.2 → npm:2.6.0
│     └─ util.promisify@npm:^1.0.0 → npm:1.0.1
│
├─ apollo-server-errors@npm:2.4.2
│  ├─ Instances: 1
│  └─ Version: 2.4.2
│
├─ apollo-server-express@npm:2.18.2
│  ├─ Instances: 1
│  ├─ Version: 2.18.2
│  │
│  └─ Dependencies
│     ├─ @apollographql/graphql-playground-html@npm:1.6.26 → npm:1.6.26
│     ├─ @types/accepts@npm:^1.3.5 → npm:1.3.5
│     ├─ @types/body-parser@npm:1.19.0 → npm:1.19.0
│     ├─ @types/cors@npm:2.8.7 → npm:2.8.7
│     ├─ @types/express-serve-static-core@npm:4.17.9 → npm:4.17.9
│     ├─ @types/express@npm:4.17.7 → npm:4.17.7
│     ├─ accepts@npm:^1.3.5 → npm:1.3.7
│     ├─ apollo-server-core@npm:^2.18.2 → npm:2.18.2
│     ├─ apollo-server-types@npm:^0.6.0 → npm:0.6.0
│     ├─ body-parser@npm:^1.18.3 → npm:1.19.0
│     ├─ cors@npm:^2.8.4 → npm:2.8.5
│     ├─ express@npm:^4.17.1 → npm:4.17.1
│     ├─ graphql-subscriptions@npm:^1.0.0 → npm:1.1.0
│     ├─ graphql-tools@npm:^4.0.0 → npm:4.0.8
│     ├─ parseurl@npm:^1.3.2 → npm:1.3.3
│     ├─ subscriptions-transport-ws@npm:^0.9.16 → npm:0.9.18
│     └─ type-is@npm:^1.6.16 → npm:1.6.18
│
├─ apollo-server-plugin-base@npm:0.10.1
│  ├─ Instances: 1
│  ├─ Version: 0.10.1
│  │
│  └─ Dependencies
│     └─ apollo-server-types@npm:^0.6.0 → npm:0.6.0
│
├─ apollo-server-plugin-response-cache@npm:0.5.5
│  ├─ Instances: 1
│  ├─ Version: 0.5.5
│  │
│  └─ Dependencies
│     ├─ apollo-cache-control@npm:^0.11.3 → npm:0.11.3
│     ├─ apollo-server-caching@npm:^0.5.2 → npm:0.5.2
│     ├─ apollo-server-plugin-base@npm:^0.10.1 → npm:0.10.1
│     └─ apollo-server-types@npm:^0.6 → npm:0.6.0
│
├─ apollo-server-testing@npm:2.18.2
│  ├─ Instances: 1
│  ├─ Version: 2.18.2
│  │
│  └─ Dependencies
│     ├─ apollo-server-core@npm:^2.18.2 → npm:2.18.2
│     └─ apollo-server-types@npm:^0.6 → npm:0.6.0
│
├─ apollo-server-types@npm:0.6.0
│  ├─ Instances: 1
│  ├─ Version: 0.6.0
│  │
│  └─ Dependencies
│     ├─ apollo-reporting-protobuf@npm:^0.6.0 → npm:0.6.0
│     ├─ apollo-server-caching@npm:^0.5.2 → npm:0.5.2
│     └─ apollo-server-env@npm:^2.4.5 → npm:2.4.5
│
├─ apollo-tracing@npm:0.11.4
│  ├─ Instances: 1
│  ├─ Version: 0.11.4
│  │
│  └─ Dependencies
│     ├─ apollo-server-env@npm:^2.4.5 → npm:2.4.5
│     └─ apollo-server-plugin-base@npm:^0.10.1 → npm:0.10.1
│
└─ apollo-utilities@npm:1.3.4
   ├─ Instances: 1
   ├─ Version: 1.3.4
   │
   └─ Dependencies
      ├─ @wry/equality@npm:^0.1.2 → npm:0.1.11
      ├─ fast-json-stable-stringify@npm:^2.0.0 → npm:2.1.0
      ├─ ts-invariant@npm:^0.4.0 → npm:0.4.4
      └─ tslib@npm:^1.10.0 → npm:1.13.0
```

**Comment by glasser** [comment]
This warning no longer exists in Apollo Server 3. (We don't fall back to `current`; in fact, we don't track "variant" as its own thing any more, but instead just send a "graph ref" to studio that can elide the default variant if it wants.)
