### ISSUE TITLE
Error: Can't set headers after they are sent

### ISSUE THREAD

**Issue by joncursi** [apollographql/apollo-server#471]
Every time I make a graphql query from my client, the server console outputs:

```
UnhandledPromiseRejectionWarning: Unhandled promise rejection (rejection id: 32): Error: Can't set headers after they are sent.
```

The data arrives fine on the client, but I keep getting this error spit out on the server console. It only happens on graphql queries (I'm using Apollo client and Apollo server). I'm not sure where to start since there is no stack trace, so I figured I would start here and see if anyone has any ideas on what's going on!

```
    "graphql": "0.10.5",
    "graphql-date": "^1.0.3",
    "graphql-loader": "^1.2.1",
    "graphql-log": "^0.1.3",
    "graphql-redis-subscriptions": "^1.2.0",
    "graphql-server-express": "^1.0.2",
    "graphql-subscriptions": "^0.4.4",
    "graphql-tools": "^1.0.0",
    "graphql-type-json": "^0.1.4",
```

My server is a Meteor app @ `METEOR@1.6-beta.4` and using the `meteor/apollo` integration, so the graphql server is based on express.

**Comment by cfnelson** [comment]
@joncursi I was having a similar issue `Error: Can't set headers after they are sent.` after clearing my `node_modules` and reinstalling.

I was able to resolve it by installing `"graphql-server-express": "1.0.0",`. Something is breaking on  `"graphql-server-express": "1.0.2",` for me.

**Comment by mklopets** [comment]
Can you provide a reduced test case for your setup that throws this error?

**Comment by VladDubrovskis** [comment]
We run into similar issue and rolled back to v1.0.0 for now. It seems to be caused by this change:
https://github.com/apollographql/apollo-server/commit/3d03295974f08ccf917cfc2e06122eb328b204ab#diff-93774063e5fc49e60474cd9b82249731

Our use case that was breaking, is that we had a 404 middleware, however as res.end() was called by GraphQL, the 404 middleware was throwing error.

In theory, any middleware that you try to apply to all requests that might be modifying headers will be break

**Comment by ArnaudRinquin** [comment]
Our app spits the same error after upgrading to 1.0.2 but, surprisingly, it does not break anything.

Here is the stack-trace:

```
Error: Can't set headers after they are sent.
  at validateHeader (_http_outgoing.js:504:11)
  at ServerResponse.setHeader (_http_outgoing.js:511:3)
  at ServerResponse.header (/tmp/node_modules/express/lib/response.js:719:10)
  at ServerResponse.send (/tmp/node_modules/express/lib/response.js:164:12)
  at ServerResponse.json (/tmp/node_modules/express/lib/response.js:250:15)
  at ServerResponse.send (/tmp/node_modules/express/lib/response.js:152:21)
  at /app/src/app.js:82:9
  at Layer.handle_error (/tmp/node_modules/express/lib/router/layer.js:71:5)
  at trim_prefix (/tmp/node_modules/express/lib/router/index.js:310:13)
  at /tmp/node_modules/express/lib/router/index.js:280:7
  at Function.process_params (/tmp/node_modules/express/lib/router/index.js:330:12)
  at next (/tmp/node_modules/express/lib/router/index.js:271:10)
  at /app/src/app.js:75:5
  at Layer.handle [as handle_request] (/tmp/node_modules/express/lib/router/layer.js:95:5)
  at trim_prefix (/tmp/node_modules/express/lib/router/index.js:312:13)
  at /tmp/node_modules/express/lib/router/index.js:280:7
  at Function.process_params (/tmp/node_modules/express/lib/router/index.js:330:12)
  at next (/tmp/node_modules/express/lib/router/index.js:271:10)
  at /tmp/node_modules/express/lib/router/index.js:618:15
  at next (/tmp/node_modules/express/lib/router/index.js:256:14)
  at /tmp/node_modules/apollo-server-express/dist/expressApollo.js:22:13
  at <anonymous>
```

Meaningful versions:

```
body-parser: "1.15.2"
dataloader: "^1.3.0"
debug: "^2.2.0"
express: "4.14.0"
express-graphql: "^0.6.6"
graphql: "^0.10.5"
graphql-redis-subscriptions-async-iterator: "^1.2.0"
graphql-server-express: "^1.0.0"
graphql-subscriptions: "^0.4.4"
graphql-tools: "^1.1.0"
graphql-type-json: "^0.1.4"
morgan: "1.7.0"
optics-agent: "^1.1.6"
request: "2.77.0"
subscriptions-transport-ws: "^0.8.1"
```

**Comment by goldo** [comment]
same for us here ! Thanks the tip

**Comment by Friss** [comment]
Here's a small example of the error. Any middleware after the your GraphQL endpoint will hit, such as 404 / error handlers. These handlers are also generated part of the express generator. 

https://gist.github.com/Friss/90604b5f53ad4bb38146a8f49c730c13

**Comment by freiksenet** [comment]
We've reverted the patch that caused the problems. I'm very sorry for any inconvinience!

**Comment by frederikhors** [comment]
The problem is still there: https://github.com/apollographql/apollo-server/issues/1523

Any hint?

**Comment by FinnFrotscher** [comment]
+1

**Comment by StupidSexyJake** [comment]
+1 same issue here

**Comment by arvi** [comment]
Same issue. https://stackoverflow.com/questions/58321093/graphql-clearing-session-cookie-results-to-cannot-set-headers-after-they-are-sen

**Comment by dayrim** [comment]
Same here https://github.com/jkettmann/graphql-passport/issues/36

**Comment by gaurav-bothra** [comment]
+1 same issue here
#4527

**Comment by marcoantoniocanhas** [comment]
+1

**Comment by grantmontgomery** [comment]
Same issue too I'm trying to write a "Set-Cookie" header in my response object after logging in a user.

**Comment by alicerocheman** [comment]
Still encountering this issue.
The app works, but my server console keeps giving me this error.
Specifically:

```
[1] error - Error: write EPIPE
[1] error - Error: read ECONNRESET
[1] Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
[1]     at new NodeError (node:internal/errors:371:5)
[1]     at ServerResponse.setHeader (node:_http_outgoing:576:11)
[1]     at NodeNextResponse.setHeader (/Users/username/Dev/project/front/app/node_modules/next/dist/server/base-http/node.js:56:19)
[1]     at DevServer.renderError (/Users/username/Dev/project/front/app/node_modules/next/dist/server/base-server.js:1134:17)
[1]     at DevServer.renderError (/Users/username/Dev/project/front/app/node_modules/next/dist/server/next-server.js:493:22)
[1]     at DevServer.run (/Users/username/Dev/project/front/app/node_modules/next/dist/server/dev/next-dev-server.js:452:35)
[1]     at processTicksAndRejections (node:internal/process/task_queues:96:5)
[1]     at async DevServer.handleRequest (/Users/username/Dev/project/front/app/node_modules/next/dist/server/base-server.js:307:20) {
[1]   code: 'ERR_HTTP_HEADERS_SENT'
[1] }
```

**Comment by glasser** [comment]
@alicerocheman Sorry you're running into this, but we won't be able to help without a full reproduction recipe that lets us see it ourselves without any creativity (eg, something starting with `git clone` or using codesandbox.io). It's probably a subtle interplay between NextJS, Apollo Server, and your own app code.

**Comment by leonard-henriquez** [comment]
I found various examples of this error using different frameworks (Express, Next.js, NestJS).
All examples use Apollo server:

- https://gist.github.com/Friss/90604b5f53ad4bb38146a8f49c730c13
- https://github.com/apollographql/apollo-server/issues/4527
- https://github.com/supertokens/supertokens-node/issues/331

Is this enough to investigate this issue @glasser ?

**Comment by glasser** [comment]
No, we really need to be given an example that we can run without creativity and see exactly what's happening.

It sounds like the common thread involves doing some sort of error handling that sends a response; perhaps the error handling is firing in cases where the response has already been sent?
