### ISSUE TITLE
Use of `res.end` is preventing other middleware from completing in Node

### ISSUE THREAD

**Issue by davedash** [apollographql/apollo-server#5053]
I'm running into an issue where I use `express-openid-connect` and both that package and ApolloServer conflict:

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at new NodeError (node:internal/errors:329:5)
    at ServerResponse.setHeader (node:_http_outgoing:573:11)
    at ServerResponse.header (/Users/davedash/Projects/backend/node_modules/express/lib/response.js:771:10)
    at ServerResponse.append (/Users/davedash/Projects/backend/node_modules/express/lib/response.js:732:15)
    at ServerResponse.res.cookie (/Users/davedash/Projects/backend/node_modules/express/lib/response.js:857:8)
    at setCookie (/Users/davedash/Projects/backend/node_modules/express-openid-connect/lib/appSession.js:135:13)
    at CookieStore.set (/Users/davedash/Projects/backend/node_modules/express-openid-connect/lib/appSession.js:150:7)
    at ServerResponse.resEnd [as end] (/Users/davedash/Projects/backend/node_modules/express-openid-connect/lib/appSession.js:295:21)
    at /Users/davedash/Projects/backend/node_modules/apollo-server-express/dist/ApolloServer.js:135:25
    at Layer.handle [as handle_request] (/Users/davedash/Projects/backend/node_modules/express/lib/router/layer.js:95:5)
```

Not 100% sure what's happening, but it seems like some cookies are trying to be set by `express-openid-connect` and maybe that middleware is running at the same time as the playground code.  So when we get to here:

https://github.com/apollographql/apollo-server/blob/a3282a2d7df0c20d9e10b058defae835120fa5b1/packages/apollo-server-express/src/ApolloServer.ts#L202

We end the response and express gives us the above error.

I was able to temporarily fix this by changing that line to `res.send(playground)` and removing the `res.write` and `res.end` calls.

Unfortunately, since I don't know what's really happening, I don't feel confident publishing that as a pull request - and I'm wondering if there's a better way to handle this.

**Comment by glasser** [comment]
It sounds like perhaps the way you've integrated express-openid-connect and apollo-server-express conflict with each other? Perhaps you need to make sure that the other package runs before Apollo Server or only when Apollo Server handlers aren't running? I won't be able to help debug without actually being able to reproduce the issue on my own machine. I'll be happy to reopen this issue if you provide a full reproduction that doesn't require me to be creative at all to try it out: a series of instructions (probably including `git clone` or using something on codesandbox.io) that shows the issue to me.

**Comment by davedash** [comment]
@glasser you rock.  

I'm posting this - just on the off chance someone runs into the same issues as I.

1. I created the code sandbox per your suggestion.  The minimal implementation I thought should fail, did not.
2. So I pulled that all into my own repo and of course it failed for me.
3. So I dug into the details, and it seemed some packages were slightly different.
4. Upgraded a few packages via yarn
5. It works locally.

Thanks for the suggestion, it really helped me narrow it down quickly.

**Comment by davedash** [comment]
@glasser I spoke too soon.  

I think there is some underlying package that is making this not work correctly, but I'm stumped.  but I did manage to break the code sandbox version:

Here's what I got.  https://codesandbox.io/s/sad-wave-epfg9?file=/src/index.js

I did need to log into auth0 with a google email address (I'm sure something else will do, but ultimately I needed a cookies present).

I did that by going here: https://epfg9.sse.codesandbox.io/login

When that set the cookie that triggered something in the sandbox's terminal:

```
Error [ERR_HTTP_HEADERS_SENT]: Cannot set headers after they are sent to the client
    at ServerResponse.setHeader (_http_outgoing.js:470:11)
    at ServerResponse.header (/sandbox/node_modules/express/lib/response.js:771:10)
    at ServerResponse.append (/sandbox/node_modules/express/lib/response.js:732:15)
    at ServerResponse.res.cookie (/sandbox/node_modules/express/lib/response.js:857:8)
    at setCookie (/sandbox/node_modules/express-openid-connect/lib/appSession.js:135:13)
    at CookieStore.set (/sandbox/node_modules/express-openid-connect/lib/appSession.js:150:7)
    at ServerResponse.resEnd (/sandbox/node_modules/express-openid-connect/lib/appSession.js:295:21)
    at router.use (/sandbox/node_modules/apollo-server-express/dist/ApolloServer.js:135:25)
    at Layer.handle [as handle_request] (/sandbox/node_modules/express/lib/router/layer.js:95:5)
```

**Comment by glasser** [comment]
Looks like it's this bug in express-openid-connect: https://github.com/auth0/express-openid-connect/issues/204

Looks like they add a hook to response.end() which tries to write a set-cookie, which is certainly too late because end comes after writing the body!

**Comment by davedash** [comment]
@glasser Oh, that's amazing - thanks for finding that for me.  I ended up doing something gross to work around it.
