### ISSUE TITLE
TypeError : Cannot use 'in' operator to search for 'httpMethod' in - Barebones project with Serverless Framework

### ISSUE THREAD

**Issue by tate2301** [apollographql/apollo-server#5129]
Getting a TypeError trying to run graphql on serverless framework - Cannot use 'in' operator to search for 'httpMethod' in

Enviroment
```
Your Environment Information ---------------------------
     Operating System:          darwin
     Node Version:              14.16.0
     Framework Version:         1.83.3 (local)
     Plugin Version:            3.8.4
     SDK Version:               2.3.2
     Components Version:        2.34.9
```

handler.ts
```
const { ApolloServer, gql } = require('apollo-server-lambda');

// Construct a schema, using GraphQL schema language
const typeDefs = someTypeDef // This is just some basic type definitions

// Provide resolver functions for your schema fields
const resolvers = {
  Query: {
    hello: () => 'Hello world!',
  },
};

const server = new ApolloServer({ typeDefs, resolvers });

exports.graphqlHandler = server.createHandler();

```
serverless.yml
```
service:
  name: ekpen-api-graphql

plugins:
  - serverless-dotenv-plugin
  - serverless-offline
  - serverless-plugin-typescript

provider:
  name: aws
  runtime: nodejs12.x

functions:
  graphql:
    handler: src/handler.graphqlHandler
    events:
    - http:
        path: graphql
        method: post
        cors: true
    - http:
        path: graphql
        method: get
        cors: true
```

Stacktrace
```
Serverless: Deprecation warning: Detected ".env" files. In the next major release variables from ".env" files will be automatically loaded into the serverless build process. Set "useDotenv: true" to adopt that behavior now.
            More Info: https://www.serverless.com/framework/docs/deprecations/#LOAD_VARIABLES_FROM_ENV_FILES
Serverless: Running "serverless" installed locally (in service node_modules)
Serverless: DOTENV: Loading environment variables from .env:
Serverless: Compiling with Typescript...
Serverless: Using local tsconfig.json
Serverless: Typescript compiled.
{
    "errorMessage": "Cannot use 'in' operator to search for 'httpMethod' in ",
    "errorType": "TypeError",
    "stackTrace": [
        "TypeError: Cannot use 'in' operator to search for 'httpMethod' in ",
        "    at eventHttpMethod (/Users/mac/work/tachom/ekpenmedia/api/.build/node_modules/apollo-server-lambda/src/ApolloServer.ts:33:22)",
        "    at ApolloServer.<anonymous> (/Users/mac/work/tachom/ekpenmedia/api/.build/node_modules/apollo-server-lambda/src/ApolloServer.ts:226:13)",
        "    at Generator.next (<anonymous>)",
        "    at /Users/mac/work/tachom/ekpenmedia/api/.build/node_modules/apollo-server-lambda/dist/ApolloServer.js:8:71",
        "    at new Promise (<anonymous>)",
        "    at __awaiter (/Users/mac/work/tachom/ekpenmedia/api/.build/node_modules/apollo-server-lambda/dist/ApolloServer.js:4:12)",
        "    at /Users/mac/work/tachom/ekpenmedia/api/.build/node_modules/apollo-server-lambda/src/ApolloServer.ts:180:43",
        "    at /Users/mac/work/tachom/ekpenmedia/api/.build/node_modules/apollo-server-lambda/src/ApolloServer.ts:95:7",
        "    at /Users/mac/work/tachom/ekpenmedia/api/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:867:30",
        "    at Promise._execute (/Users/mac/work/tachom/ekpenmedia/api/node_modules/bluebird/js/release/debuggability.js:384:9)",
        "    at Promise._resolveFromExecutor (/Users/mac/work/tachom/ekpenmedia/api/node_modules/bluebird/js/release/promise.js:518:18)",
        "    at new Promise (/Users/mac/work/tachom/ekpenmedia/api/node_modules/bluebird/js/release/promise.js:103:10)",
        "    at AwsInvokeLocal.invokeLocalNodeJs (/Users/mac/work/tachom/ekpenmedia/api/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:820:12)",
        "    at AwsInvokeLocal.invokeLocal (/Users/mac/work/tachom/ekpenmedia/api/node_modules/serverless/lib/plugins/aws/invokeLocal/index.js:228:19)",
        "    at AwsInvokeLocal.tryCatcher (/Users/mac/work/tachom/ekpenmedia/api/node_modules/bluebird/js/release/util.js:16:23)",
        "    at Promise._settlePromiseFromHandler (/Users/mac/work/tachom/ekpenmedia/api/node_modules/bluebird/js/release/promise.js:547:31)",
        "    at Promise._settlePromise (/Users/mac/work/tachom/ekpenmedia/api/node_modules/bluebird/js/release/promise.js:604:18)",
        "    at Promise._settlePromiseCtx (/Users/mac/work/tachom/ekpenmedia/api/node_modules/bluebird/js/release/promise.js:641:10)",
        "    at _drainQueueStep (/Users/mac/work/tachom/ekpenmedia/api/node_modules/bluebird/js/release/async.js:97:12)",
        "    at _drainQueue (/Users/mac/work/tachom/ekpenmedia/api/node_modules/bluebird/js/release/async.js:86:9)",
        "    at Async._drainQueues (/Users/mac/work/tachom/ekpenmedia/api/node_modules/bluebird/js/release/async.js:102:5)",
        "    at Immediate.Async.drainQueues (/Users/mac/work/tachom/ekpenmedia/api/node_modules/bluebird/js/release/async.js:15:14)",
        "    at processImmediate (internal/timers.js:461:21)"
    ]
}
```

**Comment by thetwit4u** [comment]
What caused the error ?  I've the same issue ?
