### ISSUE TITLE
Support for Webtask.io

### ISSUE THREAD

**Issue by loremaps** [apollographql/apollo-server#513]
I know [launchpad](https://github.com/apollographql/launchpad) is using webtasks internally to provide the serverless graphQL functionality. Apollo server has variants for AWS lambda, micro and Azure functions but not for webtasks.
Here is my attempt to run the express variant on webtasks.io:

```
var express = require('express');
var Webtask = require('webtask-tools');
var bodyParser = require('body-parser');
var tools = require('graphql-tools');
var graphqlExpress = require('apollo-server-express').graphqlExpress;
var graphiqlExpress = require('apollo-server-express').graphiqlExpress;


var app = express();

app.use(bodyParser.urlencoded({ extended: true }))
app.use(bodyParser.json());

// Construct a schema, using GraphQL schema language
var rootSchema = `
type Query {
  hello: String
}
`;

// Provide resolver functions for your schema fields
var rootResolvers = {
    Query: {
        hello: (root, args, context) => {
            return 'Hello world!';
        },
    },
};

// Required: Export the GraphQL.js schema object as "schema"
var myGraphQLSchema = tools.makeExecutableSchema({
    typeDefs: [rootSchema],
    resolvers: rootResolvers
});
  
app.use('/gql', bodyParser.json(), graphqlExpress({ schema: myGraphQLSchema }));

app.use('/graphiql', graphiqlExpress({ endpointURL: '/gql' }));

module.exports = Webtask.fromExpress(app);

```

I have also included the following npm packages:
```
apollo-server-express@1.0.4
graphql@0.10.5
graphql-tools@1.2.1
```

I can access graphiQL endpoint but it reports the following error:
```
{
  "code": 404,
  "message": "unable to resolve jtn to webtask token",
  "req_id": "1503345173035.470354"
}
```
And with apollo client the following error occurs:
```
Error: Schema must be an instance of GraphQLSchema. Also ensure that there are not multiple versions of GraphQL installed in your node_modules directory.<br> &nbsp; &nbsp;at invariant (/data/_verquire/apollo-server-express/1.0.4/node_modules/apollo-server-express/node_modules/graphql/jsutils/invariant.js:19:11)<br> &nbsp; &nbsp;at Object.validate (/data/_verquire/apollo-server-express/1.0.4/node_modules/apollo-server-express/node_modules/graphql/validation/validate.js:60:72)<br> &nbsp; &nbsp;at doRunQuery (/data/_verquire/apollo-server-express/1.0.4/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/runQuery.js:71:38)<br> &nbsp; &nbsp;at /data/_verquire/apollo-server-express/1.0.4/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/runQuery.js:19:54<br> &nbsp; &nbsp;at process._tickDomainCallback (node.js:481:9)
```
Any ideas on how can this be resolved? Are there any plans for implementing a webtask variant?

**Comment by martinhbramwell** [comment]
This error appears if you do not specify a valid path.

Try this one for example : 
https://wt-666ohgod666ohgod666ohgod666ohgod-0.run.webtask.io/antidisestablishmentarianism666

**Comment by JacksonKearl** [comment]
Looks like Webtask.io has been shut down, so unfortunately I'm not sure this is something we'll be able to help with.

**Comment by martinhbramwell** [comment]
Just tried it.   https://webtask.io/

Works fine.

**Comment by JacksonKearl** [comment]
I see a message: "We are no longer accepting new user signups on webtask.io."

**Comment by JacksonKearl** [comment]
![image](https://user-images.githubusercontent.com/8586769/60471618-5f17f880-9c1a-11e9-9b64-d3c14fedf6d7.png)
