### ISSUE TITLE
Error on lambda call

### ISSUE THREAD

**Issue by alialamine** [apollographql/apollo-server#5249]
Hello, We encountered the following when running the apollo-server-lambda package:

```
{ "errorType": "TypeError", "errorMessage": "Cannot read property 'endsWith' of undefined", "stack": [ "TypeError: Cannot read property 'endsWith' of undefined", " at m.<anonymous> (/var/task/src/gql/handler.js:2373:32949)", " at Generator.next (<anonymous>)", " at /var/task/src/gql/handler.js:2373:31026", " at new Promise (<anonymous>)", " at i (/var/task/src/gql/handler.js:2373:30771)", " at m (/var/task/src/gql/handler.js:2373:32378)", " at Runtime.handler (/var/task/src/gql/handler.js:2373:34824)", " at Runtime.handleOnce (/var/runtime/Runtime.js:66:25)" ] }
```

Last version where it worked: 2.24.x
Expected behavior: The function should start correctly
Actual behavior: It crashes on the initialization phase with the above error
Reproduction: Will build one if I don't find and pull-request, hints would be appreciated (will try to figure it out first without building a reproductble repo and pull-request as it's less time-consuming if I find it)

**Comment by alialamine** [comment]
This isn't from here, but caused by a custom wrapper we're using on the federation gateway to not go through apigateway
