### ISSUE TITLE
Error: Cannot find module 'core-js-pure/features/array/flat'

### ISSUE THREAD

**Issue by Sakdow** [apollographql/apollo-server#5335]
### Intended outcome:

Trying to install/run an apollo server on Heroku.

### Actual outcome:

When running apollo-server v2.25.1, I get an error when running the server in production mode. That error looks like this:

```
 Error: Cannot find module 'core-js-pure/features/array/flat'
 Require stack:
 - /app/node_modules/apollo-graphql/lib/schema/buildSchemaFromSDL.js
 - /app/node_modules/apollo-graphql/lib/schema/index.js
 - /app/node_modules/apollo-graphql/lib/index.js
 - /app/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/plugin/usageReporting/plugin.js
 - /app/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/plugin/usageReporting/index.js
 - /app/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/plugin/index.js
 - /app/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/ApolloServer.js
 - /app/node_modules/apollo-server-express/node_modules/apollo-server-core/dist/index.js
 - /app/node_modules/apollo-server-express/dist/index.js
 - /app/node_modules/apollo-server/dist/index.js
 - /app/src/security.ts
 - /app/src/graphql/authentication/authentication.resolver.ts
 - /app/src/apolloInstance.ts
 - /app/src/app.ts
     at Function.Module._resolveFilename (node:internal/modules/cjs/loader:941:15)
     at Function.Module._resolveFilename (/app/node_modules/tsconfig-paths/lib/register.js:75:40)
     at Function.Module._load (node:internal/modules/cjs/loader:774:27)
     at Module.require (node:internal/modules/cjs/loader:1013:19)
     at require (node:internal/modules/cjs/helpers:93:18)
     at Object.<anonymous> (/app/node_modules/apollo-graphql/src/schema/buildSchemaFromSDL.ts:32:1)
     at Module._compile (node:internal/modules/cjs/loader:1109:14)
     at Module._extensions..js (node:internal/modules/cjs/loader:1138:10)
     at Object.require.extensions.<computed> [as .js] (/app/node_modules/ts-node/src/index.ts:1286:43)
     at Module.load (node:internal/modules/cjs/loader:989:32)
```

### My dependencies
```
"dependencies": {
        "@types/bcrypt": "^5.0.0",
        "@types/bluebird": "^3.5.35",
        "@types/cookie": "^0.4.0",
        "@types/dotenv": "^8.2.0",
        "@types/jsonwebtoken": "^8.5.1",
        "@types/node": "^15.12.2",
        "@types/nodemailer": "^6.4.2",
        "@types/nodemailer-sendgrid": "^1.0.0",
        "@types/validator": "^13.1.4",
        "apollo-server": "^2.25.1",
        "babel-cli": "^6.26.0",
        "bcrypt": "^5.0.1",
        "class-validator": "^0.13.1",
        "cookie": "^0.4.1",
        "dotenv": "^10.0.0",
        "graphql": "^15.5.0",
        "graphql-scalars": "^1.10.0",
        "graphql-tools": "^7.0.5",
        "handlebars": "^4.7.7",
        "inversify": "^5.1.1",
        "jsonwebtoken": "^8.5.1",
        "moment": "^2.29.1",
        "nodemailer": "^6.6.1",
        "nodemailer-sendgrid": "^1.0.3",
        "password-validator": "^5.1.1",
        "pg": "^8.6.0",
        "pg-hstore": "^2.3.4",
        "reflect-metadata": "^0.1.13",
        "ts-node": "^10.0.0",
        "tsconfig-paths": "^3.9.0",
        "type-graphql": "^1.1.1",
        "typeorm": "^0.2.34",
        "typescript": "^4.3.3",
        "validator": "^13.6.0",
        "winston": "^3.3.3"
    },
    "devDependencies": {
        "@babel/core": "^7.14.6",
        "@babel/register": "^7.14.5",
        "@types/jest": "^26.0.23",
        "@typescript-eslint/eslint-plugin": "^4.27.0",
        "@typescript-eslint/parser": "^4.27.0",
        "eslint": "^7.28.0",
        "husky": "^6.0.0",
        "jest": "^27.0.4",
        "lint-staged": "^11.0.0",
        "nodemon": "^2.0.7",
        "prettier": "^2.3.1",
        "sqlite3": "^5.0.2",
        "ts-jest": "^27.0.3",
        "typeorm-seeding": "^1.6.1"
    },
```
### How to reproduce the issue:
Maybe running the app on Heroku with this version (didn't try with another project).

**Comment by glasser** [comment]
@Sakdow Did you resolve your issue?
