### ISSUE TITLE
PubSub missing in v3.0.0 of apollo-server-express

### ISSUE THREAD

**Issue by UglyHobbitFeet** [apollographql/apollo-server#5477]
I upgraded from v2.25.2 to v3.0.0 of apollo-server-express

I now get the following message:

```
TypeError: PubSub is not a constructor
     at Object.<anonymous> (/<pathToMyJsFile>)
     at Module._compile (internal/modules/cjs/loader.js:1063:30)
     at Object.Module._extensions..js (internal/modules/cjs/loader.js:1092:10)
     at Module.load (internal/modules/cjs/loader.js:928:32)
     at Function.Module._load (internal/modules/cjs/loader.js:769:14)
     at Module.require (internal/modules/cjs/loader.js:952:19)
     at require (internal/modules/cjs/helpers.js:88:18)
     at /app/node_modules/@graphql-tools/load-files/index.cjs.js:126:33
     at Array.map (<anonymous>)
     at loadFilesSync (/app/node_modules/@graphql-tools/load-files/index.cjs.js:117:10)

```

Code that triggered it was:

```
const { PubSub, withFilter } = require('apollo-server-express');
const pubsub = new PubSub(); // <-- Breaks here
```

I did not see anything in the documentation about breaking changes to PubSub.

**Comment by UglyHobbitFeet** [comment]
FWIW If I do a console.log(typeof PubSub) I get 'undefined'

**Comment by KeithGillette** [comment]
[Per the migration guide](https://www.apollographql.com/docs/apollo-server/migration/#subscriptions), all integrated Subscriptions support, [including PubSub](https://www.apollographql.com/docs/apollo-server/migration/#exports-from-graphql-subscriptions) has been removed from Apollo Server 3, so you need to add the external packages and refactor your imports and initialization code following [the updated Subscriptions documentation](https://www.apollographql.com/docs/apollo-server/data/subscriptions/).

**Comment by UglyHobbitFeet** [comment]
@KeithGillette 
Thanks, got it working now!

**Comment by glasser** [comment]
Thanks @KeithGillette!
