### ISSUE TITLE
server.createHandler() not working in an Async function for Apollo Server3.x

### ISSUE THREAD

**Issue by sachinkshetty** [apollographql/apollo-server#5597]
i am new to apollo and using apollo server 3 and azure functions. 

i am getting an error when i am trying to return the handler as suggested by the code example on "Migrating to Apollo Sever3"
******

    const run = async (context, request) => {
        const {schema, contextBuilder} = await getSchema()
        const server = new ApolloServer({
            schema,
            context: contextBuilder
        })
        const handler = server.createHandler()
        try {
            return await handler(request, context)
        } catch (e) {
            console.log(e)
        } finally {
            console.log("done")
        }
    }

******

above code throws me below error in the console and blank screen on browser. I am expecting to see the playground

For detailed output, run func with --verbose flag.
[2021-08-10T10:21:16.531Z] Executing 'Functions.src' (Reason='This function was programmatically called via the host APIs.', Id=bc2f935a-4f58-4277-a13a-cc5d00e8d8d4)
[2021-08-10T10:21:16.673Z] sac
[2021-08-10T10:21:16.692Z] (node:32821) UnhandledPromiseRejectionWarning: TypeError: context.done is not a function
[2021-08-10T10:21:16.692Z]     at /Users/b8569616/Github/dotcom-api-stock/graphql/node_modules/apollo-server-azure-functions/src/ApolloServer.ts:170:33
[2021-08-10T10:21:16.692Z]     at processTicksAndRejections (internal/process/task_queues.js:95:5)
[2021-08-10T10:21:16.692Z] (Use `node --trace-warnings ...` to show where the warning was created)
[2021-08-10T10:21:16.692Z] (node:32821) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). To terminate the node process on unhandled promise rejection, use the CLI flag `--unhandled-rejections=strict` (see https://nodejs.org/api/cli.html#cli_unhandled_rejections_mode). (rejection id: 1)
[2021-08-10T10:21:16.743Z] (node:32821) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

any help would be highly appreciated

**Comment by glasser** [comment]
It looks like you're setting up a brand new ApolloServer for every HTTP request, which doesn't seem right to me. What part of the migration guide is suggesting that you write this? The main [Azure Functions example page](https://www.apollographql.com/docs/apollo-server/deployment/azure-functions/#sample-code) shows you how to call `server.createHandler` at the top level.
