### ISSUE TITLE
Hot Module Reload not working with NestJS

### ISSUE THREAD

**Issue by phiggins** [apollographql/apollo-server#5613]
### Current behavior

Following the [NestJS Hot Reload guide](https://docs.nestjs.com/recipes/hot-reload) does not work with Apollo. This has already been filed as an issue with NestJS and was redirected here: nestjs/nest#7840

After making an update to a GraphQL resolver, the server builds again, and other non-GraphQL controllers/endpoints work, but for a variable time period (several seconds to several minutes) all GraphQL queries/mutations return the error:

```
Error: Cannot execute GraphQL operations after the server has stopped.
  at ApolloServer.<anonymous> (/Users/davidgolightly/dev/hotreload/.yarn/__virtual__/apollo-server-core-virtual-4a38e28045/0/cache/apollo-server-core-npm-2.25.2-17277a84d0-9470fd40eb.zip/node_modules/apollo-server-core/dist/ApolloServer.js:306:31)
  at Generator.next (<anonymous>)
  at /Users/davidgolightly/dev/hotreload/.yarn/__virtual__/apollo-server-core-virtual-4a38e28045/0/cache/apollo-server-core-npm-2.25.2-17277a84d0-9470fd40eb.zip/node_modules/apollo-server-core/dist/ApolloServer.js:8:71
  at new Promise (<anonymous>)
  at __awaiter (/Users/davidgolightly/dev/hotreload/.yarn/__virtual__/apollo-server-core-virtual-4a38e28045/0/cache/apollo-server-core-npm-2.25.2-17277a84d0-9470fd40eb.zip/node_modules/apollo-server-core/dist/ApolloServer.js:4:12)
  at ApolloServer.ensureStarted (/Users/davidgolightly/dev/hotreload/.yarn/__virtual__/apollo-server-core-virtual-4a38e28045/0/cache/apollo-server-core-npm-2.25.2-17277a84d0-9470fd40eb.zip/node_modules/apollo-server-core/dist/ApolloServer.js:283:16)
  at ApolloServer.<anonymous> (/Users/davidgolightly/dev/hotreload/.yarn/__virtual__/apollo-server-core-virtual-4a38e28045/0/cache/apollo-server-core-npm-2.25.2-17277a84d0-9470fd40eb.zip/node_modules/apollo-server-core/dist/ApolloServer.js:661:83)
  at Generator.next (<anonymous>)
  at /Users/davidgolightly/dev/hotreload/.yarn/__virtual__/apollo-server-core-virtual-4a38e28045/0/cache/apollo-server-core-npm-2.25.2-17277a84d0-9470fd40eb.zip/node_modules/apollo-server-core/dist/ApolloServer.js:8:71
  at new Promise (<anonymous>)
```

This appears to be thrown by Apollo Server when the server has stopped. My guess is that the internal Apollo Server
has been stopped by the reload process, but is taking a long time to restart for some reason.

While the linked repro does reproduce the issue, it seems to fix itself after a relatively short period of time. Our
(much larger) production Nest.js app takes much longer, on the order of 15-20 minutes.

Even catching this error in HMR mode and displaying something like "Apollo Server is restarting" would be helpful,
but best of course would be fixing the responsiveness of the hot-reloaded Apollo Server.

### Input Code

See minimal repro here: https://github.com/LeapYear/hotreload-repro

### Expected behavior

In order for HMR to be useful in dev mode, the time between start of rebuild to a usable server must be
less than the time it would take to manually stop then restart the server.

### Environment

```
Nest version: 8.0.6

 
For Tooling issues:
- Node version: v16.0.0  
- Platform:  Mac Catalina (10.15.7) 

Others:

apollo-server-express/apollo-server-core 2.25.2
npm 7.10.0
also repros on yarn berry v3.0.0
```

/cc @davidgoli

**Comment by glasser** [comment]
I'm unable to try your reproduction because for some reason running `npm i` wants to download things from some leapyear-specific repo:

```
npm timing npm:load Completed in 127ms
npm timing config:load:flatten Completed in 3ms
npm timing arborist:ctor Completed in 1ms
npm timing idealTree:init Completed in 333ms
npm timing idealTree:userRequests Completed in 1ms
npm timing idealTree:#root Completed in 0ms
npm timing idealTree:buildDeps Completed in 1ms
npm timing idealTree:fixDepFlags Completed in 0ms
npm timing idealTree Completed in 346ms
npm timing reify:loadTrees Completed in 499ms
npm timing reify:diffTrees Completed in 14ms
npm timing reify:retireShallow Completed in 8ms
npm timing reify:createSparse Completed in 3ms
npm timing reify:loadBundles Completed in 0ms
npm http fetch POST 200 https://registry.npmjs.org/-/npm/v1/security/advisories/bulk 399ms
npm timing auditReport:getReport Completed in 403ms
npm timing auditReport:init Completed in 0ms
npm timing reify:audit Completed in 404ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/uuid/-/uuid-8.3.2.tgz 491ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/@babel/parser/-/parser-7.15.3.tgz 518ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/semver/-/semver-6.3.0.tgz 513ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/webpack/-/webpack-5.45.1.tgz 516ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/mkdirp/-/mkdirp-1.0.4.tgz 528ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/semver/-/semver-6.3.0.tgz 514ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/@nestjs/cli/-/cli-8.1.1.tgz 527ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/xss/-/xss-1.0.9.tgz 511ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/terser/-/terser-5.7.1.tgz 566ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/ts-node/-/ts-node-10.2.0.tgz 560ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/shelljs/-/shelljs-0.8.4.tgz 559ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/which/-/which-2.0.2.tgz 603ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/@nuxtjs/opencollective/-/opencollective-0.3.2.tgz 622ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/typescript/-/typescript-4.3.5.tgz 695ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/@angular-devkit/schematics-cli/-/schematics-cli-12.1.4.tgz 713ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/@apollo/protobufjs/-/protobufjs-1.2.2.tgz 712ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/tslint/-/tslint-6.1.3.tgz 695ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/webpack/-/webpack-5.50.0.tgz 705ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/ts-jest/-/ts-jest-27.0.4.tgz 787ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/semver/-/semver-5.7.1.tgz 792ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/mkdirp/-/mkdirp-1.0.4.tgz 785ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/mime/-/mime-2.5.2.tgz 784ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/tree-kill/-/tree-kill-1.2.2.tgz 790ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/sha.js/-/sha.js-2.4.11.tgz 870ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/semver/-/semver-7.3.5.tgz 869ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/rimraf/-/rimraf-3.0.2.tgz 863ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/prettier/-/prettier-1.19.1.tgz 861ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/mkdirp/-/mkdirp-0.5.5.tgz 860ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/mime/-/mime-1.6.0.tgz 858ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/json5/-/json5-2.2.0.tgz 1035ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/js-yaml/-/js-yaml-3.14.1.tgz 1033ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/jsesc/-/jsesc-2.5.2.tgz 1028ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/semver/-/semver-6.3.0.tgz 1019ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/jest/-/jest-27.0.6.tgz 1010ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/jest-cli/-/jest-cli-27.0.6.tgz 1002ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/is-ci/-/is-ci-3.0.0.tgz 1103ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/semver/-/semver-6.3.0.tgz 1095ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/uuid/-/uuid-3.4.0.tgz 1093ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/import-local/-/import-local-3.0.2.tgz 1093ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/escodegen/-/escodegen-2.0.0.tgz 1091ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/browserslist/-/browserslist-4.16.7.tgz 1203ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/esprima/-/esprima-4.0.1.tgz 1202ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/acorn/-/acorn-8.4.1.tgz 1201ms
npm http fetch GET 401 https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/acorn/-/acorn-7.4.1.tgz 1199ms
npm timing reify:rollback:createSparse Completed in 14ms
npm timing reify:rollback:retireShallow Completed in 5ms
npm timing command:install Completed in 2059ms
npm verb stack HttpErrorAuthUnknown: Unable to authenticate, need: Basic realm="Artifactory Realm"
npm verb stack     at /usr/local/lib/node_modules/npm/node_modules/npm-registry-fetch/check-response.js:124:17
npm verb stack     at processTicksAndRejections (node:internal/process/task_queues:96:5)
npm verb statusCode 401
npm verb pkgid mkdirp@https://artifacts.leapyear.io/artifactory/api/npm/leapyear-node-all/mkdirp/-/mkdirp-1.0.4.tgz
npm verb cwd /private/tmp/hotreload-repro
npm verb Darwin 18.7.0
npm verb argv "/usr/local/Cellar/node/16.2.0/bin/node" "/usr/local/bin/npm" "i" "--loglevel=verbose"
npm verb node v16.2.0
npm verb npm  v7.13.0
npm ERR! code E401
npm ERR! Incorrect or missing password.
npm ERR! If you were trying to login, change your password, create an
npm ERR! authentication token or enable two-factor authentication then
npm ERR! that means you likely typed your password in incorrectly.
npm ERR! Please try again, or recover your password at:
npm ERR!     https://www.npmjs.com/forgot
npm ERR! 
npm ERR! If you were doing some other operation then your saved credentials are
npm ERR! probably out of date. To correct this please try logging in again with:
npm ERR!     npm login
npm verb exit 1
npm timing npm Completed in 2579ms
npm verb code 1

npm ERR! A complete log of this run can be found in:
npm ERR!     /Users/glasser/.npm/_logs/2021-08-17T21_44_11_505Z-debug.log
```

Can you provide a reproduction that works without your specific npm setup?

Additionally, it looks like this reproduction uses Apollo Server 2.x. Can you try with Apollo Server 3.x instead? AS2 is only receiving security updates at this time.

**Comment by glasser** [comment]
Additionally, it does feel like this may be more of an issue of how https://github.com/nestjs/graphql uses Apollo Server than about Apollo Server itself. That's a big complex system that we're not super familiar with here.  Understanding the exact semantics about how Nest swaps out one server for the other seems outside the scope of this project.  Do you think you could work with the `@nestjs/graphql` folks to understand how that package uses the Apollo Server API when swapping one out for the other? One would hope that a "hot module reload" API would allow you to start the new version and atomically transition requests to it before stopping the old version, but maybe that's not how Nest works?

**Comment by davidgoli** [comment]
@glasser I've upgraded the minimal repro to use AS3, and the bug still persists. Would you mind taking another look?

**Comment by davidgoli** [comment]
(My apologies for the company-specific npm registry. I'm currently working on fixing that locally, and hope to push it up shortly. For now, you should be able to get install working by deleting `package-lock.json`.)

**Comment by davidgoli** [comment]
I've pushed an update to the repro, which now uses Yarn due to a quirk of npm's behavior:

https://docs.npmjs.com/cli/v7/using-npm/registry#description

> If you create a lock file while using the default registry you can switch to another registry and npm will install packages from the new registry, but if you create a lock file while using a custom registry packages will be installed from that registry even after you change to another registry.

**Comment by davidgoli** [comment]
Issue at `@nestjs/graphql`: https://github.com/nestjs/graphql/issues/1707

**Comment by glasser** [comment]
Thanks, I can reproduce this. That said, understanding how to fix it is going to require learning a lot more about the architecture of Nest, `@nestjs/graphql`, webpack, and hot module reload than makes sense for this team.

Glancing at https://github.com/nestjs/graphql/blob/master/lib/graphql.module.ts it does seem that `onModuleDestroy` calls `this._apolloServer?.stop()`, and `onModuleInit` (indirectly) creates an ApolloServer and puts it on `this._apolloServer`. I guess somehow the old module ends up attached to the HTTP server? I think this is the sort of thing the Nest team (or the `@nestjs/graphql` folks specifically) are best equipped to debug, and I don't see anything suggesting that there's a bug in Apollo Server itself: if you have set up an architecture where you swap in one server for another, you need to make sure you're using the right server.

Happy to reopen if folks familiar with Nest can show that there's something unexpected happening in ApolloServer itself rather than just the Nest environment not properly swapping out ApolloServers.
