### ISSUE TITLE
CSS Modules cannot be imported from within node_modules when not using a node_modules export

### ISSUE THREAD

**Issue by jorgev259** [apollographql/apollo-server#5785]
Apollo-server-micro

When adding apollo-server-micro to a nextjs instance, random webpack errors and css modules errors appear for any .scss or non .js file in the project.

Reproducible repo: https://github.com/jorgev259/bug-test

**Comment by glasser** [comment]
I assume that the command I was supposed to run was `npm i && npm run build` and I see something like:

```
$ npm run build

> bug-test@0.1.0 build
> next build

info  - Using webpack 5. Reason: Enabled by default https://nextjs.org/docs/messages/webpack5
info  - Checking validity of types  
error - ESLint: Cannot read property 'value' of null Occurred while linting /private/tmp/bug-test/pages/index.js:16
(node:64157) [DEP_WEBPACK_MODULE_ISSUER] DeprecationWarning: Module.issuer: Use new ModuleGraph API
(Use `node --trace-deprecation ...` to show where the warning was created)
info  - Creating an optimized production build  
Failed to compile.

./styles/Album.module.scss
CSS Modules cannot be imported from within node_modules.
Read more: https://nextjs.org/docs/messages/css-modules-npm


> Build error occurred
Error: > Build failed because of webpack errors
    at /private/tmp/bug-test/node_modules/next/dist/build/index.js:397:19
    at async Span.traceAsyncFn (/private/tmp/bug-test/node_modules/next/dist/telemetry/trace/trace.js:60:20)
    at async Object.build [as default] (/private/tmp/bug-test/node_modules/next/dist/build/index.js:77:25)
```

However, I also see the same thing when I remove `apollo-server-micro` from your package.json (and comment out a bunch of stuff in pages/api/graphql.js that reference it.

So I don't think this has anything to do with Apollo Server.
