### ISSUE TITLE
cryptic error on call : called start() with surprising state started

### ISSUE THREAD

**Issue by mdcarter** [apollographql/apollo-server#5802]
I'm trying to setup an apollo server within a Next.js app using `apollo-server-micro` and I have this very simple test server : 
```javascript
import { ApolloServer, gql } from 'apollo-server-micro'

const typeDefs = gql`
  type  User {
    id: ID
    firstname: String
    lastname: String
  }

  type Query {
    getUser(id: ID!): User!
  }
`

const resolvers = {
  Query: {
    getUser: async () => {
      return {
        id: '1',
        firstname: 'Foo',
        lastname: 'Bar',
      }
    },
  },
}

const server = new ApolloServer({ typeDefs, resolvers, introspection: true })
const handler = async (req, res) => {
  await server.start()
  return server.createHandler({ path: '/api/graphql' })(req, res)
}

export const config = {
  api: {
    bodyParser: false
  }
}

export default handler
```

The server starts fine, but the second I'm making a request on it, I have this very cryptic error for which I cannot find any informations on : 
```bash
error - Error: called start() with surprising state started
    at ApolloServer._start (/Users/maximedehaye/Work/mdehaye/laderniereposte.fr/node_modules/apollo-server-core/dist/ApolloServer.js:138:19)
    at ApolloServer.start (/Users/maximedehaye/Work/mdehaye/laderniereposte.fr/node_modules/apollo-server-core/dist/ApolloServer.js:133:27)
    at handler (webpack-internal:///./pages/api/graphql.js:40:16)
    at Object.apiResolver (/Users/maximedehaye/Work/mdehaye/laderniereposte.fr/node_modules/next/dist/server/api-utils.js:101:15)
    at DevServer.handleApiRequest (/Users/maximedehaye/Work/mdehaye/laderniereposte.fr/node_modules/next/dist/server/next-server.js:770:30)
    at async Object.fn (/Users/maximedehaye/Work/mdehaye/laderniereposte.fr/node_modules/next/dist/server/next-server.js:661:37)
    at async Router.execute (/Users/maximedehaye/Work/mdehaye/laderniereposte.fr/node_modules/next/dist/server/router.js:205:32)
    at async DevServer.run (/Users/maximedehaye/Work/mdehaye/laderniereposte.fr/node_modules/next/dist/server/next-server.js:841:29)
    at async DevServer.run (/Users/maximedehaye/Work/mdehaye/laderniereposte.fr/node_modules/next/dist/server/dev/next-dev-server.js:355:20)
    at async DevServer.handleRequest (/Users/maximedehaye/Work/mdehaye/laderniereposte.fr/node_modules/next/dist/server/next-server.js:292:20) {
  page: '/api/graphql'
}
```

Could you help me with this issue ?
Thank you very much in advance 🙏

**Comment by glasser** [comment]
I filed https://github.com/vercel/next.js/pull/30082 to fix Next.js's examples.
