### ISSUE TITLE
 Error in apollo-server-plugin-response-cache

### ISSUE THREAD

**Issue by nnyam3831** [apollographql/apollo-server#5804]
Hello everyone,  I got this error
```
Error: Cannot find module 'apollo-server-types'
[1] Require stack:
[1] - /project/node_modules/apollo-server-plugin-response-cache/dist/ApolloServerPluginResponseCache.js
[1] - /project/node_modules/apollo-server-plugin-response-cache/dist/index.js
[1] - /project/packages/package1/src/server/start.ts
[1] - /project/packages/package1/src/server/index.ts
[1]     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:902:15)
[1]     at Function.Module._resolveFilename (/project/node_modules/tsconfig-paths/lib/register.js:75:40)
[1]     at Function.Module._load (internal/modules/cjs/loader.js:746:27)
[1]     at Module.require (internal/modules/cjs/loader.js:974:19)
[1]     at require (internal/modules/cjs/helpers.js:92:18)
[1]     at Object.<anonymous> (/project/node_modules/apollo-server-plugin-response-cache/src/ApolloServerPluginResponseCache.ts:8:1)
[1]     at Module._compile (internal/modules/cjs/loader.js:1085:14)
[1]     at Module._compile (/project/node_modules/source-map-support/source-map-support.js:547:25)
[1]     at Module._extensions..js (internal/modules/cjs/loader.js:1114:10)
[1]     at Object.nodeDevHook [as .js] (/project/node_modules/ts-node-dev/lib/hook.js:63:13)
[1] [ERROR] 21:04:23 Error: Cannot find module 'apollo-server-types'
[1] Require stack:
[1] - /project/node_modules/apollo-server-plugin-response-cache/dist/ApolloServerPluginResponseCache.js
[1] - /project/node_modules/apollo-server-plugin-response-cache/dist/index.js
[1] - /project/packages/package1/src/server/start.ts
[1] - /project/packages/package1/src/server/index.ts

```

So, I look up the source code of `ApolloServerPluginResponseCache` in 'apollo-server-plugin-response-cache'.
From what I see, now package.json has [apollo-server-types](https://github.com/apollographql/apollo-server/blob/291c17e255122d4733b23177500188d68fac55ce/packages/apollo-server-plugin-response-cache/package.json#L26) as devdependencies. However, [ApolloServerPluginResponse](https://github.com/apollographql/apollo-server/blob/291c17e255122d4733b23177500188d68fac55ce/packages/apollo-server-plugin-response-cache/src/ApolloServerPluginResponseCache.ts#L298) js uses an enum called `CacheScope`, so an error seems to occur. Maybe this should be in dependencies, not devdependencies?

**Comment by glasser** [comment]
Thanks for the catch; fixing in #5816.
