### ISSUE TITLE
Cannot handle middleware errors in the apollo server

### ISSUE THREAD

**Issue by esase** [apollographql/apollo-server#6268]
**Package**
apollo-server@3.5.0

**Description**
There is no option to handle internal middleware errors  using the `ApolloServer`, for instance when we send an incorrectly formatted json request like: 
```
{kkk}
```

we will be provided with an error: 
```
<!DOCTYPE html>
<html lang="en">

<head>
	<meta charset="utf-8">
	<title>Error</title>
</head>

<body>
	<pre>SyntaxError: Unexpected token k in JSON at position 1<br> &nbsp; &nbsp;at JSON.parse (&lt;anonymous&gt;)<br> &nbsp; &nbsp;at parse (/Users/esase/Sites/crg/liigu-api/node_modules/body-parser/lib/types/json.js:89:19)<br> &nbsp; &nbsp;at /Users/esase/Sites/crg/liigu-api/node_modules/body-parser/lib/read.js:121:18<br> &nbsp; &nbsp;at invokeCallback (/Users/esase/Sites/crg/liigu-api/node_modules/raw-body/index.js:224:16)<br> &nbsp; &nbsp;at done (/Users/esase/Sites/crg/liigu-api/node_modules/raw-body/index.js:213:7)<br> &nbsp; &nbsp;at IncomingMessage.onEnd (/Users/esase/Sites/crg/liigu-api/node_modules/raw-body/index.js:273:7)<br> &nbsp; &nbsp;at IncomingMessage.emit (events.js:412:35)<br> &nbsp; &nbsp;at endReadableNT (internal/streams/readable.js:1317:12)<br> &nbsp; &nbsp;at processTicksAndRejections (internal/process/task_queues.js:82:21)</pre>
</body>

</html>
```

which cannot be logged and it even has the html format

**Expected behavior**

Such errors also should be managed by the `ApolloServer` and not triggered outside the flow

**Actual behavior**

Errors are triggered out side the ApolloServer's flow

**Comment by glasser** [comment]
`apollo-server` is based on `apollo-server-express` which uses the standard [`body-parser` npm package](https://www.npmjs.com/package/body-parser) for JSON parsing.

`apollo-server` intentionally provides few knobs for tuning its HTTP handling; the expectation is that if you need to tune things you'll [switch to the more flexible `apollo-server-express`](https://www.apollographql.com/docs/apollo-server/integrations/middleware#example) or another HTTP server integration.  You can then use a standard [Express error handler](https://expressjs.com/en/guide/error-handling.html) to handle the error.

(In the forthcoming version 4, we will make this even more clear by removing the built-in body parsing from the equivalent of `apollo-server-express` so that it's even more clear what you need to tweak to change body parsing parameters.)
