### ISSUE TITLE
Error: Must provide document

### ISSUE THREAD

**Issue by mpicard** [apollographql/apollo-server#629]
# Intended outcome

start apollo-server-express using the following snippet from https://github.com/apollographql/apollo-tutorial-kit.
```
import express from 'express';
import { graphqlExpress, graphiqlExpress } from 'apollo-server-express';
import bodyParser from 'body-parser';
import schema from './data/schema';

const GRAPHQL_PORT = 3000;

const graphQLServer = express();

graphQLServer.use('/graphql', bodyParser.json(), graphqlExpress({ schema }));
graphQLServer.use('/graphiql', graphiqlExpress({ endpointURL: '/graphql' }));

graphQLServer.listen(GRAPHQL_PORT, () => console.log(
  `GraphiQL is now running on http://localhost:${GRAPHQL_PORT}/graphiql`
));
```

# Actual Outcome:

In any implementation of apollo-server-express, using docs, using https://github.com/apollographql/apollo-tutorial-kit, etc. I receive the follow stack trace over and over again:
```
Error: Must provide document
    at invariant (~/repos/apollo-tutorial-kit/node_modules/graphql/jsutils/invariant.js:19:11)
    at Object.validate (~/repos/apollo-tutorial-kit/node_modules/graphql/validation/validate.js:59:34)
    at doRunQuery (~/repos/apollo-tutorial-kit/node_modules/apollo-server-core/src/runQuery.ts:137:30)
    at ~/repos/apollo-tutorial-kit/node_modules/apollo-server-core/src/runQuery.ts:70:39
```

# How to reproduce the issue:
```
git clone https://github.com/apollographql/apollo-tutorial-kit.git
cd apollo-tutorial-kit
yarn/npm i
npm start
```

**Comment by mpicard** [comment]
Upon clearing npm cache and node_modules, was unable to reproduce.
