### ISSUE TITLE
Runtime.ImportModuleError: Error: Cannot find module '@keyv/redis' when running on AWS Lambda

### ISSUE THREAD

**Issue by RoyBkker** [apollographql/apollo-server#6682]
When deploying to AWS lambda, I reveive the following error:
`Runtime.ImportModuleError: Error: Cannot find module '@keyv/redis' `

Code to reproduce:

```
import { KeyvAdapter } from '@apollo/utils.keyvadapter'
import Keyv from 'keyv'
import { redisUrl } from '~src/config'

export const server = new ApolloServer({
   cache: new KeyvAdapter(new Keyv(redisUrl)),
   ...other stuff
})
```

```
  "dependencies": {
    "@apollo/federation": "0.24.0",
    "@apollo/utils.keyvadapter": "1.1.0",
    "@keyv/redis": "2.3.7",
    "apollo-server-lambda": "3.10.0",
    "keyv": "4.3.2"
    }
```

Error logs on AWS:

```
2022-07-14T08:45:34.068Z	undefined	ERROR	Uncaught Exception 	
{
    "errorType": "Runtime.ImportModuleError",
    "errorMessage": "Error: Cannot find module '@keyv/redis'\nRequire stack:\n- /var/task/src/http/index.js\n- /var/runtime/UserFunction.js\n- /var/runtime/Runtime.js\n- /var/runtime/index.js",
    "stack": [
        "Runtime.ImportModuleError: Error: Cannot find module '@keyv/redis'",
        "Require stack:",
        "- /var/task/src/http/index.js",
        "- /var/runtime/UserFunction.js",
        "- /var/runtime/Runtime.js",
        "- /var/runtime/index.js",
        "    at _loadUserApp (/var/runtime/UserFunction.js:221:13)",
        "    at Object.module.exports.load (/var/runtime/UserFunction.js:279:17)",
        "    at Object.<anonymous> (/var/runtime/index.js:43:34)",
        "    at Module._compile (internal/modules/cjs/loader.js:1085:14)",
        "    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1114:10)",
        "    at Module.load (internal/modules/cjs/loader.js:950:32)",
        "    at Function.Module._load (internal/modules/cjs/loader.js:790:12)",
        "    at Function.executeUserEntryPoint [as runMain] (internal/modules/run_main.js:75:12)",
        "    at internal/main/run_main_module.js:17:47"
    ]
}
```

**Comment by kdybicz** [comment]
Got it, it's related to the fact that I'm not directly referencing `@keyv/redis` so it's just falling out during tree shaking phase. To force it being included I'm using `webpack` configuration in my `serverless.yml`:

```
custom:
  webpack:
    includeModules:
      forceInclude:
        - '@keyv/redis'
```

This solves the problem in my case.

**Comment by glasser** [comment]
You can also reference it explicitly if you'd like, as shown in the `@keyv/redis` README:

```
import KeyvRedis from '@keyv/redis'
import { KeyvAdapter } from '@apollo/utils.keyvadapter'
import Keyv from 'keyv'
import { redisUrl } from '~src/config'

export const server = new ApolloServer({
   cache: new KeyvAdapter(new Keyv({ store: new KeyvRedis(redisUrl) })),
   ...other stuff
})
```

I don't think this is really an Apollo Server bug so I'm going to close it!
