### ISSUE TITLE
TypeError: Cannot read property 'code' of undefined

### ISSUE THREAD

**Issue by xinghul** [apollographql/apollo-server#7238]
### Issue Description

Hi, I upgraded to v4.2.2 recently from v3 and hit this error, here's the full stack:
```bash
TypeError: Cannot read property 'code' of undefined
    at enrichError (/aspirex/services/node_modules/@apollo/server/src/errorNormalize.ts:64:33)
    at /aspirex/services/node_modules/@apollo/server/src/errorNormalize.ts:46:18
    at Array.map (<anonymous>)
    at normalizeAndFormatErrors (/aspirex/services/node_modules/@apollo/server/src/errorNormalize.ts:39:29)
    at ApolloServer.errorResponse (/aspirex/services/node_modules/@apollo/server/src/ApolloServer.ts:1071:73)
    at ApolloServer.executeHTTPGraphQLRequest (/aspirex/services/node_modules/@apollo/server/src/ApolloServer.ts:1063:19)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
```

looks like `graphqlError.extensions` coming from `ensureGraphQLError(maybeError)` is undefined in this case.

### Link to Reproduction

N/A

**Comment by xinghul** [comment]
upgrading to graphql@16 fixed the issue, closing the issue.
