### ISSUE TITLE
Add support for bigint

### ISSUE THREAD

**Issue by oxilor** [apollographql/apollo-server#7502]
### Issue Description

If the response contains `bigint` values, the following error occurs:
```json
{
    "errors": [
        {
            "message": "Do not know how to serialize a BigInt",
            "extensions": {
                "code": "INTERNAL_SERVER_ERROR",
                "exception": {
                    "stacktrace": [
                        "TypeError: Do not know how to serialize a BigInt",
                        "    at JSON.stringify (<anonymous>)",
                        "    at prettyJSONStringify (/Users/oxilor/Projects/personal/apollo-server-bigint-issue/node_modules/apollo-server-core/src/runHttpQuery.ts:576:15)",
                        "    at processHTTPRequest (/Users/oxilor/Projects/personal/apollo-server-bigint-issue/node_modules/apollo-server-core/src/runHttpQuery.ts:461:14)",
                        "    at processTicksAndRejections (node:internal/process/task_queues:95:5)"
                    ]
                }
            }
        }
    ]
}
```

### Link to Reproduction

https://github.com/oxilor/apollo-server-bigint-issue

### Reproduction Steps

1. Run `yarn start`.
2. Make a request to `http://localhost:4000/graphql` with the the following query (e.g. using Postman):

```graphql
query Query {
  region {
    id
    population
  }
}
```

**Comment by trevor-scheer** [comment]
Thanks for the reproduction! Your `serialize` function definitely should not be the same as your `parseValue` function. `serialize` is responsible for turning your parsed value into something that can be stringified by `JSON.stringify` (i.e. a string or an object with a '.toJSON()` function on it.

The error you're seeing makes sense - since your `serialize` function currently hands off a `BigInt` to `JSON.serialize`, it blows up (you can see this same error just by running this in your console `JSON.stringify(100n)`) since `BigInt` doesn't have a `.toJSON()` function.

There is lots of info online about how to handle larger-than-32-bit-ints, [here's a SO post](https://stackoverflow.com/questions/18755125/node-js-is-there-any-proper-way-to-parse-json-with-large-numbers-long-bigin) as a jumping off point.
