### ISSUE TITLE
ESM TypeError: resolvable is not a function

### ISSUE THREAD

**Issue by macrozone** [apollographql/apollo-server#7895]
### Issue Description

when switching to ESM, apollo server no longer starts. you get this error:

```
TypeError: resolvable is not a function
    at ApolloServer._start (/path/to/project/node_modules/@apollo/server/dist/esm/ApolloServer.js:127:25)
    at ApolloServer.start (/path/to/project/node_modules/@apollo/server/dist/esm/ApolloServer.js:115:27)
```

### Link to Reproduction

not yet

### Reproduction Steps

1. install    "@apollo/server": "^4.10.4",
2. set `"type": "module"` in package.json
3. start apollo server

```

import { ApolloServer } from "@apollo/server";

 const server = new ApolloServer<{}>({
    schema,
    plugins: [ApolloServerPluginDrainHttpServer({ httpServer })],
  });

 await server.start();

```

**Comment by macrozone** [comment]
looks like a "left-pad" situation. https://github.com/josephg/resolvable is a 17 liner and has not been updated in 3 years.

come one, just don't use dependencies like that

**Comment by ivosabev** [comment]
I use the following `patch-package` patch

```
diff --git a/node_modules/@apollo/server/dist/esm/ApolloServer.js b/node_modules/@apollo/server/dist/esm/ApolloServer.js
index b716f63..25370aa 100644
--- a/node_modules/@apollo/server/dist/esm/ApolloServer.js
+++ b/node_modules/@apollo/server/dist/esm/ApolloServer.js
@@ -1,7 +1,7 @@
 import { isNodeLike } from '@apollo/utils.isnodelike';
 import { InMemoryLRUCache, PrefixingKeyValueCache, } from '@apollo/utils.keyvaluecache';
 import { makeExecutableSchema } from '@graphql-tools/schema';
-import resolvable from '@josephg/resolvable';
+import resolvable from '@josephg/resolvable/index.js';
 import { GraphQLError, assertValidSchema, print, printSchema, } from 'graphql';
 import loglevel from 'loglevel';
 import Negotiator from 'negotiator';
```

**Comment by macrozone** [comment]
> I use the following `patch-package` patch
> 
> ```
> diff --git a/node_modules/@apollo/server/dist/esm/ApolloServer.js b/node_modules/@apollo/server/dist/esm/ApolloServer.js
> index b716f63..25370aa 100644
> --- a/node_modules/@apollo/server/dist/esm/ApolloServer.js
> +++ b/node_modules/@apollo/server/dist/esm/ApolloServer.js
> @@ -1,7 +1,7 @@
>  import { isNodeLike } from '@apollo/utils.isnodelike';
>  import { InMemoryLRUCache, PrefixingKeyValueCache, } from '@apollo/utils.keyvaluecache';
>  import { makeExecutableSchema } from '@graphql-tools/schema';
> -import resolvable from '@josephg/resolvable';
> +import resolvable from '@josephg/resolvable/index.js';
>  import { GraphQLError, assertValidSchema, print, printSchema, } from 'graphql';
>  import loglevel from 'loglevel';
>  import Negotiator from 'negotiator';
> ```

thank you, this indeed fixes the issue.

its weird that this happens though, shouldn't node respect the main field as fallback?

**Comment by pthieu** [comment]
fails on node 20 and above, failing on 18
i didn't test any other versions

**Comment by trevor-scheer** [comment]
I haven't spent much time trying to understand the issue, but I opened a PR to inline the dependency which _should_ resolve it. Could someone with a reproduction handy please test it out? There are builds on the PR you can install via the Codesandbox CI comment. Thanks for reporting!

**Comment by macrozone** [comment]
@trevor-scheer I can confirm that your MR works

**Comment by trevor-scheer** [comment]
Fixed via #7900, should be available in `@apollo/server@4.10.5` momentarily. Thanks for reporting!
