### ISSUE TITLE
Crashes on multiple interfaces

### ISSUE THREAD

**Issue by chmac** [apollographql/apollo-server#993]
Reproduction here https://github.com/superlumen/apollo-server-reproductions/tree/multiple-interfaces

```graphql
  interface Foo { foo: String }
  interface Bar { bar: String }
  type FooBar implements Foo, Bar {
    fooBar: String,
    foo: String,
    bar: String
  }
  type Query { books: [Book] }
  type Book { title: String, author: String }
```

Kicks out this error:

```
apollo-server-reproductions/node_modules/graphql/language/parser.js:152
  throw unexpected(lexer);
  ^
GraphQLError: Syntax Error: Unexpected Name "Bar"
    at syntaxError (apollo-server-reproductions/node_modules/graphql/error/syntaxError.js:24:10)
    at unexpected (apollo-server-reproductions/node_modules/graphql/language/parser.js:1322:33)
    at parseDefinition (apollo-server-reproductions/node_modules/graphql/language/parser.js:152:9)
    at parseDocument (apollo-server-reproductions/node_modules/graphql/language/parser.js:110:22)
    at Object.parse (apollo-server-reproductions/node_modules/graphql/language/parser.js:38:10)
    at buildSchemaFromTypeDefinitions (apollo-server-reproductions/node_modules/graphql-tools/dist/schemaGenerator.js:178:33)
    at _generateSchema (apollo-server-reproductions/node_modules/graphql-tools/dist/schemaGenerator.js:97:18)
    at makeExecutableSchema (apollo-server-reproductions/node_modules/graphql-tools/dist/schemaGenerator.js:110:20)
    at Object.<anonymous> (apollo-server-reproductions/index.js:37:16)
    at Module._compile (module.js:662:30)
```

Similar query works in launchpad.

**Comment by chmac** [comment]
Never mind, looks like the syntax should be `Interface1 & Interface2` which does work. Apparently the comma syntax is supported in launchpad, but isn't the correct spec.
